#ifndef GUARD_CONSTANTS_FLAGS_FRLG_HNS_H
#define GUARD_CONSTANTS_FLAGS_FRLG_HNS_H

// Auto-generiert fuer den Kanto-Merge (test/kanto-start).
// flags_hns.h definiert diese FRLG-Flags als 0 (= FLAG_TEMP_0, wird bei
// jedem Kartenwechsel geloescht). Hier bekommen sie echte Slots.
//
// Quellen: FRLG-Kartenskripte, Objekt-/Coord-Flags aus den map.json und
// EventScript_ResetAllMapFlagsFrlg.

// Eigener Adressraum ausserhalb von SaveBlock1 (dort sind nur 4 Byte frei).
#define FRLG_FLAGS_START 0x3000

#undef  FLAG_BEAT_RIVAL_IN_OAKS_LAB
#define FLAG_BEAT_RIVAL_IN_OAKS_LAB                              (FRLG_FLAGS_START+0x0)
#undef  FLAG_BOUGHT_MAGIKARP
#define FLAG_BOUGHT_MAGIKARP                                     (FRLG_FLAGS_START+0x1)
#undef  FLAG_CAN_USE_ROCKET_HIDEOUT_LIFT
#define FLAG_CAN_USE_ROCKET_HIDEOUT_LIFT                         (FRLG_FLAGS_START+0x2)
#undef  FLAG_CINNABAR_GYM_QUIZ_1
#define FLAG_CINNABAR_GYM_QUIZ_1                                 (FRLG_FLAGS_START+0x3)
#undef  FLAG_CINNABAR_GYM_QUIZ_2
#define FLAG_CINNABAR_GYM_QUIZ_2                                 (FRLG_FLAGS_START+0x4)
#undef  FLAG_CINNABAR_GYM_QUIZ_3
#define FLAG_CINNABAR_GYM_QUIZ_3                                 (FRLG_FLAGS_START+0x5)
#undef  FLAG_CINNABAR_GYM_QUIZ_4
#define FLAG_CINNABAR_GYM_QUIZ_4                                 (FRLG_FLAGS_START+0x6)
#undef  FLAG_CINNABAR_GYM_QUIZ_5
#define FLAG_CINNABAR_GYM_QUIZ_5                                 (FRLG_FLAGS_START+0x7)
#undef  FLAG_CINNABAR_GYM_QUIZ_6
#define FLAG_CINNABAR_GYM_QUIZ_6                                 (FRLG_FLAGS_START+0x8)
#undef  FLAG_DEFEATED_AGATHA
#define FLAG_DEFEATED_AGATHA                                     (FRLG_FLAGS_START+0x9)
#undef  FLAG_DEFEATED_BLAINE
#define FLAG_DEFEATED_BLAINE                                     (FRLG_FLAGS_START+0xA)
#undef  FLAG_DEFEATED_BROCK
#define FLAG_DEFEATED_BROCK                                      (FRLG_FLAGS_START+0xB)
#undef  FLAG_DEFEATED_BRUNO
#define FLAG_DEFEATED_BRUNO                                      (FRLG_FLAGS_START+0xC)
#undef  FLAG_DEFEATED_CHAMP
#define FLAG_DEFEATED_CHAMP                                      (FRLG_FLAGS_START+0xD)
#undef  FLAG_DEFEATED_ERIKA
#define FLAG_DEFEATED_ERIKA                                      (FRLG_FLAGS_START+0xE)
#undef  FLAG_DEFEATED_KOGA
#define FLAG_DEFEATED_KOGA                                       (FRLG_FLAGS_START+0xF)
#undef  FLAG_DEFEATED_LANCE
#define FLAG_DEFEATED_LANCE                                      (FRLG_FLAGS_START+0x10)
#undef  FLAG_DEFEATED_LEADER_GIOVANNI
#define FLAG_DEFEATED_LEADER_GIOVANNI                            (FRLG_FLAGS_START+0x11)
#undef  FLAG_DEFEATED_LORELEI
#define FLAG_DEFEATED_LORELEI                                    (FRLG_FLAGS_START+0x12)
#undef  FLAG_DEFEATED_LT_SURGE
#define FLAG_DEFEATED_LT_SURGE                                   (FRLG_FLAGS_START+0x13)
#undef  FLAG_DEFEATED_MISTY
#define FLAG_DEFEATED_MISTY                                      (FRLG_FLAGS_START+0x14)
#undef  FLAG_DEFEATED_ROCKETS_IN_WAREHOUSE
#define FLAG_DEFEATED_ROCKETS_IN_WAREHOUSE                       (FRLG_FLAGS_START+0x15)
#undef  FLAG_DEFEATED_SABRINA
#define FLAG_DEFEATED_SABRINA                                    (FRLG_FLAGS_START+0x16)
#undef  FLAG_DID_CH_DING_TRADE
#define FLAG_DID_CH_DING_TRADE                                   (FRLG_FLAGS_START+0x17)
#undef  FLAG_DID_ESPHERE_TRADE
#define FLAG_DID_ESPHERE_TRADE                                   (FRLG_FLAGS_START+0x18)
#undef  FLAG_DID_MARC_TRADE
#define FLAG_DID_MARC_TRADE                                      (FRLG_FLAGS_START+0x19)
#undef  FLAG_DID_MIMIEN_TRADE
#define FLAG_DID_MIMIEN_TRADE                                    (FRLG_FLAGS_START+0x1A)
#undef  FLAG_DID_MS_NIDO_TRADE
#define FLAG_DID_MS_NIDO_TRADE                                   (FRLG_FLAGS_START+0x1B)
#undef  FLAG_DID_NINA_TRADE
#define FLAG_DID_NINA_TRADE                                      (FRLG_FLAGS_START+0x1C)
#undef  FLAG_DID_SEELOR_TRADE
#define FLAG_DID_SEELOR_TRADE                                    (FRLG_FLAGS_START+0x1D)
#undef  FLAG_DID_TANGENY_TRADE
#define FLAG_DID_TANGENY_TRADE                                   (FRLG_FLAGS_START+0x1E)
#undef  FLAG_DID_ZYNX_TRADE
#define FLAG_DID_ZYNX_TRADE                                      (FRLG_FLAGS_START+0x1F)
#undef  FLAG_FOUGHT_ARTICUNO
#define FLAG_FOUGHT_ARTICUNO                                     (FRLG_FLAGS_START+0x20)
#undef  FLAG_FOUGHT_HO_OH
#define FLAG_FOUGHT_HO_OH                                        (FRLG_FLAGS_START+0x21)
#undef  FLAG_FOUGHT_LUGIA
#define FLAG_FOUGHT_LUGIA                                        (FRLG_FLAGS_START+0x22)
#undef  FLAG_FOUGHT_MEWTWO
#define FLAG_FOUGHT_MEWTWO                                       (FRLG_FLAGS_START+0x23)
#undef  FLAG_FOUGHT_MOLTRES
#define FLAG_FOUGHT_MOLTRES                                      (FRLG_FLAGS_START+0x24)
#undef  FLAG_FOUGHT_POWER_PLANT_ELECTRODE_1
#define FLAG_FOUGHT_POWER_PLANT_ELECTRODE_1                      (FRLG_FLAGS_START+0x25)
#undef  FLAG_FOUGHT_POWER_PLANT_ELECTRODE_2
#define FLAG_FOUGHT_POWER_PLANT_ELECTRODE_2                      (FRLG_FLAGS_START+0x26)
#undef  FLAG_FOUGHT_ZAPDOS
#define FLAG_FOUGHT_ZAPDOS                                       (FRLG_FLAGS_START+0x27)
#undef  FLAG_GOT_10_COINS_FROM_GAMBLER
#define FLAG_GOT_10_COINS_FROM_GAMBLER                           (FRLG_FLAGS_START+0x28)
#undef  FLAG_GOT_20_COINS_FROM_GAMBLER
#define FLAG_GOT_20_COINS_FROM_GAMBLER                           (FRLG_FLAGS_START+0x29)
#undef  FLAG_GOT_20_COINS_FROM_GAMBLER_2
#define FLAG_GOT_20_COINS_FROM_GAMBLER_2                         (FRLG_FLAGS_START+0x2A)
#undef  FLAG_GOT_AMULET_COIN_FROM_OAKS_AIDE
#define FLAG_GOT_AMULET_COIN_FROM_OAKS_AIDE                      (FRLG_FLAGS_START+0x2B)
#undef  FLAG_GOT_BICYCLE
#define FLAG_GOT_BICYCLE                                         (FRLG_FLAGS_START+0x2C)
#undef  FLAG_GOT_BIKE_VOUCHER
#define FLAG_GOT_BIKE_VOUCHER                                    (FRLG_FLAGS_START+0x2D)
#undef  FLAG_GOT_COIN_CASE
#define FLAG_GOT_COIN_CASE                                       (FRLG_FLAGS_START+0x2E)
#undef  FLAG_GOT_DOME_FOSSIL
#define FLAG_GOT_DOME_FOSSIL                                     (FRLG_FLAGS_START+0x2F)
#undef  FLAG_GOT_EVERSTONE_FROM_OAKS_AIDE
#define FLAG_GOT_EVERSTONE_FROM_OAKS_AIDE                        (FRLG_FLAGS_START+0x30)
#undef  FLAG_GOT_EXP_SHARE_FROM_OAKS_AIDE
#define FLAG_GOT_EXP_SHARE_FROM_OAKS_AIDE                        (FRLG_FLAGS_START+0x31)
#undef  FLAG_GOT_FAME_CHECKER
#define FLAG_GOT_FAME_CHECKER                                    (FRLG_FLAGS_START+0x32)
#undef  FLAG_GOT_FOSSIL_FROM_MT_MOON
#define FLAG_GOT_FOSSIL_FROM_MT_MOON                             (FRLG_FLAGS_START+0x33)
#undef  FLAG_GOT_FULL_RESTORE_FROM_THREE_ISLAND_DEFENDER
#define FLAG_GOT_FULL_RESTORE_FROM_THREE_ISLAND_DEFENDER         (FRLG_FLAGS_START+0x34)
#undef  FLAG_GOT_GOOD_ROD
#define FLAG_GOT_GOOD_ROD                                        (FRLG_FLAGS_START+0x35)
#undef  FLAG_GOT_HELIX_FOSSIL
#define FLAG_GOT_HELIX_FOSSIL                                    (FRLG_FLAGS_START+0x36)
#undef  FLAG_GOT_HITMON_FROM_DOJO
#define FLAG_GOT_HITMON_FROM_DOJO                                (FRLG_FLAGS_START+0x37)
#undef  FLAG_GOT_HM01
#define FLAG_GOT_HM01                                            (FRLG_FLAGS_START+0x38)
#undef  FLAG_GOT_HM02
#define FLAG_GOT_HM02                                            (FRLG_FLAGS_START+0x39)
#undef  FLAG_GOT_HM03
#define FLAG_GOT_HM03                                            (FRLG_FLAGS_START+0x3A)
#undef  FLAG_GOT_HM04
#define FLAG_GOT_HM04                                            (FRLG_FLAGS_START+0x3B)
#undef  FLAG_GOT_HM05
#define FLAG_GOT_HM05                                            (FRLG_FLAGS_START+0x3C)
#undef  FLAG_GOT_HM06
#define FLAG_GOT_HM06                                            (FRLG_FLAGS_START+0x3D)
#undef  FLAG_GOT_ITEMFINDER
#define FLAG_GOT_ITEMFINDER                                      (FRLG_FLAGS_START+0x3E)
#undef  FLAG_GOT_LAPRAS_FROM_SILPH
#define FLAG_GOT_LAPRAS_FROM_SILPH                               (FRLG_FLAGS_START+0x3F)
#undef  FLAG_GOT_MASTER_BALL_FROM_SILPH
#define FLAG_GOT_MASTER_BALL_FROM_SILPH                          (FRLG_FLAGS_START+0x40)
#undef  FLAG_GOT_MOON_STONE_FROM_JOYFUL_GAME_CORNER
#define FLAG_GOT_MOON_STONE_FROM_JOYFUL_GAME_CORNER              (FRLG_FLAGS_START+0x41)
#undef  FLAG_GOT_NEST_BALL_FROM_WATER_PATH_HOUSE_1
#define FLAG_GOT_NEST_BALL_FROM_WATER_PATH_HOUSE_1               (FRLG_FLAGS_START+0x42)
#undef  FLAG_GOT_NUGGET_FROM_DUNSPARCE_TUNNEL
#define FLAG_GOT_NUGGET_FROM_DUNSPARCE_TUNNEL                    (FRLG_FLAGS_START+0x43)
#undef  FLAG_GOT_OLD_AMBER
#define FLAG_GOT_OLD_AMBER                                       (FRLG_FLAGS_START+0x44)
#undef  FLAG_GOT_OLD_ROD
#define FLAG_GOT_OLD_ROD                                         (FRLG_FLAGS_START+0x45)
#undef  FLAG_GOT_POKEBALLS_FROM_OAK_AFTER_22_RIVAL
#define FLAG_GOT_POKEBALLS_FROM_OAK_AFTER_22_RIVAL               (FRLG_FLAGS_START+0x46)
#undef  FLAG_GOT_POKE_FLUTE
#define FLAG_GOT_POKE_FLUTE                                      (FRLG_FLAGS_START+0x47)
#undef  FLAG_GOT_POTION_ON_ROUTE_1
#define FLAG_GOT_POTION_ON_ROUTE_1                               (FRLG_FLAGS_START+0x48)
#undef  FLAG_GOT_POWDER_JAR
#define FLAG_GOT_POWDER_JAR                                      (FRLG_FLAGS_START+0x49)
#undef  FLAG_GOT_RECORD_SETTING_MAGIKARP
#define FLAG_GOT_RECORD_SETTING_MAGIKARP                         (FRLG_FLAGS_START+0x4A)
#undef  FLAG_GOT_RUBY
#define FLAG_GOT_RUBY                                            (FRLG_FLAGS_START+0x4B)
#undef  FLAG_GOT_SS_TICKET
#define FLAG_GOT_SS_TICKET                                       (FRLG_FLAGS_START+0x4C)
#undef  FLAG_GOT_SS_TICKET_DUP
#define FLAG_GOT_SS_TICKET_DUP                                   (FRLG_FLAGS_START+0x4D)
#undef  FLAG_GOT_TEA
#define FLAG_GOT_TEA                                             (FRLG_FLAGS_START+0x4E)
#undef  FLAG_GOT_TM03_FROM_MISTY
#define FLAG_GOT_TM03_FROM_MISTY                                 (FRLG_FLAGS_START+0x4F)
#undef  FLAG_GOT_TM04_FROM_SABRINA
#define FLAG_GOT_TM04_FROM_SABRINA                               (FRLG_FLAGS_START+0x50)
#undef  FLAG_GOT_TM06_FROM_KOGA
#define FLAG_GOT_TM06_FROM_KOGA                                  (FRLG_FLAGS_START+0x51)
#undef  FLAG_GOT_TM16_FROM_THIRSTY_GIRL
#define FLAG_GOT_TM16_FROM_THIRSTY_GIRL                          (FRLG_FLAGS_START+0x52)
#undef  FLAG_GOT_TM19_FROM_ERIKA
#define FLAG_GOT_TM19_FROM_ERIKA                                 (FRLG_FLAGS_START+0x53)
#undef  FLAG_GOT_TM20_FROM_THIRSTY_GIRL
#define FLAG_GOT_TM20_FROM_THIRSTY_GIRL                          (FRLG_FLAGS_START+0x54)
#undef  FLAG_GOT_TM26_FROM_GIOVANNI
#define FLAG_GOT_TM26_FROM_GIOVANNI                              (FRLG_FLAGS_START+0x55)
#undef  FLAG_GOT_TM27
#define FLAG_GOT_TM27                                            (FRLG_FLAGS_START+0x56)
#undef  FLAG_GOT_TM28_FROM_ROCKET
#define FLAG_GOT_TM28_FROM_ROCKET                                (FRLG_FLAGS_START+0x57)
#undef  FLAG_GOT_TM29_FROM_MR_PSYCHIC
#define FLAG_GOT_TM29_FROM_MR_PSYCHIC                            (FRLG_FLAGS_START+0x58)
#undef  FLAG_GOT_TM33_FROM_THIRSTY_GIRL
#define FLAG_GOT_TM33_FROM_THIRSTY_GIRL                          (FRLG_FLAGS_START+0x59)
#undef  FLAG_GOT_TM34_FROM_SURGE
#define FLAG_GOT_TM34_FROM_SURGE                                 (FRLG_FLAGS_START+0x5A)
#undef  FLAG_GOT_TM38_FROM_BLAINE
#define FLAG_GOT_TM38_FROM_BLAINE                                (FRLG_FLAGS_START+0x5B)
#undef  FLAG_GOT_TM39_FROM_BROCK
#define FLAG_GOT_TM39_FROM_BROCK                                 (FRLG_FLAGS_START+0x5C)
#undef  FLAG_GOT_TM42_AT_MEMORIAL_PILLAR
#define FLAG_GOT_TM42_AT_MEMORIAL_PILLAR                         (FRLG_FLAGS_START+0x5D)
#undef  FLAG_GOT_TOGEPI_EGG
#define FLAG_GOT_TOGEPI_EGG                                      (FRLG_FLAGS_START+0x5E)
#undef  FLAG_GOT_VS_SEEKER
#define FLAG_GOT_VS_SEEKER                                       (FRLG_FLAGS_START+0x5F)
#undef  FLAG_HELPED_BILL_IN_SEA_COTTAGE
#define FLAG_HELPED_BILL_IN_SEA_COTTAGE                          (FRLG_FLAGS_START+0x60)
#undef  FLAG_HIDE_BILL_CLEFAIRY
#define FLAG_HIDE_BILL_CLEFAIRY                                  (FRLG_FLAGS_START+0x61)
#undef  FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE
#define FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE                         (FRLG_FLAGS_START+0x62)
#undef  FLAG_HIDE_BIRTH_ISLAND_METEORITE
#define FLAG_HIDE_BIRTH_ISLAND_METEORITE                         (FRLG_FLAGS_START+0x63)
#undef  FLAG_HIDE_BULBASAUR_BALL
#define FLAG_HIDE_BULBASAUR_BALL                                 (FRLG_FLAGS_START+0x64)
#undef  FLAG_HIDE_CELADON_CITY_ETHER
#define FLAG_HIDE_CELADON_CITY_ETHER                             (FRLG_FLAGS_START+0x65)
#undef  FLAG_HIDE_CELADON_ROCKETS
#define FLAG_HIDE_CELADON_ROCKETS                                (FRLG_FLAGS_START+0x66)
#undef  FLAG_HIDE_CERULEAN_CAVE_1F_FULL_RESTORE
#define FLAG_HIDE_CERULEAN_CAVE_1F_FULL_RESTORE                  (FRLG_FLAGS_START+0x67)
#undef  FLAG_HIDE_CERULEAN_CAVE_1F_MAX_ELIXIR
#define FLAG_HIDE_CERULEAN_CAVE_1F_MAX_ELIXIR                    (FRLG_FLAGS_START+0x68)
#undef  FLAG_HIDE_CERULEAN_CAVE_1F_NUGGET
#define FLAG_HIDE_CERULEAN_CAVE_1F_NUGGET                        (FRLG_FLAGS_START+0x69)
#undef  FLAG_HIDE_CERULEAN_CAVE_2F_FULL_RESTORE
#define FLAG_HIDE_CERULEAN_CAVE_2F_FULL_RESTORE                  (FRLG_FLAGS_START+0x6A)
#undef  FLAG_HIDE_CERULEAN_CAVE_2F_PP_UP
#define FLAG_HIDE_CERULEAN_CAVE_2F_PP_UP                         (FRLG_FLAGS_START+0x6B)
#undef  FLAG_HIDE_CERULEAN_CAVE_2F_ULTRA_BALL
#define FLAG_HIDE_CERULEAN_CAVE_2F_ULTRA_BALL                    (FRLG_FLAGS_START+0x6C)
#undef  FLAG_HIDE_CERULEAN_CAVE_B1F_MAX_REVIVE
#define FLAG_HIDE_CERULEAN_CAVE_B1F_MAX_REVIVE                   (FRLG_FLAGS_START+0x6D)
#undef  FLAG_HIDE_CERULEAN_CAVE_B1F_ULTRA_BALL
#define FLAG_HIDE_CERULEAN_CAVE_B1F_ULTRA_BALL                   (FRLG_FLAGS_START+0x6E)
#undef  FLAG_HIDE_CERULEAN_CAVE_GUARD
#define FLAG_HIDE_CERULEAN_CAVE_GUARD                            (FRLG_FLAGS_START+0x6F)
#undef  FLAG_HIDE_CERULEAN_RIVAL
#define FLAG_HIDE_CERULEAN_RIVAL                                 (FRLG_FLAGS_START+0x70)
#undef  FLAG_HIDE_CERULEAN_ROCKET
#define FLAG_HIDE_CERULEAN_ROCKET                                (FRLG_FLAGS_START+0x71)
#undef  FLAG_HIDE_CHARMANDER_BALL
#define FLAG_HIDE_CHARMANDER_BALL                                (FRLG_FLAGS_START+0x72)
#undef  FLAG_HIDE_CINNABAR_BILL
#define FLAG_HIDE_CINNABAR_BILL                                  (FRLG_FLAGS_START+0x73)
#undef  FLAG_HIDE_CINNABAR_POKECENTER_BILL
#define FLAG_HIDE_CINNABAR_POKECENTER_BILL                       (FRLG_FLAGS_START+0x74)
#undef  FLAG_HIDE_CINNABAR_SEAGALLOP
#define FLAG_HIDE_CINNABAR_SEAGALLOP                             (FRLG_FLAGS_START+0x75)
#undef  FLAG_HIDE_CREDITS_OAK
#define FLAG_HIDE_CREDITS_OAK                                    (FRLG_FLAGS_START+0x76)
#undef  FLAG_HIDE_CREDITS_RIVAL
#define FLAG_HIDE_CREDITS_RIVAL                                  (FRLG_FLAGS_START+0x77)
#undef  FLAG_HIDE_DOJO_HITMONCHAN_BALL
#define FLAG_HIDE_DOJO_HITMONCHAN_BALL                           (FRLG_FLAGS_START+0x78)
#undef  FLAG_HIDE_DOJO_HITMONLEE_BALL
#define FLAG_HIDE_DOJO_HITMONLEE_BALL                            (FRLG_FLAGS_START+0x79)
#undef  FLAG_HIDE_DOME_FOSSIL
#define FLAG_HIDE_DOME_FOSSIL                                    (FRLG_FLAGS_START+0x7A)
#undef  FLAG_HIDE_DOTTED_HOLE_SCIENTIST
#define FLAG_HIDE_DOTTED_HOLE_SCIENTIST                          (FRLG_FLAGS_START+0x7B)
#undef  FLAG_HIDE_EEVEE_BALL
#define FLAG_HIDE_EEVEE_BALL                                     (FRLG_FLAGS_START+0x7C)
#undef  FLAG_HIDE_FAME_CHECKER_ERIKA_JOURNALS
#define FLAG_HIDE_FAME_CHECKER_ERIKA_JOURNALS                    (FRLG_FLAGS_START+0x7D)
#undef  FLAG_HIDE_FAME_CHECKER_KOGA_JOURNAL
#define FLAG_HIDE_FAME_CHECKER_KOGA_JOURNAL                      (FRLG_FLAGS_START+0x7E)
#undef  FLAG_HIDE_FAME_CHECKER_LT_SURGE_JOURNAL
#define FLAG_HIDE_FAME_CHECKER_LT_SURGE_JOURNAL                  (FRLG_FLAGS_START+0x7F)
#undef  FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM10_SILK_SCARF
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM10_SILK_SCARF        (FRLG_FLAGS_START+0x80)
#undef  FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM11_LAX_INCENSE
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM11_LAX_INCENSE       (FRLG_FLAGS_START+0x81)
#undef  FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM12_SEA_INCENSE
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM12_SEA_INCENSE       (FRLG_FLAGS_START+0x82)
#undef  FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM13_MAX_REVIVE
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM13_MAX_REVIVE        (FRLG_FLAGS_START+0x83)
#undef  FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM14_RARE_CANDY
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM14_RARE_CANDY        (FRLG_FLAGS_START+0x84)
#undef  FLAG_HIDE_FIVE_ISLAND_MEADOW_MAX_POTION
#define FLAG_HIDE_FIVE_ISLAND_MEADOW_MAX_POTION                  (FRLG_FLAGS_START+0x85)
#undef  FLAG_HIDE_FIVE_ISLAND_MEADOW_PP_UP
#define FLAG_HIDE_FIVE_ISLAND_MEADOW_PP_UP                       (FRLG_FLAGS_START+0x86)
#undef  FLAG_HIDE_FIVE_ISLAND_MEMORIAL_PILLAR_METAL_COAT
#define FLAG_HIDE_FIVE_ISLAND_MEMORIAL_PILLAR_METAL_COAT         (FRLG_FLAGS_START+0x87)
#undef  FLAG_HIDE_FIVE_ISLAND_ROCKETS
#define FLAG_HIDE_FIVE_ISLAND_ROCKETS                            (FRLG_FLAGS_START+0x88)
#undef  FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_BIG_PEARL
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_BIG_PEARL         (FRLG_FLAGS_START+0x89)
#undef  FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_PEARL
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_PEARL             (FRLG_FLAGS_START+0x8A)
#undef  FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_TM36
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_TM36              (FRLG_FLAGS_START+0x8B)
#undef  FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_UP_GRADE
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_UP_GRADE          (FRLG_FLAGS_START+0x8C)
#undef  FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_HM07
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_HM07               (FRLG_FLAGS_START+0x8D)
#undef  FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_ULTRA_BALL
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_ULTRA_BALL         (FRLG_FLAGS_START+0x8E)
#undef  FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_FULL_RESTORE
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_FULL_RESTORE      (FRLG_FLAGS_START+0x8F)
#undef  FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_NEVER_MELT_ICE
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_NEVER_MELT_ICE    (FRLG_FLAGS_START+0x90)
#undef  FLAG_HIDE_FOUR_ISLAND_RIVAL
#define FLAG_HIDE_FOUR_ISLAND_RIVAL                              (FRLG_FLAGS_START+0x91)
#undef  FLAG_HIDE_FOUR_ISLAND_STARDUST
#define FLAG_HIDE_FOUR_ISLAND_STARDUST                           (FRLG_FLAGS_START+0x92)
#undef  FLAG_HIDE_FOUR_ISLAND_STAR_PIECE
#define FLAG_HIDE_FOUR_ISLAND_STAR_PIECE                         (FRLG_FLAGS_START+0x93)
#undef  FLAG_HIDE_FUCHSIA_CITY_WARDENS_HOUSE_RARE_CANDY
#define FLAG_HIDE_FUCHSIA_CITY_WARDENS_HOUSE_RARE_CANDY          (FRLG_FLAGS_START+0x94)
#undef  FLAG_HIDE_GAME_CORNER_ROCKET
#define FLAG_HIDE_GAME_CORNER_ROCKET                             (FRLG_FLAGS_START+0x95)
#undef  FLAG_HIDE_HELIX_FOSSIL
#define FLAG_HIDE_HELIX_FOSSIL                                   (FRLG_FLAGS_START+0x96)
#undef  FLAG_HIDE_HIDEOUT_GIOVANNI
#define FLAG_HIDE_HIDEOUT_GIOVANNI                               (FRLG_FLAGS_START+0x97)
#undef  FLAG_HIDE_ICEFALL_CAVE_LORELEI
#define FLAG_HIDE_ICEFALL_CAVE_LORELEI                           (FRLG_FLAGS_START+0x98)
#undef  FLAG_HIDE_ICEFALL_CAVE_ROCKETS
#define FLAG_HIDE_ICEFALL_CAVE_ROCKETS                           (FRLG_FLAGS_START+0x99)
#undef  FLAG_HIDE_LIFT_KEY
#define FLAG_HIDE_LIFT_KEY                                       (FRLG_FLAGS_START+0x9A)
#undef  FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL                     (FRLG_FLAGS_START+0x9B)
#undef  FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL                     (FRLG_FLAGS_START+0x9C)
#undef  FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL                  (FRLG_FLAGS_START+0x9D)
#undef  FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL                  (FRLG_FLAGS_START+0x9E)
#undef  FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL                    (FRLG_FLAGS_START+0x9F)
#undef  FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL                     (FRLG_FLAGS_START+0xA0)
#undef  FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL                  (FRLG_FLAGS_START+0xA1)
#undef  FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL                      (FRLG_FLAGS_START+0xA2)
#undef  FLAG_HIDE_LORELEI_IN_HER_HOUSE
#define FLAG_HIDE_LORELEI_IN_HER_HOUSE                           (FRLG_FLAGS_START+0xA3)
#undef  FLAG_HIDE_LOSTELLE_IN_BERRY_FOREST
#define FLAG_HIDE_LOSTELLE_IN_BERRY_FOREST                       (FRLG_FLAGS_START+0xA4)
#undef  FLAG_HIDE_LOSTELLE_IN_HER_HOME
#define FLAG_HIDE_LOSTELLE_IN_HER_HOME                           (FRLG_FLAGS_START+0xA5)
#undef  FLAG_HIDE_LOST_CAVE_SELPHY
#define FLAG_HIDE_LOST_CAVE_SELPHY                               (FRLG_FLAGS_START+0xA6)
#undef  FLAG_HIDE_MG_DELIVERYMEN
#define FLAG_HIDE_MG_DELIVERYMEN                                 (FRLG_FLAGS_START+0xA7)
#undef  FLAG_HIDE_MISC_KANTO_ROCKETS
#define FLAG_HIDE_MISC_KANTO_ROCKETS                             (FRLG_FLAGS_START+0xA8)
#undef  FLAG_HIDE_MT_EMBER_EXTERIOR_DIRE_HIT
#define FLAG_HIDE_MT_EMBER_EXTERIOR_DIRE_HIT                     (FRLG_FLAGS_START+0xA9)
#undef  FLAG_HIDE_MT_EMBER_EXTERIOR_FIRE_STONE
#define FLAG_HIDE_MT_EMBER_EXTERIOR_FIRE_STONE                   (FRLG_FLAGS_START+0xAA)
#undef  FLAG_HIDE_MT_EMBER_EXTERIOR_ROCKETS
#define FLAG_HIDE_MT_EMBER_EXTERIOR_ROCKETS                      (FRLG_FLAGS_START+0xAB)
#undef  FLAG_HIDE_MT_EMBER_EXTERIOR_ULTRA_BALL
#define FLAG_HIDE_MT_EMBER_EXTERIOR_ULTRA_BALL                   (FRLG_FLAGS_START+0xAC)
#undef  FLAG_HIDE_MT_MOON_1F_ESCAPE_ROPE
#define FLAG_HIDE_MT_MOON_1F_ESCAPE_ROPE                         (FRLG_FLAGS_START+0xAD)
#undef  FLAG_HIDE_MT_MOON_1F_MOON_STONE
#define FLAG_HIDE_MT_MOON_1F_MOON_STONE                          (FRLG_FLAGS_START+0xAE)
#undef  FLAG_HIDE_MT_MOON_1F_PARALYZE_HEAL
#define FLAG_HIDE_MT_MOON_1F_PARALYZE_HEAL                       (FRLG_FLAGS_START+0xAF)
#undef  FLAG_HIDE_MT_MOON_1F_POTION
#define FLAG_HIDE_MT_MOON_1F_POTION                              (FRLG_FLAGS_START+0xB0)
#undef  FLAG_HIDE_MT_MOON_1F_RARE_CANDY
#define FLAG_HIDE_MT_MOON_1F_RARE_CANDY                          (FRLG_FLAGS_START+0xB1)
#undef  FLAG_HIDE_MT_MOON_1F_TM09
#define FLAG_HIDE_MT_MOON_1F_TM09                                (FRLG_FLAGS_START+0xB2)
#undef  FLAG_HIDE_MT_MOON_B2F_ANTIDOTE
#define FLAG_HIDE_MT_MOON_B2F_ANTIDOTE                           (FRLG_FLAGS_START+0xB3)
#undef  FLAG_HIDE_MT_MOON_B2F_REVIVE
#define FLAG_HIDE_MT_MOON_B2F_REVIVE                             (FRLG_FLAGS_START+0xB4)
#undef  FLAG_HIDE_MT_MOON_B2F_STAR_PIECE
#define FLAG_HIDE_MT_MOON_B2F_STAR_PIECE                         (FRLG_FLAGS_START+0xB5)
#undef  FLAG_HIDE_MT_MOON_B2F_TM46
#define FLAG_HIDE_MT_MOON_B2F_TM46                               (FRLG_FLAGS_START+0xB6)
#undef  FLAG_HIDE_NUGGET_BRIDGE_ROCKET
#define FLAG_HIDE_NUGGET_BRIDGE_ROCKET                           (FRLG_FLAGS_START+0xB7)
#undef  FLAG_HIDE_OAK_IN_CHAMP_ROOM
#define FLAG_HIDE_OAK_IN_CHAMP_ROOM                              (FRLG_FLAGS_START+0xB8)
#undef  FLAG_HIDE_OAK_IN_HIS_LAB
#define FLAG_HIDE_OAK_IN_HIS_LAB                                 (FRLG_FLAGS_START+0xB9)
#undef  FLAG_HIDE_OAK_IN_PALLET_TOWN
#define FLAG_HIDE_OAK_IN_PALLET_TOWN                             (FRLG_FLAGS_START+0xBA)
#undef  FLAG_HIDE_OLD_AMBER
#define FLAG_HIDE_OLD_AMBER                                      (FRLG_FLAGS_START+0xBB)
#undef  FLAG_HIDE_ONE_ISLAND_BILL
#define FLAG_HIDE_ONE_ISLAND_BILL                                (FRLG_FLAGS_START+0xBC)
#undef  FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_CARBOS
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_CARBOS                  (FRLG_FLAGS_START+0xBD)
#undef  FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_ETHER
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_ETHER                   (FRLG_FLAGS_START+0xBE)
#undef  FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_MAX_REPEL
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_MAX_REPEL               (FRLG_FLAGS_START+0xBF)
#undef  FLAG_HIDE_ONE_ISLAND_POKECENTER_BILL
#define FLAG_HIDE_ONE_ISLAND_POKECENTER_BILL                     (FRLG_FLAGS_START+0xC0)
#undef  FLAG_HIDE_ONE_ISLAND_POKECENTER_CELIO
#define FLAG_HIDE_ONE_ISLAND_POKECENTER_CELIO                    (FRLG_FLAGS_START+0xC1)
#undef  FLAG_HIDE_PEWTER_CITY_GYM_GUIDE
#define FLAG_HIDE_PEWTER_CITY_GYM_GUIDE                          (FRLG_FLAGS_START+0xC2)
#undef  FLAG_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY
#define FLAG_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY                  (FRLG_FLAGS_START+0xC3)
#undef  FLAG_HIDE_PEWTER_MUSEUM_GUIDE
#define FLAG_HIDE_PEWTER_MUSEUM_GUIDE                            (FRLG_FLAGS_START+0xC4)
#undef  FLAG_HIDE_POKEDEX
#define FLAG_HIDE_POKEDEX                                        (FRLG_FLAGS_START+0xC5)
#undef  FLAG_HIDE_POKEHOUSE_FUJI
#define FLAG_HIDE_POKEHOUSE_FUJI                                 (FRLG_FLAGS_START+0xC6)
#undef  FLAG_HIDE_POKEMON_MANSION_1F_CARBOS
#define FLAG_HIDE_POKEMON_MANSION_1F_CARBOS                      (FRLG_FLAGS_START+0xC7)
#undef  FLAG_HIDE_POKEMON_MANSION_1F_ESCAPE_ROPE
#define FLAG_HIDE_POKEMON_MANSION_1F_ESCAPE_ROPE                 (FRLG_FLAGS_START+0xC8)
#undef  FLAG_HIDE_POKEMON_MANSION_1F_PROTEIN
#define FLAG_HIDE_POKEMON_MANSION_1F_PROTEIN                     (FRLG_FLAGS_START+0xC9)
#undef  FLAG_HIDE_POKEMON_MANSION_2F_CALCIUM
#define FLAG_HIDE_POKEMON_MANSION_2F_CALCIUM                     (FRLG_FLAGS_START+0xCA)
#undef  FLAG_HIDE_POKEMON_MANSION_2F_HP_UP
#define FLAG_HIDE_POKEMON_MANSION_2F_HP_UP                       (FRLG_FLAGS_START+0xCB)
#undef  FLAG_HIDE_POKEMON_MANSION_2F_ZINC
#define FLAG_HIDE_POKEMON_MANSION_2F_ZINC                        (FRLG_FLAGS_START+0xCC)
#undef  FLAG_HIDE_POKEMON_MANSION_3F_IRON
#define FLAG_HIDE_POKEMON_MANSION_3F_IRON                        (FRLG_FLAGS_START+0xCD)
#undef  FLAG_HIDE_POKEMON_MANSION_3F_MAX_POTION
#define FLAG_HIDE_POKEMON_MANSION_3F_MAX_POTION                  (FRLG_FLAGS_START+0xCE)
#undef  FLAG_HIDE_POKEMON_MANSION_B1F_FULL_RESTORE
#define FLAG_HIDE_POKEMON_MANSION_B1F_FULL_RESTORE               (FRLG_FLAGS_START+0xCF)
#undef  FLAG_HIDE_POKEMON_MANSION_B1F_SECRET_KEY
#define FLAG_HIDE_POKEMON_MANSION_B1F_SECRET_KEY                 (FRLG_FLAGS_START+0xD0)
#undef  FLAG_HIDE_POKEMON_MANSION_B1F_TM14
#define FLAG_HIDE_POKEMON_MANSION_B1F_TM14                       (FRLG_FLAGS_START+0xD1)
#undef  FLAG_HIDE_POKEMON_MANSION_B1F_TM22
#define FLAG_HIDE_POKEMON_MANSION_B1F_TM22                       (FRLG_FLAGS_START+0xD2)
#undef  FLAG_HIDE_POKEMON_TOWER_3F_ESCAPE_ROPE
#define FLAG_HIDE_POKEMON_TOWER_3F_ESCAPE_ROPE                   (FRLG_FLAGS_START+0xD3)
#undef  FLAG_HIDE_POKEMON_TOWER_4F_AWAKENING
#define FLAG_HIDE_POKEMON_TOWER_4F_AWAKENING                     (FRLG_FLAGS_START+0xD4)
#undef  FLAG_HIDE_POKEMON_TOWER_4F_ELIXIR
#define FLAG_HIDE_POKEMON_TOWER_4F_ELIXIR                        (FRLG_FLAGS_START+0xD5)
#undef  FLAG_HIDE_POKEMON_TOWER_4F_GREAT_BALL
#define FLAG_HIDE_POKEMON_TOWER_4F_GREAT_BALL                    (FRLG_FLAGS_START+0xD6)
#undef  FLAG_HIDE_POKEMON_TOWER_5F_CLEANSE_TAG
#define FLAG_HIDE_POKEMON_TOWER_5F_CLEANSE_TAG                   (FRLG_FLAGS_START+0xD7)
#undef  FLAG_HIDE_POKEMON_TOWER_5F_NUGGET
#define FLAG_HIDE_POKEMON_TOWER_5F_NUGGET                        (FRLG_FLAGS_START+0xD8)
#undef  FLAG_HIDE_POKEMON_TOWER_6F_RARE_CANDY
#define FLAG_HIDE_POKEMON_TOWER_6F_RARE_CANDY                    (FRLG_FLAGS_START+0xD9)
#undef  FLAG_HIDE_POKEMON_TOWER_6F_X_ACCURACY
#define FLAG_HIDE_POKEMON_TOWER_6F_X_ACCURACY                    (FRLG_FLAGS_START+0xDA)
#undef  FLAG_HIDE_POSTGAME_GOSSIPERS
#define FLAG_HIDE_POSTGAME_GOSSIPERS                             (FRLG_FLAGS_START+0xDB)
#undef  FLAG_HIDE_POWER_PLANT_ELECTRODE_1
#define FLAG_HIDE_POWER_PLANT_ELECTRODE_1                        (FRLG_FLAGS_START+0xDC)
#undef  FLAG_HIDE_POWER_PLANT_ELECTRODE_2
#define FLAG_HIDE_POWER_PLANT_ELECTRODE_2                        (FRLG_FLAGS_START+0xDD)
#undef  FLAG_HIDE_POWER_PLANT_ELIXIR
#define FLAG_HIDE_POWER_PLANT_ELIXIR                             (FRLG_FLAGS_START+0xDE)
#undef  FLAG_HIDE_POWER_PLANT_MAX_POTION
#define FLAG_HIDE_POWER_PLANT_MAX_POTION                         (FRLG_FLAGS_START+0xDF)
#undef  FLAG_HIDE_POWER_PLANT_THUNDER_STONE
#define FLAG_HIDE_POWER_PLANT_THUNDER_STONE                      (FRLG_FLAGS_START+0xE0)
#undef  FLAG_HIDE_POWER_PLANT_TM17
#define FLAG_HIDE_POWER_PLANT_TM17                               (FRLG_FLAGS_START+0xE1)
#undef  FLAG_HIDE_POWER_PLANT_TM25
#define FLAG_HIDE_POWER_PLANT_TM25                               (FRLG_FLAGS_START+0xE2)
#undef  FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY
#define FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY                  (FRLG_FLAGS_START+0xE3)
#undef  FLAG_HIDE_RESORT_GORGEOUS_SELPHY
#define FLAG_HIDE_RESORT_GORGEOUS_SELPHY                         (FRLG_FLAGS_START+0xE4)
#undef  FLAG_HIDE_RIVAL_IN_LAB
#define FLAG_HIDE_RIVAL_IN_LAB                                   (FRLG_FLAGS_START+0xE5)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B1F_ESCAPE_ROPE
#define FLAG_HIDE_ROCKET_HIDEOUT_B1F_ESCAPE_ROPE                 (FRLG_FLAGS_START+0xE6)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B1F_HYPER_POTION
#define FLAG_HIDE_ROCKET_HIDEOUT_B1F_HYPER_POTION                (FRLG_FLAGS_START+0xE7)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B2F_MOON_STONE
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_MOON_STONE                  (FRLG_FLAGS_START+0xE8)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B2F_SUPER_POTION
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_SUPER_POTION                (FRLG_FLAGS_START+0xE9)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B2F_TM12
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_TM12                        (FRLG_FLAGS_START+0xEA)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B2F_X_SPEED
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_X_SPEED                     (FRLG_FLAGS_START+0xEB)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B3F_BLACK_GLASSES
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_BLACK_GLASSES               (FRLG_FLAGS_START+0xEC)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B3F_RARE_CANDY
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_RARE_CANDY                  (FRLG_FLAGS_START+0xED)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B3F_TM21
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_TM21                        (FRLG_FLAGS_START+0xEE)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B4F_CALCIUM
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_CALCIUM                     (FRLG_FLAGS_START+0xEF)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B4F_MAX_ETHER
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_MAX_ETHER                   (FRLG_FLAGS_START+0xF0)
#undef  FLAG_HIDE_ROCKET_HIDEOUT_B4F_TM49
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_TM49                        (FRLG_FLAGS_START+0xF1)
#undef  FLAG_HIDE_ROCK_TUNNEL_1F_ESCAPE_ROPE
#define FLAG_HIDE_ROCK_TUNNEL_1F_ESCAPE_ROPE                     (FRLG_FLAGS_START+0xF2)
#undef  FLAG_HIDE_ROCK_TUNNEL_1F_PEARL
#define FLAG_HIDE_ROCK_TUNNEL_1F_PEARL                           (FRLG_FLAGS_START+0xF3)
#undef  FLAG_HIDE_ROCK_TUNNEL_1F_REPEL
#define FLAG_HIDE_ROCK_TUNNEL_1F_REPEL                           (FRLG_FLAGS_START+0xF4)
#undef  FLAG_HIDE_ROCK_TUNNEL_B1F_MAX_ETHER
#define FLAG_HIDE_ROCK_TUNNEL_B1F_MAX_ETHER                      (FRLG_FLAGS_START+0xF5)
#undef  FLAG_HIDE_ROCK_TUNNEL_B1F_REVIVE
#define FLAG_HIDE_ROCK_TUNNEL_B1F_REVIVE                         (FRLG_FLAGS_START+0xF6)
#undef  FLAG_HIDE_ROUTE11_AWAKENING
#define FLAG_HIDE_ROUTE11_AWAKENING                              (FRLG_FLAGS_START+0xF7)
#undef  FLAG_HIDE_ROUTE11_GREAT_BALL
#define FLAG_HIDE_ROUTE11_GREAT_BALL                             (FRLG_FLAGS_START+0xF8)
#undef  FLAG_HIDE_ROUTE11_X_DEFEND
#define FLAG_HIDE_ROUTE11_X_DEFEND                               (FRLG_FLAGS_START+0xF9)
#undef  FLAG_HIDE_ROUTE12_IRON
#define FLAG_HIDE_ROUTE12_IRON                                   (FRLG_FLAGS_START+0xFA)
#undef  FLAG_HIDE_ROUTE12_TM48
#define FLAG_HIDE_ROUTE12_TM48                                   (FRLG_FLAGS_START+0xFB)
#undef  FLAG_HIDE_ROUTE15_TM18
#define FLAG_HIDE_ROUTE15_TM18                                   (FRLG_FLAGS_START+0xFC)
#undef  FLAG_HIDE_ROUTE24_TM45
#define FLAG_HIDE_ROUTE24_TM45                                   (FRLG_FLAGS_START+0xFD)
#undef  FLAG_HIDE_ROUTE25_TM43
#define FLAG_HIDE_ROUTE25_TM43                                   (FRLG_FLAGS_START+0xFE)
#undef  FLAG_HIDE_ROUTE2_ETHER
#define FLAG_HIDE_ROUTE2_ETHER                                   (FRLG_FLAGS_START+0xFF)
#undef  FLAG_HIDE_ROUTE2_PARALYZE_HEAL
#define FLAG_HIDE_ROUTE2_PARALYZE_HEAL                           (FRLG_FLAGS_START+0x100)
#undef  FLAG_HIDE_ROUTE4_TM05
#define FLAG_HIDE_ROUTE4_TM05                                    (FRLG_FLAGS_START+0x101)
#undef  FLAG_HIDE_ROUTE9_BURN_HEAL
#define FLAG_HIDE_ROUTE9_BURN_HEAL                               (FRLG_FLAGS_START+0x102)
#undef  FLAG_HIDE_ROUTE9_TM40
#define FLAG_HIDE_ROUTE9_TM40                                    (FRLG_FLAGS_START+0x103)
#undef  FLAG_HIDE_ROUTE_12_SNORLAX
#define FLAG_HIDE_ROUTE_12_SNORLAX                               (FRLG_FLAGS_START+0x104)
#undef  FLAG_HIDE_ROUTE_16_SNORLAX
#define FLAG_HIDE_ROUTE_16_SNORLAX                               (FRLG_FLAGS_START+0x105)
#undef  FLAG_HIDE_ROUTE_22_RIVAL
#define FLAG_HIDE_ROUTE_22_RIVAL                                 (FRLG_FLAGS_START+0x106)
#undef  FLAG_HIDE_RUBY
#define FLAG_HIDE_RUBY                                           (FRLG_FLAGS_START+0x107)
#undef  FLAG_HIDE_RUIN_VALLEY_SCIENTIST
#define FLAG_HIDE_RUIN_VALLEY_SCIENTIST                          (FRLG_FLAGS_START+0x108)
#undef  FLAG_HIDE_SAFARI_ZONE_CENTER_NUGGET
#define FLAG_HIDE_SAFARI_ZONE_CENTER_NUGGET                      (FRLG_FLAGS_START+0x109)
#undef  FLAG_HIDE_SAFARI_ZONE_EAST_FULL_RESTORE
#define FLAG_HIDE_SAFARI_ZONE_EAST_FULL_RESTORE                  (FRLG_FLAGS_START+0x10A)
#undef  FLAG_HIDE_SAFARI_ZONE_EAST_LEAF_STONE
#define FLAG_HIDE_SAFARI_ZONE_EAST_LEAF_STONE                    (FRLG_FLAGS_START+0x10B)
#undef  FLAG_HIDE_SAFARI_ZONE_EAST_MAX_POTION
#define FLAG_HIDE_SAFARI_ZONE_EAST_MAX_POTION                    (FRLG_FLAGS_START+0x10C)
#undef  FLAG_HIDE_SAFARI_ZONE_EAST_TM11
#define FLAG_HIDE_SAFARI_ZONE_EAST_TM11                          (FRLG_FLAGS_START+0x10D)
#undef  FLAG_HIDE_SAFARI_ZONE_NORTH_PROTEIN
#define FLAG_HIDE_SAFARI_ZONE_NORTH_PROTEIN                      (FRLG_FLAGS_START+0x10E)
#undef  FLAG_HIDE_SAFARI_ZONE_NORTH_QUICK_CLAW
#define FLAG_HIDE_SAFARI_ZONE_NORTH_QUICK_CLAW                   (FRLG_FLAGS_START+0x10F)
#undef  FLAG_HIDE_SAFARI_ZONE_NORTH_TM47
#define FLAG_HIDE_SAFARI_ZONE_NORTH_TM47                         (FRLG_FLAGS_START+0x110)
#undef  FLAG_HIDE_SAFARI_ZONE_WEST_GOLD_TEETH
#define FLAG_HIDE_SAFARI_ZONE_WEST_GOLD_TEETH                    (FRLG_FLAGS_START+0x111)
#undef  FLAG_HIDE_SAFARI_ZONE_WEST_MAX_POTION
#define FLAG_HIDE_SAFARI_ZONE_WEST_MAX_POTION                    (FRLG_FLAGS_START+0x112)
#undef  FLAG_HIDE_SAFARI_ZONE_WEST_MAX_REVIVE
#define FLAG_HIDE_SAFARI_ZONE_WEST_MAX_REVIVE                    (FRLG_FLAGS_START+0x113)
#undef  FLAG_HIDE_SAFARI_ZONE_WEST_TM32
#define FLAG_HIDE_SAFARI_ZONE_WEST_TM32                          (FRLG_FLAGS_START+0x114)
#undef  FLAG_HIDE_SAFFRON_CITY_POKECENTER_SABRINA_JOURNALS
#define FLAG_HIDE_SAFFRON_CITY_POKECENTER_SABRINA_JOURNALS       (FRLG_FLAGS_START+0x115)
#undef  FLAG_HIDE_SAFFRON_CIVILIANS
#define FLAG_HIDE_SAFFRON_CIVILIANS                              (FRLG_FLAGS_START+0x116)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY                        (FRLG_FLAGS_START+0x117)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT                     (FRLG_FLAGS_START+0x118)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER
#define FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER                        (FRLG_FLAGS_START+0x119)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN
#define FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN                         (FRLG_FLAGS_START+0x11A)
#undef  FLAG_HIDE_SAFFRON_ROCKETS
#define FLAG_HIDE_SAFFRON_ROCKETS                                (FRLG_FLAGS_START+0x11B)
#undef  FLAG_HIDE_SAPPHIRE
#define FLAG_HIDE_SAPPHIRE                                       (FRLG_FLAGS_START+0x11C)
#undef  FLAG_HIDE_SEAFOAM_1F_BOULDER_1
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_1                           (FRLG_FLAGS_START+0x11D)
#undef  FLAG_HIDE_SEAFOAM_1F_BOULDER_2
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_2                           (FRLG_FLAGS_START+0x11E)
#undef  FLAG_HIDE_SEAFOAM_B1F_BOULDER_1
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_1                          (FRLG_FLAGS_START+0x11F)
#undef  FLAG_HIDE_SEAFOAM_B1F_BOULDER_2
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_2                          (FRLG_FLAGS_START+0x120)
#undef  FLAG_HIDE_SEAFOAM_B2F_BOULDER_1
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_1                          (FRLG_FLAGS_START+0x121)
#undef  FLAG_HIDE_SEAFOAM_B2F_BOULDER_2
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_2                          (FRLG_FLAGS_START+0x122)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_1
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_1                          (FRLG_FLAGS_START+0x123)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_2
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_2                          (FRLG_FLAGS_START+0x124)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_3
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_3                          (FRLG_FLAGS_START+0x125)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_4
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_4                          (FRLG_FLAGS_START+0x126)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_5
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_5                          (FRLG_FLAGS_START+0x127)
#undef  FLAG_HIDE_SEAFOAM_B3F_BOULDER_6
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_6                          (FRLG_FLAGS_START+0x128)
#undef  FLAG_HIDE_SEAFOAM_B4F_BOULDER_1
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_1                          (FRLG_FLAGS_START+0x129)
#undef  FLAG_HIDE_SEAFOAM_B4F_BOULDER_2
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_2                          (FRLG_FLAGS_START+0x12A)
#undef  FLAG_HIDE_SEAFOAM_ISLANDS_1F_ICE_HEAL
#define FLAG_HIDE_SEAFOAM_ISLANDS_1F_ICE_HEAL                    (FRLG_FLAGS_START+0x12B)
#undef  FLAG_HIDE_SEAFOAM_ISLANDS_B1F_REVIVE
#define FLAG_HIDE_SEAFOAM_ISLANDS_B1F_REVIVE                     (FRLG_FLAGS_START+0x12C)
#undef  FLAG_HIDE_SEAFOAM_ISLANDS_B1F_WATER_STONE
#define FLAG_HIDE_SEAFOAM_ISLANDS_B1F_WATER_STONE                (FRLG_FLAGS_START+0x12D)
#undef  FLAG_HIDE_SEAFOAM_ISLANDS_B2F_BIG_PEARL
#define FLAG_HIDE_SEAFOAM_ISLANDS_B2F_BIG_PEARL                  (FRLG_FLAGS_START+0x12E)
#undef  FLAG_HIDE_SEAFOAM_ISLANDS_B4F_ULTRA_BALL
#define FLAG_HIDE_SEAFOAM_ISLANDS_B4F_ULTRA_BALL                 (FRLG_FLAGS_START+0x12F)
#undef  FLAG_HIDE_SELPHYS_BUTLER
#define FLAG_HIDE_SELPHYS_BUTLER                                 (FRLG_FLAGS_START+0x130)
#undef  FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE_LUCKY_PUNCH
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE_LUCKY_PUNCH  (FRLG_FLAGS_START+0x131)
#undef  FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_KINGS_ROCK
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_KINGS_ROCK         (FRLG_FLAGS_START+0x132)
#undef  FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_MAX_ELIXIR
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_MAX_ELIXIR         (FRLG_FLAGS_START+0x133)
#undef  FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_NUGGET
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_NUGGET             (FRLG_FLAGS_START+0x134)
#undef  FLAG_HIDE_SILPH_CO_10F_CARBOS
#define FLAG_HIDE_SILPH_CO_10F_CARBOS                            (FRLG_FLAGS_START+0x135)
#undef  FLAG_HIDE_SILPH_CO_10F_RARE_CANDY
#define FLAG_HIDE_SILPH_CO_10F_RARE_CANDY                        (FRLG_FLAGS_START+0x136)
#undef  FLAG_HIDE_SILPH_CO_10F_ULTRA_BALL
#define FLAG_HIDE_SILPH_CO_10F_ULTRA_BALL                        (FRLG_FLAGS_START+0x137)
#undef  FLAG_HIDE_SILPH_CO_11F_ZINC
#define FLAG_HIDE_SILPH_CO_11F_ZINC                              (FRLG_FLAGS_START+0x138)
#undef  FLAG_HIDE_SILPH_CO_3F_HYPER_POTION
#define FLAG_HIDE_SILPH_CO_3F_HYPER_POTION                       (FRLG_FLAGS_START+0x139)
#undef  FLAG_HIDE_SILPH_CO_4F_ESCAPE_ROPE
#define FLAG_HIDE_SILPH_CO_4F_ESCAPE_ROPE                        (FRLG_FLAGS_START+0x13A)
#undef  FLAG_HIDE_SILPH_CO_4F_FULL_HEAL
#define FLAG_HIDE_SILPH_CO_4F_FULL_HEAL                          (FRLG_FLAGS_START+0x13B)
#undef  FLAG_HIDE_SILPH_CO_4F_MAX_REVIVE
#define FLAG_HIDE_SILPH_CO_4F_MAX_REVIVE                         (FRLG_FLAGS_START+0x13C)
#undef  FLAG_HIDE_SILPH_CO_4F_TM41
#define FLAG_HIDE_SILPH_CO_4F_TM41                               (FRLG_FLAGS_START+0x13D)
#undef  FLAG_HIDE_SILPH_CO_5F_CARD_KEY
#define FLAG_HIDE_SILPH_CO_5F_CARD_KEY                           (FRLG_FLAGS_START+0x13E)
#undef  FLAG_HIDE_SILPH_CO_5F_PROTEIN
#define FLAG_HIDE_SILPH_CO_5F_PROTEIN                            (FRLG_FLAGS_START+0x13F)
#undef  FLAG_HIDE_SILPH_CO_5F_TM01
#define FLAG_HIDE_SILPH_CO_5F_TM01                               (FRLG_FLAGS_START+0x140)
#undef  FLAG_HIDE_SILPH_CO_6F_HP_UP
#define FLAG_HIDE_SILPH_CO_6F_HP_UP                              (FRLG_FLAGS_START+0x141)
#undef  FLAG_HIDE_SILPH_CO_6F_X_SPECIAL
#define FLAG_HIDE_SILPH_CO_6F_X_SPECIAL                          (FRLG_FLAGS_START+0x142)
#undef  FLAG_HIDE_SILPH_CO_7F_CALCIUM
#define FLAG_HIDE_SILPH_CO_7F_CALCIUM                            (FRLG_FLAGS_START+0x143)
#undef  FLAG_HIDE_SILPH_CO_7F_TM08
#define FLAG_HIDE_SILPH_CO_7F_TM08                               (FRLG_FLAGS_START+0x144)
#undef  FLAG_HIDE_SILPH_CO_8F_IRON
#define FLAG_HIDE_SILPH_CO_8F_IRON                               (FRLG_FLAGS_START+0x145)
#undef  FLAG_HIDE_SILPH_RIVAL
#define FLAG_HIDE_SILPH_RIVAL                                    (FRLG_FLAGS_START+0x146)
#undef  FLAG_HIDE_SILPH_ROCKETS
#define FLAG_HIDE_SILPH_ROCKETS                                  (FRLG_FLAGS_START+0x147)
#undef  FLAG_HIDE_SILPH_SCOPE
#define FLAG_HIDE_SILPH_SCOPE                                    (FRLG_FLAGS_START+0x148)
#undef  FLAG_HIDE_SIX_ISLAND_OUTCAST_ISLAND_PP_UP
#define FLAG_HIDE_SIX_ISLAND_OUTCAST_ISLAND_PP_UP                (FRLG_FLAGS_START+0x149)
#undef  FLAG_HIDE_SIX_ISLAND_POKECENTER_RIVAL
#define FLAG_HIDE_SIX_ISLAND_POKECENTER_RIVAL                    (FRLG_FLAGS_START+0x14A)
#undef  FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_FULL_RESTORE
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_FULL_RESTORE            (FRLG_FLAGS_START+0x14B)
#undef  FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_HP_UP
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_HP_UP                   (FRLG_FLAGS_START+0x14C)
#undef  FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_SUN_STONE
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_SUN_STONE               (FRLG_FLAGS_START+0x14D)
#undef  FLAG_HIDE_SIX_ISLAND_WATER_PATH_DRAGON_SCALE
#define FLAG_HIDE_SIX_ISLAND_WATER_PATH_DRAGON_SCALE             (FRLG_FLAGS_START+0x14E)
#undef  FLAG_HIDE_SIX_ISLAND_WATER_PATH_ELIXIR
#define FLAG_HIDE_SIX_ISLAND_WATER_PATH_ELIXIR                   (FRLG_FLAGS_START+0x14F)
#undef  FLAG_HIDE_SQUIRTLE_BALL
#define FLAG_HIDE_SQUIRTLE_BALL                                  (FRLG_FLAGS_START+0x150)
#undef  FLAG_HIDE_SSANNE_1F_ROOM2_TM31
#define FLAG_HIDE_SSANNE_1F_ROOM2_TM31                           (FRLG_FLAGS_START+0x151)
#undef  FLAG_HIDE_SSANNE_2F_ROOM2_STARDUST
#define FLAG_HIDE_SSANNE_2F_ROOM2_STARDUST                       (FRLG_FLAGS_START+0x152)
#undef  FLAG_HIDE_SSANNE_2F_ROOM4_X_ATTACK
#define FLAG_HIDE_SSANNE_2F_ROOM4_X_ATTACK                       (FRLG_FLAGS_START+0x153)
#undef  FLAG_HIDE_SSANNE_B1F_ROOM2_TM44
#define FLAG_HIDE_SSANNE_B1F_ROOM2_TM44                          (FRLG_FLAGS_START+0x154)
#undef  FLAG_HIDE_SSANNE_B1F_ROOM3_ETHER
#define FLAG_HIDE_SSANNE_B1F_ROOM3_ETHER                         (FRLG_FLAGS_START+0x155)
#undef  FLAG_HIDE_SSANNE_B1F_ROOM5_SUPER_POTION
#define FLAG_HIDE_SSANNE_B1F_ROOM5_SUPER_POTION                  (FRLG_FLAGS_START+0x156)
#undef  FLAG_HIDE_SSANNE_KITCHEN_GREAT_BALL
#define FLAG_HIDE_SSANNE_KITCHEN_GREAT_BALL                      (FRLG_FLAGS_START+0x157)
#undef  FLAG_HIDE_SS_ANNE
#define FLAG_HIDE_SS_ANNE                                        (FRLG_FLAGS_START+0x158)
#undef  FLAG_HIDE_SS_ANNE_RIVAL
#define FLAG_HIDE_SS_ANNE_RIVAL                                  (FRLG_FLAGS_START+0x159)
#undef  FLAG_HIDE_THREE_ISLAND_ANTIBIKERS
#define FLAG_HIDE_THREE_ISLAND_ANTIBIKERS                        (FRLG_FLAGS_START+0x15A)
#undef  FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_FULL_HEAL
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_FULL_HEAL            (FRLG_FLAGS_START+0x15B)
#undef  FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ELIXIR
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ELIXIR           (FRLG_FLAGS_START+0x15C)
#undef  FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ETHER
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ETHER            (FRLG_FLAGS_START+0x15D)
#undef  FLAG_HIDE_THREE_ISLAND_BIKERS
#define FLAG_HIDE_THREE_ISLAND_BIKERS                            (FRLG_FLAGS_START+0x15E)
#undef  FLAG_HIDE_THREE_ISLAND_LONE_BIKER
#define FLAG_HIDE_THREE_ISLAND_LONE_BIKER                        (FRLG_FLAGS_START+0x15F)
#undef  FLAG_HIDE_THREE_ISLAND_ZINC
#define FLAG_HIDE_THREE_ISLAND_ZINC                              (FRLG_FLAGS_START+0x160)
#undef  FLAG_HIDE_TOWER_FUJI
#define FLAG_HIDE_TOWER_FUJI                                     (FRLG_FLAGS_START+0x161)
#undef  FLAG_HIDE_TOWER_RIVAL
#define FLAG_HIDE_TOWER_RIVAL                                    (FRLG_FLAGS_START+0x162)
#undef  FLAG_HIDE_TOWER_ROCKET_1
#define FLAG_HIDE_TOWER_ROCKET_1                                 (FRLG_FLAGS_START+0x163)
#undef  FLAG_HIDE_TOWER_ROCKET_2
#define FLAG_HIDE_TOWER_ROCKET_2                                 (FRLG_FLAGS_START+0x164)
#undef  FLAG_HIDE_TOWER_ROCKET_3
#define FLAG_HIDE_TOWER_ROCKET_3                                 (FRLG_FLAGS_START+0x165)
#undef  FLAG_HIDE_TOWN_MAP
#define FLAG_HIDE_TOWN_MAP                                       (FRLG_FLAGS_START+0x166)
#undef  FLAG_HIDE_TWO_ISLAND_BEAUTY
#define FLAG_HIDE_TWO_ISLAND_BEAUTY                              (FRLG_FLAGS_START+0x167)
#undef  FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER
#define FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER                   (FRLG_FLAGS_START+0x168)
#undef  FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE
#define FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE                (FRLG_FLAGS_START+0x169)
#undef  FLAG_HIDE_TWO_ISLAND_REVIVE
#define FLAG_HIDE_TWO_ISLAND_REVIVE                              (FRLG_FLAGS_START+0x16A)
#undef  FLAG_HIDE_TWO_ISLAND_SUPER_NERD
#define FLAG_HIDE_TWO_ISLAND_SUPER_NERD                          (FRLG_FLAGS_START+0x16B)
#undef  FLAG_HIDE_TWO_ISLAND_WOMAN
#define FLAG_HIDE_TWO_ISLAND_WOMAN                               (FRLG_FLAGS_START+0x16C)
#undef  FLAG_HIDE_VERMILION_CITY_OAKS_AIDE
#define FLAG_HIDE_VERMILION_CITY_OAKS_AIDE                       (FRLG_FLAGS_START+0x16D)
#undef  FLAG_HIDE_VICTORY_ROAD_1F_RARE_CANDY
#define FLAG_HIDE_VICTORY_ROAD_1F_RARE_CANDY                     (FRLG_FLAGS_START+0x16E)
#undef  FLAG_HIDE_VICTORY_ROAD_1F_TM02
#define FLAG_HIDE_VICTORY_ROAD_1F_TM02                           (FRLG_FLAGS_START+0x16F)
#undef  FLAG_HIDE_VICTORY_ROAD_2F_BOULDER
#define FLAG_HIDE_VICTORY_ROAD_2F_BOULDER                        (FRLG_FLAGS_START+0x170)
#undef  FLAG_HIDE_VICTORY_ROAD_2F_FULL_HEAL
#define FLAG_HIDE_VICTORY_ROAD_2F_FULL_HEAL                      (FRLG_FLAGS_START+0x171)
#undef  FLAG_HIDE_VICTORY_ROAD_2F_GUARD_SPEC
#define FLAG_HIDE_VICTORY_ROAD_2F_GUARD_SPEC                     (FRLG_FLAGS_START+0x172)
#undef  FLAG_HIDE_VICTORY_ROAD_2F_TM07
#define FLAG_HIDE_VICTORY_ROAD_2F_TM07                           (FRLG_FLAGS_START+0x173)
#undef  FLAG_HIDE_VICTORY_ROAD_2F_TM37
#define FLAG_HIDE_VICTORY_ROAD_2F_TM37                           (FRLG_FLAGS_START+0x174)
#undef  FLAG_HIDE_VICTORY_ROAD_3F_BOULDER
#define FLAG_HIDE_VICTORY_ROAD_3F_BOULDER                        (FRLG_FLAGS_START+0x175)
#undef  FLAG_HIDE_VICTORY_ROAD_3F_MAX_REVIVE
#define FLAG_HIDE_VICTORY_ROAD_3F_MAX_REVIVE                     (FRLG_FLAGS_START+0x176)
#undef  FLAG_HIDE_VICTORY_ROAD_3F_TM50
#define FLAG_HIDE_VICTORY_ROAD_3F_TM50                           (FRLG_FLAGS_START+0x177)
#undef  FLAG_HIDE_VIRIDIAN_CITY_POTION
#define FLAG_HIDE_VIRIDIAN_CITY_POTION                           (FRLG_FLAGS_START+0x178)
#undef  FLAG_HIDE_VIRIDIAN_FOREST_ANTIDOTE
#define FLAG_HIDE_VIRIDIAN_FOREST_ANTIDOTE                       (FRLG_FLAGS_START+0x179)
#undef  FLAG_HIDE_VIRIDIAN_FOREST_POKE_BALL
#define FLAG_HIDE_VIRIDIAN_FOREST_POKE_BALL                      (FRLG_FLAGS_START+0x17A)
#undef  FLAG_HIDE_VIRIDIAN_FOREST_POTION
#define FLAG_HIDE_VIRIDIAN_FOREST_POTION                         (FRLG_FLAGS_START+0x17B)
#undef  FLAG_HIDE_VIRIDIAN_FOREST_POTION_2
#define FLAG_HIDE_VIRIDIAN_FOREST_POTION_2                       (FRLG_FLAGS_START+0x17C)
#undef  FLAG_HIDE_VIRIDIAN_GIOVANNI
#define FLAG_HIDE_VIRIDIAN_GIOVANNI                              (FRLG_FLAGS_START+0x17D)
#undef  FLAG_HO_OH_FLEW_AWAY
#define FLAG_HO_OH_FLEW_AWAY                                     (FRLG_FLAGS_START+0x17E)
#undef  FLAG_LEARNED_YES_NAH_CHANSEY
#define FLAG_LEARNED_YES_NAH_CHANSEY                             (FRLG_FLAGS_START+0x17F)
#undef  FLAG_LUGIA_FLEW_AWAY
#define FLAG_LUGIA_FLEW_AWAY                                     (FRLG_FLAGS_START+0x180)
#undef  FLAG_NO_ROOM_FOR_JOYFUL_GAME_CORNER_MOON_STONE
#define FLAG_NO_ROOM_FOR_JOYFUL_GAME_CORNER_MOON_STONE           (FRLG_FLAGS_START+0x181)
#undef  FLAG_NO_ROOM_FOR_TM42_AT_MEMORIAL_PILLAR
#define FLAG_NO_ROOM_FOR_TM42_AT_MEMORIAL_PILLAR                 (FRLG_FLAGS_START+0x182)
#undef  FLAG_NO_ROOM_FOR_TOGEPI_EGG
#define FLAG_NO_ROOM_FOR_TOGEPI_EGG                              (FRLG_FLAGS_START+0x183)
#undef  FLAG_OAK_SAW_DEX_COMPLETION
#define FLAG_OAK_SAW_DEX_COMPLETION                              (FRLG_FLAGS_START+0x184)
#undef  FLAG_OAK_SKIP_22_RIVAL_CHECK
#define FLAG_OAK_SKIP_22_RIVAL_CHECK                             (FRLG_FLAGS_START+0x185)
#undef  FLAG_OPENED_ROCKET_HIDEOUT
#define FLAG_OPENED_ROCKET_HIDEOUT                               (FRLG_FLAGS_START+0x186)
#undef  FLAG_PALLET_LADY_NOT_BLOCKING_SIGN
#define FLAG_PALLET_LADY_NOT_BLOCKING_SIGN                       (FRLG_FLAGS_START+0x187)
#undef  FLAG_POKEMON_MANSION_SWITCH_STATE
#define FLAG_POKEMON_MANSION_SWITCH_STATE                        (FRLG_FLAGS_START+0x188)
#undef  FLAG_RECOVERED_SAPPHIRE
#define FLAG_RECOVERED_SAPPHIRE                                  (FRLG_FLAGS_START+0x189)
#undef  FLAG_RESCUED_LOSTELLE
#define FLAG_RESCUED_LOSTELLE                                    (FRLG_FLAGS_START+0x18A)
#undef  FLAG_RESCUED_MR_FUJI
#define FLAG_RESCUED_MR_FUJI                                     (FRLG_FLAGS_START+0x18B)
#undef  FLAG_REVIVED_AMBER
#define FLAG_REVIVED_AMBER                                       (FRLG_FLAGS_START+0x18C)
#undef  FLAG_REVIVED_DOME
#define FLAG_REVIVED_DOME                                        (FRLG_FLAGS_START+0x18D)
#undef  FLAG_REVIVED_HELIX
#define FLAG_REVIVED_HELIX                                       (FRLG_FLAGS_START+0x18E)
#undef  FLAG_SEVII_DETOUR_FINISHED
#define FLAG_SEVII_DETOUR_FINISHED                               (FRLG_FLAGS_START+0x18F)
#undef  FLAG_SILPH_10F_DOOR
#define FLAG_SILPH_10F_DOOR                                      (FRLG_FLAGS_START+0x190)
#undef  FLAG_SILPH_11F_DOOR
#define FLAG_SILPH_11F_DOOR                                      (FRLG_FLAGS_START+0x191)
#undef  FLAG_SILPH_2F_DOOR_1
#define FLAG_SILPH_2F_DOOR_1                                     (FRLG_FLAGS_START+0x192)
#undef  FLAG_SILPH_2F_DOOR_2
#define FLAG_SILPH_2F_DOOR_2                                     (FRLG_FLAGS_START+0x193)
#undef  FLAG_SILPH_3F_DOOR_1
#define FLAG_SILPH_3F_DOOR_1                                     (FRLG_FLAGS_START+0x194)
#undef  FLAG_SILPH_3F_DOOR_2
#define FLAG_SILPH_3F_DOOR_2                                     (FRLG_FLAGS_START+0x195)
#undef  FLAG_SILPH_4F_DOOR_1
#define FLAG_SILPH_4F_DOOR_1                                     (FRLG_FLAGS_START+0x196)
#undef  FLAG_SILPH_4F_DOOR_2
#define FLAG_SILPH_4F_DOOR_2                                     (FRLG_FLAGS_START+0x197)
#undef  FLAG_SILPH_5F_DOOR_1
#define FLAG_SILPH_5F_DOOR_1                                     (FRLG_FLAGS_START+0x198)
#undef  FLAG_SILPH_5F_DOOR_2
#define FLAG_SILPH_5F_DOOR_2                                     (FRLG_FLAGS_START+0x199)
#undef  FLAG_SILPH_5F_DOOR_3
#define FLAG_SILPH_5F_DOOR_3                                     (FRLG_FLAGS_START+0x19A)
#undef  FLAG_SILPH_6F_DOOR
#define FLAG_SILPH_6F_DOOR                                       (FRLG_FLAGS_START+0x19B)
#undef  FLAG_SILPH_7F_DOOR_1
#define FLAG_SILPH_7F_DOOR_1                                     (FRLG_FLAGS_START+0x19C)
#undef  FLAG_SILPH_7F_DOOR_2
#define FLAG_SILPH_7F_DOOR_2                                     (FRLG_FLAGS_START+0x19D)
#undef  FLAG_SILPH_7F_DOOR_3
#define FLAG_SILPH_7F_DOOR_3                                     (FRLG_FLAGS_START+0x19E)
#undef  FLAG_SILPH_8F_DOOR
#define FLAG_SILPH_8F_DOOR                                       (FRLG_FLAGS_START+0x19F)
#undef  FLAG_SILPH_9F_DOOR_1
#define FLAG_SILPH_9F_DOOR_1                                     (FRLG_FLAGS_START+0x1A0)
#undef  FLAG_SILPH_9F_DOOR_2
#define FLAG_SILPH_9F_DOOR_2                                     (FRLG_FLAGS_START+0x1A1)
#undef  FLAG_SILPH_9F_DOOR_3
#define FLAG_SILPH_9F_DOOR_3                                     (FRLG_FLAGS_START+0x1A2)
#undef  FLAG_SILPH_9F_DOOR_4
#define FLAG_SILPH_9F_DOOR_4                                     (FRLG_FLAGS_START+0x1A3)
#undef  FLAG_STOPPED_SEAFOAM_B3F_CURRENT
#define FLAG_STOPPED_SEAFOAM_B3F_CURRENT                         (FRLG_FLAGS_START+0x1A4)
#undef  FLAG_STOPPED_SEAFOAM_B4F_CURRENT
#define FLAG_STOPPED_SEAFOAM_B4F_CURRENT                         (FRLG_FLAGS_START+0x1A5)
#undef  FLAG_TALKED_TO_LORELEI_AFTER_WAREHOUSE
#define FLAG_TALKED_TO_LORELEI_AFTER_WAREHOUSE                   (FRLG_FLAGS_START+0x1A6)
#undef  FLAG_TALKED_TO_OAKS_AIDE_IN_VERMILION
#define FLAG_TALKED_TO_OAKS_AIDE_IN_VERMILION                    (FRLG_FLAGS_START+0x1A7)
#undef  FLAG_TALKED_TO_TEA_LADY_AFTER_HOF
#define FLAG_TALKED_TO_TEA_LADY_AFTER_HOF                        (FRLG_FLAGS_START+0x1A8)
#undef  FLAG_TWO_ISLAND_SHOP_EXPANDED_1
#define FLAG_TWO_ISLAND_SHOP_EXPANDED_1                          (FRLG_FLAGS_START+0x1A9)
#undef  FLAG_TWO_ISLAND_SHOP_EXPANDED_2
#define FLAG_TWO_ISLAND_SHOP_EXPANDED_2                          (FRLG_FLAGS_START+0x1AA)
#undef  FLAG_TWO_ISLAND_SHOP_EXPANDED_3
#define FLAG_TWO_ISLAND_SHOP_EXPANDED_3                          (FRLG_FLAGS_START+0x1AB)
#undef  FLAG_TWO_ISLAND_SHOP_INTRODUCED
#define FLAG_TWO_ISLAND_SHOP_INTRODUCED                          (FRLG_FLAGS_START+0x1AC)
#undef  FLAG_UNLOCKED_ROCKET_WAREHOUSE
#define FLAG_UNLOCKED_ROCKET_WAREHOUSE                           (FRLG_FLAGS_START+0x1AD)
#undef  FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE
#define FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE                     (FRLG_FLAGS_START+0x1AE)
#undef  FLAG_VISITED_OAKS_LAB
#define FLAG_VISITED_OAKS_LAB                                    (FRLG_FLAGS_START+0x1AF)
#undef  FLAG_VISITED_TWO_ISLAND
#define FLAG_VISITED_TWO_ISLAND                                  (FRLG_FLAGS_START+0x1B0)
#undef  FLAG_WOKE_UP_ROUTE_12_SNORLAX
#define FLAG_WOKE_UP_ROUTE_12_SNORLAX                            (FRLG_FLAGS_START+0x1B1)
#undef  FLAG_RIVAL_NAMED_BY_MOM
#define FLAG_RIVAL_NAMED_BY_MOM                                  (FRLG_FLAGS_START+0x1B2)



// Kanto-Merge: FRLG-Verstecke. flags_hns.h weist ihnen samt und sonders
// FLAG_HIDDEN_ITEMS_START zu (Offset 0) - alle 191 Verstecke haengen dort
// an derselben Fahne. Hier bekommt jedes seine eigene.

#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS                  (FRLG_FLAGS_START+0x1B3)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_10
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_10               (FRLG_FLAGS_START+0x1B4)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_11
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_11               (FRLG_FLAGS_START+0x1B5)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_12
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_12               (FRLG_FLAGS_START+0x1B6)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_2
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_2                (FRLG_FLAGS_START+0x1B7)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_3
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_3                (FRLG_FLAGS_START+0x1B8)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_4
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_4                (FRLG_FLAGS_START+0x1B9)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_5
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_5                (FRLG_FLAGS_START+0x1BA)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_6
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_6                (FRLG_FLAGS_START+0x1BB)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_7
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_7                (FRLG_FLAGS_START+0x1BC)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_8
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_8                (FRLG_FLAGS_START+0x1BD)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_9
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_9                (FRLG_FLAGS_START+0x1BE)
#undef  FLAG_HIDDEN_ITEM_CELADON_CITY_PP_UP
#define FLAG_HIDDEN_ITEM_CELADON_CITY_PP_UP                              (FRLG_FLAGS_START+0x1BF)
#undef  FLAG_HIDDEN_ITEM_CERULEAN_CAVE_1F_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_CERULEAN_CAVE_1F_ULTRA_BALL                     (FRLG_FLAGS_START+0x1C0)
#undef  FLAG_HIDDEN_ITEM_CERULEAN_CITY_RARE_CANDY
#define FLAG_HIDDEN_ITEM_CERULEAN_CITY_RARE_CANDY                        (FRLG_FLAGS_START+0x1C1)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BIG_PEARL
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BIG_PEARL           (FRLG_FLAGS_START+0x1C2)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BLUK_BERRY
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BLUK_BERRY          (FRLG_FLAGS_START+0x1C3)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_RAZZ_BERRY
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_RAZZ_BERRY          (FRLG_FLAGS_START+0x1C4)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_SITRUS_BERRY
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_SITRUS_BERRY        (FRLG_FLAGS_START+0x1C5)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_NEST_BALL
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_NEST_BALL           (FRLG_FLAGS_START+0x1C6)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST            (FRLG_FLAGS_START+0x1C7)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST_2
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST_2          (FRLG_FLAGS_START+0x1C8)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STAR_PIECE
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STAR_PIECE          (FRLG_FLAGS_START+0x1C9)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NEST_BALL
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NEST_BALL          (FRLG_FLAGS_START+0x1CA)
#undef  FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NET_BALL
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NET_BALL           (FRLG_FLAGS_START+0x1CB)
#undef  FLAG_HIDDEN_ITEM_FOUR_ISLAND_PEARL
#define FLAG_HIDDEN_ITEM_FOUR_ISLAND_PEARL                               (FRLG_FLAGS_START+0x1CC)
#undef  FLAG_HIDDEN_ITEM_FOUR_ISLAND_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_FOUR_ISLAND_ULTRA_BALL                          (FRLG_FLAGS_START+0x1CD)
#undef  FLAG_HIDDEN_ITEM_FUCHSIA_CITY_MAX_REVIVE
#define FLAG_HIDDEN_ITEM_FUCHSIA_CITY_MAX_REVIVE                         (FRLG_FLAGS_START+0x1CE)
#undef  FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_FIRE_STONE
#define FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_FIRE_STONE                    (FRLG_FLAGS_START+0x1CF)
#undef  FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_ULTRA_BALL                    (FRLG_FLAGS_START+0x1D0)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM                        (FRLG_FLAGS_START+0x1D1)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_2
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_2                      (FRLG_FLAGS_START+0x1D2)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_3
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_3                      (FRLG_FLAGS_START+0x1D3)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM                       (FRLG_FLAGS_START+0x1D4)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_2
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_2                     (FRLG_FLAGS_START+0x1D5)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_3
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_3                     (FRLG_FLAGS_START+0x1D6)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B2F_ETHER
#define FLAG_HIDDEN_ITEM_MT_MOON_B2F_ETHER                               (FRLG_FLAGS_START+0x1D7)
#undef  FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE
#define FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE                          (FRLG_FLAGS_START+0x1D8)
#undef  FLAG_HIDDEN_ITEM_NAVEL_ROCK_SUMMIT_SACRED_ASH
#define FLAG_HIDDEN_ITEM_NAVEL_ROCK_SUMMIT_SACRED_ASH                    (FRLG_FLAGS_START+0x1D9)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_BIG_PEARL
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_BIG_PEARL             (FRLG_FLAGS_START+0x1DA)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL                 (FRLG_FLAGS_START+0x1DB)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL_2
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL_2               (FRLG_FLAGS_START+0x1DC)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST              (FRLG_FLAGS_START+0x1DD)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST_2
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST_2            (FRLG_FLAGS_START+0x1DE)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STAR_PIECE
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STAR_PIECE            (FRLG_FLAGS_START+0x1DF)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL            (FRLG_FLAGS_START+0x1E0)
#undef  FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL_2
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL_2          (FRLG_FLAGS_START+0x1E1)
#undef  FLAG_HIDDEN_ITEM_PEWTER_CITY_POKE_BALL
#define FLAG_HIDDEN_ITEM_PEWTER_CITY_POKE_BALL                           (FRLG_FLAGS_START+0x1E2)
#undef  FLAG_HIDDEN_ITEM_POKEMON_MANSION_1F_MOON_STONE
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_1F_MOON_STONE                   (FRLG_FLAGS_START+0x1E3)
#undef  FLAG_HIDDEN_ITEM_POKEMON_MANSION_3F_RARE_CANDY
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_3F_RARE_CANDY                   (FRLG_FLAGS_START+0x1E4)
#undef  FLAG_HIDDEN_ITEM_POKEMON_MANSION_B1F_ELIXIR
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_B1F_ELIXIR                      (FRLG_FLAGS_START+0x1E5)
#undef  FLAG_HIDDEN_ITEM_POKEMON_TOWER_5F_BIG_MUSHROOM
#define FLAG_HIDDEN_ITEM_POKEMON_TOWER_5F_BIG_MUSHROOM                   (FRLG_FLAGS_START+0x1E6)
#undef  FLAG_HIDDEN_ITEM_POKEMON_TOWER_7F_SOOTHE_BELL
#define FLAG_HIDDEN_ITEM_POKEMON_TOWER_7F_SOOTHE_BELL                    (FRLG_FLAGS_START+0x1E7)
#undef  FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR
#define FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR                          (FRLG_FLAGS_START+0x1E8)
#undef  FLAG_HIDDEN_ITEM_POWER_PLANT_THUNDER_STONE
#define FLAG_HIDDEN_ITEM_POWER_PLANT_THUNDER_STONE                       (FRLG_FLAGS_START+0x1E9)
#undef  FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP                        (FRLG_FLAGS_START+0x1EA)
#undef  FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B3F_NUGGET
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B3F_NUGGET                       (FRLG_FLAGS_START+0x1EB)
#undef  FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NEST_BALL
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NEST_BALL                    (FRLG_FLAGS_START+0x1EC)
#undef  FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NET_BALL
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NET_BALL                     (FRLG_FLAGS_START+0x1ED)
#undef  FLAG_HIDDEN_ITEM_ROUTE10_CHERI_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE10_CHERI_BERRY                             (FRLG_FLAGS_START+0x1EE)
#undef  FLAG_HIDDEN_ITEM_ROUTE10_MAX_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE10_MAX_ETHER                               (FRLG_FLAGS_START+0x1EF)
#undef  FLAG_HIDDEN_ITEM_ROUTE10_NANAB_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE10_NANAB_BERRY                             (FRLG_FLAGS_START+0x1F0)
#undef  FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY                            (FRLG_FLAGS_START+0x1F1)
#undef  FLAG_HIDDEN_ITEM_ROUTE10_SUPER_POTION
#define FLAG_HIDDEN_ITEM_ROUTE10_SUPER_POTION                            (FRLG_FLAGS_START+0x1F2)
#undef  FLAG_HIDDEN_ITEM_ROUTE11_ESCAPE_ROPE
#define FLAG_HIDDEN_ITEM_ROUTE11_ESCAPE_ROPE                             (FRLG_FLAGS_START+0x1F3)
#undef  FLAG_HIDDEN_ITEM_ROUTE12_HYPER_POTION
#define FLAG_HIDDEN_ITEM_ROUTE12_HYPER_POTION                            (FRLG_FLAGS_START+0x1F4)
#undef  FLAG_HIDDEN_ITEM_ROUTE12_LEFTOVERS
#define FLAG_HIDDEN_ITEM_ROUTE12_LEFTOVERS                               (FRLG_FLAGS_START+0x1F5)
#undef  FLAG_HIDDEN_ITEM_ROUTE12_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE12_RARE_CANDY                              (FRLG_FLAGS_START+0x1F6)
#undef  FLAG_HIDDEN_ITEM_ROUTE13_PP_UP
#define FLAG_HIDDEN_ITEM_ROUTE13_PP_UP                                   (FRLG_FLAGS_START+0x1F7)
#undef  FLAG_HIDDEN_ITEM_ROUTE14_PINAP_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE14_PINAP_BERRY                             (FRLG_FLAGS_START+0x1F8)
#undef  FLAG_HIDDEN_ITEM_ROUTE14_ZINC
#define FLAG_HIDDEN_ITEM_ROUTE14_ZINC                                    (FRLG_FLAGS_START+0x1F9)
#undef  FLAG_HIDDEN_ITEM_ROUTE16_LEFTOVERS
#define FLAG_HIDDEN_ITEM_ROUTE16_LEFTOVERS                               (FRLG_FLAGS_START+0x1FA)
#undef  FLAG_HIDDEN_ITEM_ROUTE17_FULL_RESTORE
#define FLAG_HIDDEN_ITEM_ROUTE17_FULL_RESTORE                            (FRLG_FLAGS_START+0x1FB)
#undef  FLAG_HIDDEN_ITEM_ROUTE17_MAX_ELIXIR
#define FLAG_HIDDEN_ITEM_ROUTE17_MAX_ELIXIR                              (FRLG_FLAGS_START+0x1FC)
#undef  FLAG_HIDDEN_ITEM_ROUTE17_MAX_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE17_MAX_REVIVE                              (FRLG_FLAGS_START+0x1FD)
#undef  FLAG_HIDDEN_ITEM_ROUTE17_PP_UP
#define FLAG_HIDDEN_ITEM_ROUTE17_PP_UP                                   (FRLG_FLAGS_START+0x1FE)
#undef  FLAG_HIDDEN_ITEM_ROUTE17_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE17_RARE_CANDY                              (FRLG_FLAGS_START+0x1FF)
#undef  FLAG_HIDDEN_ITEM_ROUTE20_STARDUST
#define FLAG_HIDDEN_ITEM_ROUTE20_STARDUST                                (FRLG_FLAGS_START+0x200)
#undef  FLAG_HIDDEN_ITEM_ROUTE21_NORTH_PEARL
#define FLAG_HIDDEN_ITEM_ROUTE21_NORTH_PEARL                             (FRLG_FLAGS_START+0x201)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_ASPEAR_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE23_ASPEAR_BERRY                            (FRLG_FLAGS_START+0x202)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_FULL_RESTORE
#define FLAG_HIDDEN_ITEM_ROUTE23_FULL_RESTORE                            (FRLG_FLAGS_START+0x203)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_LEPPA_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE23_LEPPA_BERRY                             (FRLG_FLAGS_START+0x204)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_LUM_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE23_LUM_BERRY                               (FRLG_FLAGS_START+0x205)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_MAX_ELIXIR
#define FLAG_HIDDEN_ITEM_ROUTE23_MAX_ELIXIR                              (FRLG_FLAGS_START+0x206)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_MAX_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE23_MAX_ETHER                               (FRLG_FLAGS_START+0x207)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_SITRUS_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE23_SITRUS_BERRY                            (FRLG_FLAGS_START+0x208)
#undef  FLAG_HIDDEN_ITEM_ROUTE23_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_ROUTE23_ULTRA_BALL                              (FRLG_FLAGS_START+0x209)
#undef  FLAG_HIDDEN_ITEM_ROUTE24_PECHA_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE24_PECHA_BERRY                             (FRLG_FLAGS_START+0x20A)
#undef  FLAG_HIDDEN_ITEM_ROUTE25_BLUK_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE25_BLUK_BERRY                              (FRLG_FLAGS_START+0x20B)
#undef  FLAG_HIDDEN_ITEM_ROUTE25_ELIXIR
#define FLAG_HIDDEN_ITEM_ROUTE25_ELIXIR                                  (FRLG_FLAGS_START+0x20C)
#undef  FLAG_HIDDEN_ITEM_ROUTE25_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE25_ETHER                                   (FRLG_FLAGS_START+0x20D)
#undef  FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY                              (FRLG_FLAGS_START+0x20E)
#undef  FLAG_HIDDEN_ITEM_ROUTE3_ORAN_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE3_ORAN_BERRY                               (FRLG_FLAGS_START+0x20F)
#undef  FLAG_HIDDEN_ITEM_ROUTE4_GREAT_BALL
#define FLAG_HIDDEN_ITEM_ROUTE4_GREAT_BALL                               (FRLG_FLAGS_START+0x210)
#undef  FLAG_HIDDEN_ITEM_ROUTE4_PERSIM_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE4_PERSIM_BERRY                             (FRLG_FLAGS_START+0x211)
#undef  FLAG_HIDDEN_ITEM_ROUTE4_RAZZ_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE4_RAZZ_BERRY                               (FRLG_FLAGS_START+0x212)
#undef  FLAG_HIDDEN_ITEM_ROUTE6_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE6_RARE_CANDY                               (FRLG_FLAGS_START+0x213)
#undef  FLAG_HIDDEN_ITEM_ROUTE6_SITRUS_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE6_SITRUS_BERRY                             (FRLG_FLAGS_START+0x214)
#undef  FLAG_HIDDEN_ITEM_ROUTE7_WEPEAR_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE7_WEPEAR_BERRY                             (FRLG_FLAGS_START+0x215)
#undef  FLAG_HIDDEN_ITEM_ROUTE8_LEPPA_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE8_LEPPA_BERRY                              (FRLG_FLAGS_START+0x216)
#undef  FLAG_HIDDEN_ITEM_ROUTE8_LUM_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE8_LUM_BERRY                                (FRLG_FLAGS_START+0x217)
#undef  FLAG_HIDDEN_ITEM_ROUTE8_RAWST_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE8_RAWST_BERRY                              (FRLG_FLAGS_START+0x218)
#undef  FLAG_HIDDEN_ITEM_ROUTE9_CHESTO_BERRY
#define FLAG_HIDDEN_ITEM_ROUTE9_CHESTO_BERRY                             (FRLG_FLAGS_START+0x219)
#undef  FLAG_HIDDEN_ITEM_ROUTE9_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE9_ETHER                                    (FRLG_FLAGS_START+0x21A)
#undef  FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY                               (FRLG_FLAGS_START+0x21B)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_CENTER_LEAF_STONE
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_CENTER_LEAF_STONE                   (FRLG_FLAGS_START+0x21C)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_WEST_REVIVE
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_WEST_REVIVE                         (FRLG_FLAGS_START+0x21D)
#undef  FLAG_HIDDEN_ITEM_SAFFRON_CITY_COPYCATS_HOUSE_2F_NUGGET
#define FLAG_HIDDEN_ITEM_SAFFRON_CITY_COPYCATS_HOUSE_2F_NUGGET           (FRLG_FLAGS_START+0x21E)
#undef  FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B3F_NUGGET
#define FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B3F_NUGGET                      (FRLG_FLAGS_START+0x21F)
#undef  FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B4F_WATER_STONE
#define FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B4F_WATER_STONE                 (FRLG_FLAGS_START+0x220)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_CHERI_BERRY
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_CHERI_BERRY         (FRLG_FLAGS_START+0x221)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE_RAWST_BERRY
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE_RAWST_BERRY (FRLG_FLAGS_START+0x222)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE           (FRLG_FLAGS_START+0x223)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_2
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_2         (FRLG_FLAGS_START+0x224)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_3
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_3         (FRLG_FLAGS_START+0x225)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_4
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_4         (FRLG_FLAGS_START+0x226)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_BIG_PEARL
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_BIG_PEARL            (FRLG_FLAGS_START+0x227)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_NANAB_BERRY
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_NANAB_BERRY          (FRLG_FLAGS_START+0x228)
#undef  FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_PEARL
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_PEARL                (FRLG_FLAGS_START+0x229)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_10F_HP_UP
#define FLAG_HIDDEN_ITEM_SILPH_CO_10F_HP_UP                              (FRLG_FLAGS_START+0x22A)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_11F_REVIVE
#define FLAG_HIDDEN_ITEM_SILPH_CO_11F_REVIVE                             (FRLG_FLAGS_START+0x22B)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL                          (FRLG_FLAGS_START+0x22C)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN
#define FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN                             (FRLG_FLAGS_START+0x22D)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_4F_IRON
#define FLAG_HIDDEN_ITEM_SILPH_CO_4F_IRON                                (FRLG_FLAGS_START+0x22E)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR
#define FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR                              (FRLG_FLAGS_START+0x22F)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP
#define FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP                               (FRLG_FLAGS_START+0x230)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_6F_CARBOS
#define FLAG_HIDDEN_ITEM_SILPH_CO_6F_CARBOS                              (FRLG_FLAGS_START+0x231)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC
#define FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC                                (FRLG_FLAGS_START+0x232)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_8F_NUGGET
#define FLAG_HIDDEN_ITEM_SILPH_CO_8F_NUGGET                              (FRLG_FLAGS_START+0x233)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_9F_CALCIUM
#define FLAG_HIDDEN_ITEM_SILPH_CO_9F_CALCIUM                             (FRLG_FLAGS_START+0x234)
#undef  FLAG_HIDDEN_ITEM_SILPH_CO_9F_MAX_POTION
#define FLAG_HIDDEN_ITEM_SILPH_CO_9F_MAX_POTION                          (FRLG_FLAGS_START+0x235)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_GREEN_PATH_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_GREEN_PATH_ULTRA_BALL                (FRLG_FLAGS_START+0x236)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_LEPPA_BERRY
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_LEPPA_BERRY                          (FRLG_FLAGS_START+0x237)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_NET_BALL
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_NET_BALL              (FRLG_FLAGS_START+0x238)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_STAR_PIECE
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_STAR_PIECE            (FRLG_FLAGS_START+0x239)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ASPEAR_BERRY
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ASPEAR_BERRY              (FRLG_FLAGS_START+0x23A)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ORAN_BERRY
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ORAN_BERRY                (FRLG_FLAGS_START+0x23B)
#undef  FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_PINAP_BERRY
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_PINAP_BERRY               (FRLG_FLAGS_START+0x23C)
#undef  FLAG_HIDDEN_ITEM_SSANNE_B1F_CORRIDOR_HYPER_POTION
#define FLAG_HIDDEN_ITEM_SSANNE_B1F_CORRIDOR_HYPER_POTION                (FRLG_FLAGS_START+0x23D)
#undef  FLAG_HIDDEN_ITEM_SSANNE_EXTERIOR_LAVA_COOKIE
#define FLAG_HIDDEN_ITEM_SSANNE_EXTERIOR_LAVA_COOKIE                     (FRLG_FLAGS_START+0x23E)
#undef  FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHERI_BERRY
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHERI_BERRY                      (FRLG_FLAGS_START+0x23F)
#undef  FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHESTO_BERRY
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHESTO_BERRY                     (FRLG_FLAGS_START+0x240)
#undef  FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_PECHA_BERRY
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_PECHA_BERRY                      (FRLG_FLAGS_START+0x241)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ASPEAR_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ASPEAR_BERRY          (FRLG_FLAGS_START+0x242)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_BLUK_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_BLUK_BERRY            (FRLG_FLAGS_START+0x243)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHERI_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHERI_BERRY           (FRLG_FLAGS_START+0x244)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHESTO_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHESTO_BERRY          (FRLG_FLAGS_START+0x245)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_LUM_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_LUM_BERRY             (FRLG_FLAGS_START+0x246)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_NANAB_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_NANAB_BERRY           (FRLG_FLAGS_START+0x247)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ORAN_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ORAN_BERRY            (FRLG_FLAGS_START+0x248)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PECHA_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PECHA_BERRY           (FRLG_FLAGS_START+0x249)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PERSIM_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PERSIM_BERRY          (FRLG_FLAGS_START+0x24A)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PINAP_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PINAP_BERRY           (FRLG_FLAGS_START+0x24B)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAWST_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAWST_BERRY           (FRLG_FLAGS_START+0x24C)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAZZ_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAZZ_BERRY            (FRLG_FLAGS_START+0x24D)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_WEPEAR_BERRY
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_WEPEAR_BERRY          (FRLG_FLAGS_START+0x24E)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_MAX_REPEL
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_MAX_REPEL              (FRLG_FLAGS_START+0x24F)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_PEARL
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_PEARL                  (FRLG_FLAGS_START+0x250)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_STARDUST
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_STARDUST               (FRLG_FLAGS_START+0x251)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_DUNSPARCE_TUNNEL_NUGGET
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_DUNSPARCE_TUNNEL_NUGGET            (FRLG_FLAGS_START+0x252)
#undef  FLAG_HIDDEN_ITEM_THREE_ISLAND_PP_UP
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_PP_UP                              (FRLG_FLAGS_START+0x253)
#undef  FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_PP_MAX
#define FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_PP_MAX                    (FRLG_FLAGS_START+0x254)
#undef  FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_RARE_CANDY
#define FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_RARE_CANDY                (FRLG_FLAGS_START+0x255)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ANTIDOTE
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ANTIDOTE      (FRLG_FLAGS_START+0x256)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_AWAKENING
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_AWAKENING     (FRLG_FLAGS_START+0x257)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_BURN_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_BURN_HEAL     (FRLG_FLAGS_START+0x258)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ETHER
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ETHER         (FRLG_FLAGS_START+0x259)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ICE_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ICE_HEAL      (FRLG_FLAGS_START+0x25A)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_PARALYZE_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_PARALYZE_HEAL (FRLG_FLAGS_START+0x25B)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_POTION
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_POTION        (FRLG_FLAGS_START+0x25C)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ANTIDOTE
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ANTIDOTE    (FRLG_FLAGS_START+0x25D)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_AWAKENING
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_AWAKENING   (FRLG_FLAGS_START+0x25E)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_BURN_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_BURN_HEAL   (FRLG_FLAGS_START+0x25F)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ETHER
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ETHER       (FRLG_FLAGS_START+0x260)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ICE_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ICE_HEAL    (FRLG_FLAGS_START+0x261)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_PARALYZE_HEAL
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_PARALYZE_HEAL (FRLG_FLAGS_START+0x262)
#undef  FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_POTION
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_POTION      (FRLG_FLAGS_START+0x263)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x07
#define FLAG_HIDDEN_ITEM_UNUSED_0x07                                     (FRLG_FLAGS_START+0x264)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x10
#define FLAG_HIDDEN_ITEM_UNUSED_0x10                                     (FRLG_FLAGS_START+0x265)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x28
#define FLAG_HIDDEN_ITEM_UNUSED_0x28                                     (FRLG_FLAGS_START+0x266)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x2B
#define FLAG_HIDDEN_ITEM_UNUSED_0x2B                                     (FRLG_FLAGS_START+0x267)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x2C
#define FLAG_HIDDEN_ITEM_UNUSED_0x2C                                     (FRLG_FLAGS_START+0x268)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x2D
#define FLAG_HIDDEN_ITEM_UNUSED_0x2D                                     (FRLG_FLAGS_START+0x269)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x2E
#define FLAG_HIDDEN_ITEM_UNUSED_0x2E                                     (FRLG_FLAGS_START+0x26A)
#undef  FLAG_HIDDEN_ITEM_UNUSED_0x7C
#define FLAG_HIDDEN_ITEM_UNUSED_0x7C                                     (FRLG_FLAGS_START+0x26B)
#undef  FLAG_HIDDEN_ITEM_VERMILION_CITY_MAX_ETHER
#define FLAG_HIDDEN_ITEM_VERMILION_CITY_MAX_ETHER                        (FRLG_FLAGS_START+0x26C)
#undef  FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_FULL_RESTORE
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_FULL_RESTORE                    (FRLG_FLAGS_START+0x26D)
#undef  FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL                      (FRLG_FLAGS_START+0x26E)
#undef  FLAG_HIDDEN_ITEM_VIRIDIAN_CITY_GYM_MACHO_BRACE
#define FLAG_HIDDEN_ITEM_VIRIDIAN_CITY_GYM_MACHO_BRACE                   (FRLG_FLAGS_START+0x26F)
#undef  FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_ANTIDOTE
#define FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_ANTIDOTE                        (FRLG_FLAGS_START+0x270)
#undef  FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_POTION
#define FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_POTION                          (FRLG_FLAGS_START+0x271)



// Kanto-Merge: Restliche Festland-Flags, die flags_hns.h auf 0 stubbt.

#undef  FLAG_SYS_GOT_BERRY_POUCH
#define FLAG_SYS_GOT_BERRY_POUCH                       (FRLG_FLAGS_START+0x272)
#undef  FLAG_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM
#define FLAG_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM    (FRLG_FLAGS_START+0x273)
#undef  FLAG_WORLD_MAP_SSANNE_EXTERIOR
#define FLAG_WORLD_MAP_SSANNE_EXTERIOR                 (FRLG_FLAGS_START+0x274)
#undef  FLAG_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL
#define FLAG_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL (FRLG_FLAGS_START+0x275)
#undef  FLAG_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL
#define FLAG_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL (FRLG_FLAGS_START+0x276)



// Kanto-Merge: Anruf der Mutter nach ihrer PokeCom-Uebergabe.

#undef  FLAG_HNS_MOM_CALL_PENDING
#define FLAG_HNS_MOM_CALL_PENDING                      (FRLG_FLAGS_START+0x278)



// Kanto-Merge: Mamas PokeCom-Kontakt (in flags_hns.h auf 0 gestubbt).

#undef  FLAG_ENABLE_MOM_MATCH_CALL
#define FLAG_ENABLE_MOM_MATCH_CALL                     (FRLG_FLAGS_START+0x279)



// Kanto-Merge: Wird beim ersten Betreten von Route 26 Nord gesetzt und
// schaltet die Regionskarte von Kanto auf die kombinierte JK-Karte um.

#define FLAG_VISITED_JOHTO                             (FRLG_FLAGS_START+0x27A)



// Kanto-Merge: Sarah sitzt zu Beginn bei der Mutter und geht, sobald der
// Spieler seinen Starter hat.
#define FLAG_HIDE_PALLET_HOUSE_DAISY                   (FRLG_FLAGS_START+0x27B)


// Kanto-Merge: Sarah ist zu Beginn bei uns zu Besuch und deshalb nicht
// zu Hause. Das Flag faellt, sobald der Starter vergeben ist.
#define FLAG_HIDE_RIVALS_HOUSE_DAISY                   (FRLG_FLAGS_START+0x27C)


// Kanto-Merge: Weltkarten-Flags. flags_hns.h stubbt sie auf 0, wodurch
// saemtliche Flugziele von Beginn an als besucht galten.

#undef  FLAG_WORLD_MAP_CELADON_CITY
#define FLAG_WORLD_MAP_CELADON_CITY                              (FRLG_FLAGS_START+0x27D)
#undef  FLAG_WORLD_MAP_CERULEAN_CAVE_1F
#define FLAG_WORLD_MAP_CERULEAN_CAVE_1F                          (FRLG_FLAGS_START+0x27E)
#undef  FLAG_WORLD_MAP_CERULEAN_CITY
#define FLAG_WORLD_MAP_CERULEAN_CITY                             (FRLG_FLAGS_START+0x27F)
#undef  FLAG_WORLD_MAP_CINNABAR_ISLAND
#define FLAG_WORLD_MAP_CINNABAR_ISLAND                           (FRLG_FLAGS_START+0x280)
#undef  FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F
#define FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F                         (FRLG_FLAGS_START+0x281)
#undef  FLAG_WORLD_MAP_FUCHSIA_CITY
#define FLAG_WORLD_MAP_FUCHSIA_CITY                              (FRLG_FLAGS_START+0x282)
#undef  FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR
#define FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR                   (FRLG_FLAGS_START+0x283)
#undef  FLAG_WORLD_MAP_LAVENDER_TOWN
#define FLAG_WORLD_MAP_LAVENDER_TOWN                             (FRLG_FLAGS_START+0x284)
#undef  FLAG_WORLD_MAP_MT_MOON_1F
#define FLAG_WORLD_MAP_MT_MOON_1F                                (FRLG_FLAGS_START+0x285)
#undef  FLAG_WORLD_MAP_PALLET_TOWN
#define FLAG_WORLD_MAP_PALLET_TOWN                               (FRLG_FLAGS_START+0x286)
#undef  FLAG_WORLD_MAP_PEWTER_CITY
#define FLAG_WORLD_MAP_PEWTER_CITY                               (FRLG_FLAGS_START+0x287)
#undef  FLAG_WORLD_MAP_POKEMON_MANSION_1F
#define FLAG_WORLD_MAP_POKEMON_MANSION_1F                        (FRLG_FLAGS_START+0x288)
#undef  FLAG_WORLD_MAP_POKEMON_TOWER_1F
#define FLAG_WORLD_MAP_POKEMON_TOWER_1F                          (FRLG_FLAGS_START+0x289)
#undef  FLAG_WORLD_MAP_POWER_PLANT
#define FLAG_WORLD_MAP_POWER_PLANT                               (FRLG_FLAGS_START+0x28A)
#undef  FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F
#define FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F                        (FRLG_FLAGS_START+0x28B)
#undef  FLAG_WORLD_MAP_ROCK_TUNNEL_1F
#define FLAG_WORLD_MAP_ROCK_TUNNEL_1F                            (FRLG_FLAGS_START+0x28C)
#undef  FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F
#define FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F                 (FRLG_FLAGS_START+0x28D)
#undef  FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F
#define FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F                  (FRLG_FLAGS_START+0x28E)
#undef  FLAG_WORLD_MAP_SAFARI_ZONE_CENTER
#define FLAG_WORLD_MAP_SAFARI_ZONE_CENTER                        (FRLG_FLAGS_START+0x28F)
#undef  FLAG_WORLD_MAP_SAFFRON_CITY
#define FLAG_WORLD_MAP_SAFFRON_CITY                              (FRLG_FLAGS_START+0x290)
#undef  FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F
#define FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F                        (FRLG_FLAGS_START+0x291)
#undef  FLAG_WORLD_MAP_SILPH_CO_1F
#define FLAG_WORLD_MAP_SILPH_CO_1F                               (FRLG_FLAGS_START+0x292)
#undef  FLAG_WORLD_MAP_VERMILION_CITY
#define FLAG_WORLD_MAP_VERMILION_CITY                            (FRLG_FLAGS_START+0x293)
#undef  FLAG_WORLD_MAP_VICTORY_ROAD_1F
#define FLAG_WORLD_MAP_VICTORY_ROAD_1F                           (FRLG_FLAGS_START+0x294)
#undef  FLAG_WORLD_MAP_VIRIDIAN_CITY
#define FLAG_WORLD_MAP_VIRIDIAN_CITY                             (FRLG_FLAGS_START+0x295)
#undef  FLAG_WORLD_MAP_VIRIDIAN_FOREST
#define FLAG_WORLD_MAP_VIRIDIAN_FOREST                           (FRLG_FLAGS_START+0x296)


// Kanto-Merge: Eigener Flag fuer das Lavados auf der Siegesstrasse.
// FLAG_HIDE_MOLTRES gehoert HnS' Silberberg-Lavados und wird erst nach
// deren Ruhmeshalle geloescht - damit waere unseres nie sichtbar.
#define FLAG_HIDE_MOLTRES_KANTO                        (FRLG_FLAGS_START+0x297)


// Kanto-Merge: Zwei Evo-Items, die HnS-Kanto als Versteck fuehrte.

#define FLAG_HIDDEN_ITEM_CERULEAN_CAVE_B1F_ELECTIRIZER       (FRLG_FLAGS_START+0x298)
#define FLAG_HIDDEN_ITEM_ROCK_TUNNEL_B1F_OVAL_STONE          (FRLG_FLAGS_START+0x299)


// Kanto-Merge: Evo-Items als Ballitems an thematisch passenden Orten.

#define FLAG_HIDE_SILPHCO_9F_UP_GRADE                        (FRLG_FLAGS_START+0x29A)
#define FLAG_HIDE_SILPHCO_10F_DUBIOUS_DISC                   (FRLG_FLAGS_START+0x29B)
#define FLAG_HIDE_MTMOON_1F_PROTECTOR                        (FRLG_FLAGS_START+0x29C)
#define FLAG_HIDE_POKEMONMANSION_2F_MAGMARIZER               (FRLG_FLAGS_START+0x29D)

// Kanto-Merge: Mew in der Kammer hinter dem Mondberg (B3F), erreichbar
// erst mit VM Staerke. Gleiches Muster wie FLAG_HIDE_MOLTRES_KANTO.
#define FLAG_HIDE_MEW_KANTO                                  (FRLG_FLAGS_START+0x29E)

#define FRLG_FLAGS_END (FRLG_FLAGS_START+0x29E)

#define FRLG_NUM_FLAG_BYTES (((FRLG_FLAGS_END - FRLG_FLAGS_START + 1) + 7) / 8)

#endif // GUARD_CONSTANTS_FLAGS_FRLG_HNS_H
