// Add new IDs here
enum {
    HELP_DEMO_WINDOW,
    HELP_GAMESTART_WINDOW,
    HELP_TRADE_WINDOW,
    HELP_TELEPORTER_WINDOW,
    HELP_SINJOH_WINDOW,
    HELP_ALOLA_WINDOW,
    HELP_DAYCARE1_WINDOW,
    HELP_DAYCARE2_WINDOW,
    HELP_DAYCARE3_WINDOW,
    HELP_DAYCARE4_WINDOW,
    HELP_POKEBLOCK_WINDOW,
    HELP_GOLD_POKEBLOCK_WINDOW,
    HELP_COUNT
};
