#ifndef GUARD_ITEM_CONSTANTS_H
#define GUARD_ITEM_CONSTANTS_H

#include "config/item.h"

#if I_COMBINE_BAG_POCKETS == TRUE
enum Pocket
{
    POCKET_ITEMS,
    POCKET_MEDICINE,
    POCKET_POKE_BALLS,
    POCKET_TM_HM,
    POCKET_BERRIES,
    POCKET_KEY_ITEMS,
    POCKETS_COUNT,
    POCKET_DUMMY = POCKETS_COUNT,
};
#define POCKET_TREASURES POCKET_ITEMS
#define POCKET_BATTLE_ITEMS POCKET_MEDICINE
#else
enum Pocket
{
    POCKET_ITEMS,
    POCKET_MEDICINE,
    POCKET_POKE_BALLS,
    POCKET_TM_HM,
    POCKET_BERRIES,
    POCKET_BATTLE_ITEMS,
    POCKET_TREASURES,
    POCKET_KEY_ITEMS,
    POCKETS_COUNT,
    POCKET_DUMMY = POCKETS_COUNT,
};
#endif

#define REPEL_LURE_MASK         (1 << 15)
#define IS_LAST_USED_LURE(var)  (var & REPEL_LURE_MASK)
#define REPEL_LURE_STEPS(var)   (var & (REPEL_LURE_MASK - 1))
#define LURE_STEP_COUNT         (IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)
#define REPEL_STEP_COUNT        (!IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)

#define ITEM_SELL_FACTOR ((I_SELL_VALUE_FRACTION >= GEN_9) ? 4 : 2)

#endif // GUARD_ITEM_CONSTANTS_H
