#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"
#include "constants/opponents_hns.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      619
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          620
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          621
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          622
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          623
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       624
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       625
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       626
#define TRAINER_GABRIELLE_1                   627
#define TRAINER_GRUNT_PETALBURG_WOODS        628
#define TRAINER_MARCEL                       629
#define TRAINER_ALBERTO                      630
#define TRAINER_ED                           631
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      632
#define TRAINER_DECLAN                       633
#define TRAINER_GRUNT_RUSTURF_TUNNEL         634
#define TRAINER_GRUNT_WEATHER_INST_1         635
#define TRAINER_GRUNT_WEATHER_INST_2         636
#define TRAINER_GRUNT_WEATHER_INST_3         637
#define TRAINER_GRUNT_MUSEUM_1               638
#define TRAINER_GRUNT_MUSEUM_2               639
#define TRAINER_GRUNT_SPACE_CENTER_1         640
#define TRAINER_GRUNT_MT_PYRE_1              641
#define TRAINER_GRUNT_MT_PYRE_2              642
#define TRAINER_GRUNT_MT_PYRE_3              643
#define TRAINER_GRUNT_WEATHER_INST_4         644
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         645
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         646
#define TRAINER_FREDRICK                     647
#define TRAINER_MATT                         648
#define TRAINER_ZANDER                       649
#define TRAINER_SHELLY_WEATHER_INSTITUTE     650
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       651
#define TRAINER_ARCHIE                       652
#define TRAINER_LEAH                         653
#define TRAINER_DAISY                        654
#define TRAINER_ROSE_1                       655
#define TRAINER_FELIX                        656
#define TRAINER_VIOLET                       657
#define TRAINER_ROSE_2                       658
#define TRAINER_ROSE_3                       659
#define TRAINER_ROSE_4                       660
#define TRAINER_ROSE_5                       661
#define TRAINER_DUSTY_1                      662
#define TRAINER_CHIP                         663
#define TRAINER_FOSTER                       664
#define TRAINER_DUSTY_2                      665
#define TRAINER_DUSTY_3                      666
#define TRAINER_DUSTY_4                      667
#define TRAINER_DUSTY_5                      668
#define TRAINER_GABBY_AND_TY_1               669
#define TRAINER_GABBY_AND_TY_2               670
#define TRAINER_GABBY_AND_TY_3               671
#define TRAINER_GABBY_AND_TY_4               672
#define TRAINER_GABBY_AND_TY_5               673
#define TRAINER_GABBY_AND_TY_6               674
#define TRAINER_LOLA_1                       675
#define TRAINER_AUSTINA                      676
#define TRAINER_GWEN                         677
#define TRAINER_LOLA_2                       678
#define TRAINER_LOLA_3                       679
#define TRAINER_LOLA_4                       680
#define TRAINER_LOLA_5                       681
#define TRAINER_RICKY_1                      682
#define TRAINER_SIMON                        683
#define TRAINER_CHARLIE                      684
#define TRAINER_RICKY_2                      685
#define TRAINER_RICKY_3                      686
#define TRAINER_RICKY_4                      687
#define TRAINER_RICKY_5                      688
#define TRAINER_RANDALL                      689
#define TRAINER_PARKER                       690
#define TRAINER_GEORGE                       691
#define TRAINER_BERKE                        692
#define TRAINER_BRAXTON                      693
#define TRAINER_VINCENT                      694
#define TRAINER_LEROY                        695
#define TRAINER_WILTON_1                     696
#define TRAINER_EDGAR                        697
#define TRAINER_ALBERT                       698
#define TRAINER_SAMUEL                       699
#define TRAINER_VITO                         700
#define TRAINER_OWEN                         701
#define TRAINER_WILTON_2                     702
#define TRAINER_WILTON_3                     703
#define TRAINER_WILTON_4                     704
#define TRAINER_WILTON_5                     705
#define TRAINER_WARREN                       706
#define TRAINER_MARY                         707
#define TRAINER_ALEXIA                       708
#define TRAINER_JODY                         709
#define TRAINER_WENDY                        710
#define TRAINER_KEIRA                        711
#define TRAINER_BROOKE_1                     712
#define TRAINER_JENNIFER                     713
#define TRAINER_HOPE                         714
#define TRAINER_SHANNON                      715
#define TRAINER_MICHELLE                     716
#define TRAINER_CAROLINE                     717
#define TRAINER_JULIE                       718
#define TRAINER_BROOKE_2                    719
#define TRAINER_BROOKE_3                    720
#define TRAINER_BROOKE_4                    721
#define TRAINER_BROOKE_5                    722
#define TRAINER_PATRICIA                    723
#define TRAINER_KINDRA                      724
#define TRAINER_TAMMY                       725
#define TRAINER_VALERIE_1                   726
#define TRAINER_TASHA                       727
#define TRAINER_VALERIE_2                   728
#define TRAINER_VALERIE_3                   729
#define TRAINER_VALERIE_4                   730
#define TRAINER_VALERIE_5                   731
#define TRAINER_CINDY_1                     732
#define TRAINER_DAPHNE                      733
#define TRAINER_GRUNT_SPACE_CENTER_2        734
#define TRAINER_CINDY_2                     735
#define TRAINER_BRIANNA                     736
#define TRAINER_NAOMI                       737
#define TRAINER_CINDY_3                     738
#define TRAINER_CINDY_4                     739
#define TRAINER_CINDY_5                     740
#define TRAINER_CINDY_6                     741
#define TRAINER_MELISSA                     742
#define TRAINER_SHEILA                      743
#define TRAINER_SHIRLEY                     744
#define TRAINER_JESSICA_1                   745
#define TRAINER_CONNIE                      746
#define TRAINER_BRIDGET                     747
#define TRAINER_OLIVIA                      748
#define TRAINER_TIFFANY                     749
#define TRAINER_JESSICA_2                   750
#define TRAINER_JESSICA_3                   751
#define TRAINER_JESSICA_4                   752
#define TRAINER_JESSICA_5                   753
#define TRAINER_WINSTON_1                   754
#define TRAINER_MOLLIE                      755
#define TRAINER_GARRET                      756
#define TRAINER_WINSTON_2                   757
#define TRAINER_WINSTON_3                   758
#define TRAINER_WINSTON_4                   759
#define TRAINER_WINSTON_5                   760
#define TRAINER_STEVE_1                     761
#define TRAINER_THALIA_1                    762
#define TRAINER_MARK                        763
#define TRAINER_GRUNT_MT_CHIMNEY_1          764
#define TRAINER_STEVE_2                     765
#define TRAINER_STEVE_3                     766
#define TRAINER_STEVE_4                     767
#define TRAINER_STEVE_5                     768
#define TRAINER_LUIS                        769
#define TRAINER_DOMINIK                     770
#define TRAINER_DOUGLAS                     771
#define TRAINER_DARRIN                      772
#define TRAINER_TONY_1                      773
#define TRAINER_JEROME                      774
#define TRAINER_MATTHEW                     775
#define TRAINER_DAVID                       776
#define TRAINER_SPENCER                     777
#define TRAINER_ROLAND                      778
#define TRAINER_NOLEN                       779
#define TRAINER_STAN                        780
#define TRAINER_BARRY                       781
#define TRAINER_DEAN                        782
#define TRAINER_RODNEY                      783
#define TRAINER_RICHARD                     784
#define TRAINER_HERMAN                      785
#define TRAINER_SANTIAGO                    786
#define TRAINER_GILBERT                     787
#define TRAINER_FRANKLIN                    788
#define TRAINER_KEVIN                       789
#define TRAINER_JACK                        790
#define TRAINER_DUDLEY                      791
#define TRAINER_CHAD                        792
#define TRAINER_TONY_2                      793
#define TRAINER_TONY_3                      794
#define TRAINER_TONY_4                      795
#define TRAINER_TONY_5                      796
#define TRAINER_TAKAO                       797
#define TRAINER_HITOSHI                     798
#define TRAINER_KIYO                        799
#define TRAINER_KOICHI                      800
#define TRAINER_NOB_1                       801
#define TRAINER_NOB_2                       802
#define TRAINER_NOB_3                       803
#define TRAINER_NOB_4                       804
#define TRAINER_NOB_5                       805
#define TRAINER_YUJI                        806
#define TRAINER_DAISUKE                     807
#define TRAINER_ATSUSHI                     808
#define TRAINER_KIRK                        809
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        810
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        811
#define TRAINER_SHAWN                       812
#define TRAINER_FERNANDO_1                  813
#define TRAINER_DALTON_1                    814
#define TRAINER_DALTON_2                    815
#define TRAINER_DALTON_3                    816
#define TRAINER_DALTON_4                    817
#define TRAINER_DALTON_5                    818
#define TRAINER_COLE                        819
#define TRAINER_JEFF                        820
#define TRAINER_AXLE                        821
#define TRAINER_JACE                        822
#define TRAINER_KEEGAN                      823
#define TRAINER_BERNIE_1                    824
#define TRAINER_BERNIE_2                    825
#define TRAINER_BERNIE_3                    826
#define TRAINER_BERNIE_4                    827
#define TRAINER_BERNIE_5                    828
#define TRAINER_DREW                        829
#define TRAINER_BEAU                        830
#define TRAINER_LARRY                       831
#define TRAINER_SHANE                       832
#define TRAINER_JUSTIN                      833
#define TRAINER_ETHAN_1                     834
#define TRAINER_AUTUMN                      835
#define TRAINER_TRAVIS                      836
#define TRAINER_ETHAN_2                     837
#define TRAINER_ETHAN_3                     838
#define TRAINER_ETHAN_4                     839
#define TRAINER_ETHAN_5                     840
#define TRAINER_BRENT                       841
#define TRAINER_DONALD                      842
#define TRAINER_TAYLOR                      843
#define TRAINER_JEFFREY_1                   844
#define TRAINER_DEREK                       845
#define TRAINER_JEFFREY_2                   846
#define TRAINER_JEFFREY_3                   847
#define TRAINER_JEFFREY_4                   848
#define TRAINER_JEFFREY_5                   849
#define TRAINER_EDWARD                      850
#define TRAINER_PRESTON                     851
#define TRAINER_VIRGIL                      852
#define TRAINER_BLAKE                       853
#define TRAINER_WILLIAM                     854
#define TRAINER_JOSHUA                      855
#define TRAINER_CAMERON_1                   856
#define TRAINER_CAMERON_2                   857
#define TRAINER_CAMERON_3                   858
#define TRAINER_CAMERON_4                   859
#define TRAINER_CAMERON_5                   860
#define TRAINER_JACLYN                      861
#define TRAINER_HANNAH                      862
#define TRAINER_SAMANTHA                    863
#define TRAINER_MAURA                       864
#define TRAINER_KAYLA                       865
#define TRAINER_ALEXIS                      866
#define TRAINER_JACKI_1                     867
#define TRAINER_JACKI_2                     868
#define TRAINER_JACKI_3                     869
#define TRAINER_JACKI_4                     870
#define TRAINER_JACKI_5                     871
#define TRAINER_WALTER_1                    872
#define TRAINER_MICAH                       873
#define TRAINER_THOMAS                      874
#define TRAINER_WALTER_2                    875
#define TRAINER_WALTER_3                    876
#define TRAINER_WALTER_4                    877
#define TRAINER_WALTER_5                    878
#define TRAINER_SIDNEY                      879
#define TRAINER_PHOEBE                      880
#define TRAINER_GLACIA                      881
#define TRAINER_DRAKE                       882
#define TRAINER_ROXANNE_1                   883
#define TRAINER_BRAWLY_1                    884
#define TRAINER_WATTSON_1                   885
#define TRAINER_FLANNERY_1                  886
#define TRAINER_NORMAN_1                    887
#define TRAINER_WINONA_1                    888
#define TRAINER_TATE_AND_LIZA_1             889
#define TRAINER_JUAN_1                      890
#define TRAINER_JERRY_1                     891
#define TRAINER_TED                         892
#define TRAINER_PAUL                        893
#define TRAINER_JERRY_2                     894
#define TRAINER_JERRY_3                     895
#define TRAINER_JERRY_4                     896
#define TRAINER_JERRY_5                     897
#define TRAINER_KAREN_1                     898
#define TRAINER_GEORGIA                     899
#define TRAINER_KAREN_2                     900
#define TRAINER_KAREN_3                     901
#define TRAINER_KAREN_4                     902
#define TRAINER_KAREN_5                     903
#define TRAINER_KATE_AND_JOY                904
#define TRAINER_ANNA_AND_MEG_1              905
#define TRAINER_ANNA_AND_MEG_2              906
#define TRAINER_ANNA_AND_MEG_3              907
#define TRAINER_ANNA_AND_MEG_4              908
#define TRAINER_ANNA_AND_MEG_5              909
#define TRAINER_VICTOR                      910
#define TRAINER_MIGUEL_1                    911
#define TRAINER_COLTON                      912
#define TRAINER_MIGUEL_2                    913
#define TRAINER_MIGUEL_3                    914
#define TRAINER_MIGUEL_4                    915
#define TRAINER_MIGUEL_5                    916
#define TRAINER_VICTORIA                    917
#define TRAINER_VANESSA                     918
#define TRAINER_BETHANY                     919
#define TRAINER_ISABEL_1                    920
#define TRAINER_ISABEL_2                    921
#define TRAINER_ISABEL_3                    922
#define TRAINER_ISABEL_4                    923
#define TRAINER_ISABEL_5                    924
#define TRAINER_TIMOTHY_1                   925
#define TRAINER_TIMOTHY_2                   926
#define TRAINER_TIMOTHY_3                   927
#define TRAINER_TIMOTHY_4                   928
#define TRAINER_TIMOTHY_5                   929
#define TRAINER_VICKY                       930
#define TRAINER_SHELBY_1                    931
#define TRAINER_SHELBY_2                    932
#define TRAINER_SHELBY_3                    933
#define TRAINER_SHELBY_4                    934
#define TRAINER_SHELBY_5                    935
#define TRAINER_CALVIN_1                    936
#define TRAINER_BILLY                       937
#define TRAINER_JOSH                        938
#define TRAINER_TOMMY                       939
#define TRAINER_JOEY                        940
#define TRAINER_BEN                         941
#define TRAINER_QUINCY                      942
#define TRAINER_KATELYNN                    943
#define TRAINER_JAYLEN                      944
#define TRAINER_DILLON                      945
#define TRAINER_CALVIN_2                    946
#define TRAINER_CALVIN_3                    947
#define TRAINER_CALVIN_4                    948
#define TRAINER_CALVIN_5                    949
#define TRAINER_EDDIE                       950
#define TRAINER_ALLEN                       951
#define TRAINER_TIMMY                       952
#define TRAINER_WALLACE                     953
#define TRAINER_ANDREW                      954
#define TRAINER_IVAN                        955
#define TRAINER_CLAUDE                      956
#define TRAINER_ELLIOT_1                    957
#define TRAINER_NED                         958
#define TRAINER_DALE                        959
#define TRAINER_NOLAN                       960
#define TRAINER_BARNY                       961
#define TRAINER_WADE                        962
#define TRAINER_CARTER                      963
#define TRAINER_ELLIOT_2                    964
#define TRAINER_ELLIOT_3                    965
#define TRAINER_ELLIOT_4                    966
#define TRAINER_ELLIOT_5                    967
#define TRAINER_RONALD                      968
#define TRAINER_JACOB                       969
#define TRAINER_ANTHONY                     970
#define TRAINER_BENJAMIN_1                  971
#define TRAINER_BENJAMIN_2                  972
#define TRAINER_BENJAMIN_3                  973
#define TRAINER_BENJAMIN_4                  974
#define TRAINER_BENJAMIN_5                  975
#define TRAINER_ABIGAIL_1                   976
#define TRAINER_JASMINE                     977
#define TRAINER_ABIGAIL_2                   978
#define TRAINER_ABIGAIL_3                   979
#define TRAINER_ABIGAIL_4                   980
#define TRAINER_ABIGAIL_5                   981
#define TRAINER_DYLAN_1                     982
#define TRAINER_DYLAN_2                     983
#define TRAINER_DYLAN_3                     984
#define TRAINER_DYLAN_4                     985
#define TRAINER_DYLAN_5                     986
#define TRAINER_MARIA_1                     987
#define TRAINER_MARIA_2                     988
#define TRAINER_MARIA_3                     989
#define TRAINER_MARIA_4                     990
#define TRAINER_MARIA_5                     991
#define TRAINER_CAMDEN                      992
#define TRAINER_DEMETRIUS                   993
#define TRAINER_ISAIAH_1                    994
#define TRAINER_PABLO_1                     995
#define TRAINER_CHASE                       996
#define TRAINER_ISAIAH_2                    997
#define TRAINER_ISAIAH_3                    998
#define TRAINER_ISAIAH_4                    999
#define TRAINER_ISAIAH_5                    1000
#define TRAINER_ISOBEL                      1001
#define TRAINER_DONNY                       1002
#define TRAINER_TALIA                       1003
#define TRAINER_KATELYN_1                   1004
#define TRAINER_ALLISON                     1005
#define TRAINER_KATELYN_2                   1006
#define TRAINER_KATELYN_3                   1007
#define TRAINER_KATELYN_4                   1008
#define TRAINER_KATELYN_5                   1009
#define TRAINER_NICOLAS_1                   1010
#define TRAINER_NICOLAS_2                   1011
#define TRAINER_NICOLAS_3                   1012
#define TRAINER_NICOLAS_4                   1013
#define TRAINER_NICOLAS_5                   1014
#define TRAINER_AARON                       1015
#define TRAINER_PERRY                       1016
#define TRAINER_HUGH                        1017
#define TRAINER_PHIL                        1018
#define TRAINER_JARED                       1019
#define TRAINER_HUMBERTO                    1020
#define TRAINER_PRESLEY                     1021
#define TRAINER_EDWARDO                     1022
#define TRAINER_COLIN                       1023
#define TRAINER_ROBERT_1                    1024
#define TRAINER_BENNY                       1025
#define TRAINER_CHESTER                     1026
#define TRAINER_ROBERT_2                    1027
#define TRAINER_ROBERT_3                    1028
#define TRAINER_ROBERT_4                    1029
#define TRAINER_ROBERT_5                    1030
#define TRAINER_ALEX                        1031
#define TRAINER_BECK                        1032
#define TRAINER_YASU                        1033
#define TRAINER_TAKASHI                     1034
#define TRAINER_DIANNE                      1035
#define TRAINER_JANI                        1036
#define TRAINER_LAO_1                       1037
#define TRAINER_LUNG                        1038
#define TRAINER_LAO_2                       1039
#define TRAINER_LAO_3                       1040
#define TRAINER_LAO_4                       1041
#define TRAINER_LAO_5                       1042
#define TRAINER_JOCELYN                     1043
#define TRAINER_LAURA                       1044
#define TRAINER_CYNDY_1                     1045
#define TRAINER_CORA                        1046
#define TRAINER_PAULA                       1047
#define TRAINER_CYNDY_2                     1048
#define TRAINER_CYNDY_3                     1049
#define TRAINER_CYNDY_4                     1050
#define TRAINER_CYNDY_5                     1051
#define TRAINER_MADELINE_1                  1052
#define TRAINER_CLARISSA                    1053
#define TRAINER_ANGELICA                    1054
#define TRAINER_MADELINE_2                  1055
#define TRAINER_MADELINE_3                  1056
#define TRAINER_MADELINE_4                  1057
#define TRAINER_MADELINE_5                  1058
#define TRAINER_BEVERLY                     1059
#define TRAINER_IMANI                       1060
#define TRAINER_KYLA                        1061
#define TRAINER_DENISE                      1062
#define TRAINER_BETH                        1063
#define TRAINER_TARA                        1064
#define TRAINER_MISSY                       1065
#define TRAINER_ALICE                       1066
#define TRAINER_JENNY_1                     1067
#define TRAINER_GRACE                       1068
#define TRAINER_TANYA                       1069
#define TRAINER_SHARON                      1070
#define TRAINER_NIKKI                       1071
#define TRAINER_BRENDA                      1072
#define TRAINER_KATIE                       1073
#define TRAINER_SUSIE                       1074
#define TRAINER_KARA                        1075
#define TRAINER_DANA                        1076
#define TRAINER_SIENNA                      1077
#define TRAINER_DEBRA                       1078
#define TRAINER_LINDA                       1079
#define TRAINER_KAYLEE                      1080
#define TRAINER_LAUREL                      1081
#define TRAINER_CARLEE                      1082
#define TRAINER_JENNY_2                     1083
#define TRAINER_JENNY_3                     1084
#define TRAINER_JENNY_4                     1085
#define TRAINER_JENNY_5                     1086
#define TRAINER_HEIDI                       1087
#define TRAINER_BECKY                       1088
#define TRAINER_CAROL                       1089
#define TRAINER_NANCY                       1090
#define TRAINER_MARTHA                      1091
#define TRAINER_DIANA_1                     1092
#define TRAINER_CEDRIC                      1093
#define TRAINER_IRENE                       1094
#define TRAINER_DIANA_2                     1095
#define TRAINER_DIANA_3                     1096
#define TRAINER_DIANA_4                     1097
#define TRAINER_DIANA_5                     1098
#define TRAINER_AMY_AND_LIV_1               1099
#define TRAINER_AMY_AND_LIV_2               1100
#define TRAINER_GINA_AND_MIA_1              1101
#define TRAINER_MIU_AND_YUKI                1102
#define TRAINER_AMY_AND_LIV_3               1103
#define TRAINER_GINA_AND_MIA_2              1104
#define TRAINER_AMY_AND_LIV_4               1105
#define TRAINER_AMY_AND_LIV_5               1106
#define TRAINER_AMY_AND_LIV_6               1107
#define TRAINER_HUEY                        1108
#define TRAINER_EDMOND                      1109
#define TRAINER_ERNEST_1                    1110
#define TRAINER_DWAYNE                      1111
#define TRAINER_PHILLIP                     1112
#define TRAINER_LEONARD                     1113
#define TRAINER_DUNCAN                      1114
#define TRAINER_ERNEST_2                    1115
#define TRAINER_ERNEST_3                    1116
#define TRAINER_ERNEST_4                    1117
#define TRAINER_ERNEST_5                    1118
#define TRAINER_ELI                         1119
#define TRAINER_ANNIKA                      1120
#define TRAINER_JAZMYN                      1121
#define TRAINER_JONAS                       1122
#define TRAINER_KAYLEY                      1123
#define TRAINER_AURON                       1124
#define TRAINER_KELVIN                      1125
#define TRAINER_MARLEY                      1126
#define TRAINER_REYNA                       1127
#define TRAINER_HUDSON                      1128
#define TRAINER_CONOR                       1129
#define TRAINER_EDWIN_1                     1130
#define TRAINER_HECTOR                      1131
#define TRAINER_TABITHA_MOSSDEEP            1132
#define TRAINER_EDWIN_2                     1133
#define TRAINER_EDWIN_3                     1134
#define TRAINER_EDWIN_4                     1135
#define TRAINER_EDWIN_5                     1136
#define TRAINER_WALLY_VR_1                  1137
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    1138
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    1139
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    1140
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   1141
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   1142
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   1143
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   1144
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   1145
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   1146
#define TRAINER_MAY_ROUTE_103_MUDKIP        1147
#define TRAINER_MAY_ROUTE_110_MUDKIP        1148
#define TRAINER_MAY_ROUTE_119_MUDKIP        1149
#define TRAINER_MAY_ROUTE_103_TREECKO       1150
#define TRAINER_MAY_ROUTE_110_TREECKO       1151
#define TRAINER_MAY_ROUTE_119_TREECKO       1152
#define TRAINER_MAY_ROUTE_103_TORCHIC       1153
#define TRAINER_MAY_ROUTE_110_TORCHIC       1154
#define TRAINER_MAY_ROUTE_119_TORCHIC       1155
#define TRAINER_ISAAC_1                     1156
#define TRAINER_DAVIS                       1157
#define TRAINER_MITCHELL                    1158
#define TRAINER_ISAAC_2                     1159
#define TRAINER_ISAAC_3                     1160
#define TRAINER_ISAAC_4                     1161
#define TRAINER_ISAAC_5                     1162
#define TRAINER_LYDIA_1                     1163
#define TRAINER_HALLE                       1164
#define TRAINER_GARRISON                    1165
#define TRAINER_LYDIA_2                     1166
#define TRAINER_LYDIA_3                     1167
#define TRAINER_LYDIA_4                     1168
#define TRAINER_LYDIA_5                     1169
#define TRAINER_JACKSON_1                   1170
#define TRAINER_LORENZO                     1171
#define TRAINER_SEBASTIAN                   1172
#define TRAINER_JACKSON_2                   1173
#define TRAINER_JACKSON_3                   1174
#define TRAINER_JACKSON_4                   1175
#define TRAINER_JACKSON_5                   1176
#define TRAINER_CATHERINE_1                 1177
#define TRAINER_JENNA                       1178
#define TRAINER_SOPHIA                      1179
#define TRAINER_CATHERINE_2                 1180
#define TRAINER_CATHERINE_3                 1181
#define TRAINER_CATHERINE_4                 1182
#define TRAINER_CATHERINE_5                 1183
#define TRAINER_JULIO                       1184
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     1185
#define TRAINER_GRUNT_UNUSED                1186
#define TRAINER_GRUNT_MT_PYRE_4             1187
#define TRAINER_GRUNT_JAGGED_PASS           1188
#define TRAINER_MARC                        1189
#define TRAINER_BRENDEN                     1190
#define TRAINER_LILITH                      1191
#define TRAINER_CRISTIAN                    1192
#define TRAINER_SYLVIA                      1193
#define TRAINER_LEONARDO                    1194
#define TRAINER_ATHENA                      1195
#define TRAINER_HARRISON                    1196
#define TRAINER_GRUNT_MT_CHIMNEY_2          1197
#define TRAINER_CLARENCE                    1198
#define TRAINER_TERRY                       1199
#define TRAINER_NATE                        1200
#define TRAINER_KATHLEEN                    1201
#define TRAINER_CLIFFORD                    1202
#define TRAINER_NICHOLAS                    1203
#define TRAINER_GRUNT_SPACE_CENTER_3        1204
#define TRAINER_GRUNT_SPACE_CENTER_4        1205
#define TRAINER_GRUNT_SPACE_CENTER_5        1206
#define TRAINER_GRUNT_SPACE_CENTER_6        1207
#define TRAINER_GRUNT_SPACE_CENTER_7        1208
#define TRAINER_MACEY                       1209
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    1210
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     1211
#define TRAINER_PAXTON                      1212
#define TRAINER_ISABELLA                    1213
#define TRAINER_GRUNT_WEATHER_INST_5        1214
#define TRAINER_TABITHA_MT_CHIMNEY          1215
#define TRAINER_JONATHAN                    1216
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    1217
#define TRAINER_MAY_RUSTBORO_MUDKIP         1218
#define TRAINER_MAXIE_MAGMA_HIDEOUT         1219
#define TRAINER_MAXIE_MT_CHIMNEY            1220
#define TRAINER_TIANA                       1221
#define TRAINER_HALEY_1                     1222
#define TRAINER_JANICE                      1223
#define TRAINER_VIVI                        1224
#define TRAINER_HALEY_2                     1225
#define TRAINER_HALEY_3                     1226
#define TRAINER_HALEY_4                     1227
#define TRAINER_HALEY_5                     1228
#define TRAINER_SALLY                       1229
#define TRAINER_ROBIN                       1230
#define TRAINER_ANDREA                      1231
#define TRAINER_CRISSY                      1232
#define TRAINER_RICK                        1233
#define TRAINER_LYLE                        1234
#define TRAINER_JOSE                        1235
#define TRAINER_DOUG                        1236
#define TRAINER_GREG                        1237
#define TRAINER_KENT                        1238
#define TRAINER_JAMES_1                     1239
#define TRAINER_JAMES_2                     1240
#define TRAINER_JAMES_3                     1241
#define TRAINER_JAMES_4                     1242
#define TRAINER_JAMES_5                     1243
#define TRAINER_BRICE                       1244
#define TRAINER_TRENT_1                     1245
#define TRAINER_LENNY                       1246
#define TRAINER_LUCAS_1                     1247
#define TRAINER_ALAN                        1248
#define TRAINER_CLARK                       1249
#define TRAINER_ERIC                        1250
#define TRAINER_LUCAS_2                     1251
#define TRAINER_MIKE_1                      1252
#define TRAINER_MIKE_2                      1253
#define TRAINER_TRENT_2                     1254
#define TRAINER_TRENT_3                     1255
#define TRAINER_TRENT_4                     1256
#define TRAINER_TRENT_5                     1257
#define TRAINER_DEZ_AND_LUKE                1258
#define TRAINER_LEA_AND_JED                 1259
#define TRAINER_KIRA_AND_DAN_1              1260
#define TRAINER_KIRA_AND_DAN_2              1261
#define TRAINER_KIRA_AND_DAN_3              1262
#define TRAINER_KIRA_AND_DAN_4              1263
#define TRAINER_KIRA_AND_DAN_5              1264
#define TRAINER_JOHANNA                     1265
#define TRAINER_GERALD                      1266
#define TRAINER_VIVIAN                      1267
#define TRAINER_DANIELLE                    1268
#define TRAINER_HIDEO                       1269
#define TRAINER_KEIGO                       1270
#define TRAINER_RILEY                       1271
#define TRAINER_FLINT                       1272
#define TRAINER_ASHLEY                      1273
#define TRAINER_WALLY_MAUVILLE              1274
#define TRAINER_WALLY_VR_2                  1275
#define TRAINER_WALLY_VR_3                  1276
#define TRAINER_WALLY_VR_4                  1277
#define TRAINER_WALLY_VR_5                  1278
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     1279
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    1280
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    1281
#define TRAINER_MAY_LILYCOVE_MUDKIP         1282
#define TRAINER_MAY_LILYCOVE_TREECKO        1283
#define TRAINER_MAY_LILYCOVE_TORCHIC        1284
#define TRAINER_JONAH                       1285
#define TRAINER_HENRY                       1286
#define TRAINER_ROGER                       1287
#define TRAINER_ALEXA                       1288
#define TRAINER_RUBEN                       1289
#define TRAINER_KOJI_1                      1290
#define TRAINER_WAYNE                       1291
#define TRAINER_AIDAN                       1292
#define TRAINER_REED                        1293
#define TRAINER_TISHA                       1294
#define TRAINER_TORI_AND_TIA                1295
#define TRAINER_KIM_AND_IRIS                1296
#define TRAINER_TYRA_AND_IVY                1297
#define TRAINER_MEL_AND_PAUL                1298
#define TRAINER_JOHN_AND_JAY_1              1299
#define TRAINER_JOHN_AND_JAY_2              1300
#define TRAINER_JOHN_AND_JAY_3              1301
#define TRAINER_JOHN_AND_JAY_4              1302
#define TRAINER_JOHN_AND_JAY_5              1303
#define TRAINER_RELI_AND_IAN                1304
#define TRAINER_LILA_AND_ROY_1              1305
#define TRAINER_LILA_AND_ROY_2              1306
#define TRAINER_LILA_AND_ROY_3              1307
#define TRAINER_LILA_AND_ROY_4              1308
#define TRAINER_LILA_AND_ROY_5              1309
#define TRAINER_LISA_AND_RAY                1310
#define TRAINER_CHRIS                       1311
#define TRAINER_DAWSON                      1312
#define TRAINER_SARAH                       1313
#define TRAINER_DARIAN                      1314
#define TRAINER_HAILEY                      1315
#define TRAINER_CHANDLER                    1316
#define TRAINER_KALEB                       1317
#define TRAINER_JOSEPH                      1318
#define TRAINER_ALYSSA                      1319
#define TRAINER_MARCOS                      1320
#define TRAINER_RHETT                       1321
#define TRAINER_TYRON                       1322
#define TRAINER_CELINA                      1323
#define TRAINER_BIANCA                      1324
#define TRAINER_HAYDEN                      1325
#define TRAINER_SOPHIE                      1326
#define TRAINER_COBY                        1327
#define TRAINER_LAWRENCE                    1328
#define TRAINER_WYATT                       1329
#define TRAINER_ANGELINA                    1330
#define TRAINER_KAI                         1331
#define TRAINER_CHARLOTTE                   1332
#define TRAINER_DEANDRE                     1333
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       1334
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       1335
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       1336
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       1337
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       1338
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       1339
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       1340
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       1341
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       1342
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      1343
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      1344
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      1345
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      1346
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      1347
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      1348
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      1349
#define TRAINER_TABITHA_MAGMA_HIDEOUT       1350
#define TRAINER_DARCY                       1351
#define TRAINER_MAXIE_MOSSDEEP              1352
#define TRAINER_PETE                        1353
#define TRAINER_ISABELLE                    1354
#define TRAINER_ANDRES_1                    1355
#define TRAINER_JOSUE                       1356
#define TRAINER_CAMRON                      1357
#define TRAINER_CORY_1                      1358
#define TRAINER_CAROLINA                    1359
#define TRAINER_ELIJAH                      1360
#define TRAINER_CELIA                       1361
#define TRAINER_BRYAN                       1362
#define TRAINER_BRANDEN                     1363
#define TRAINER_BRYANT                      1364
#define TRAINER_SHAYLA                      1365
#define TRAINER_KYRA                        1366
#define TRAINER_JAIDEN                      1367
#define TRAINER_ALIX                        1368
#define TRAINER_HELENE                      1369
#define TRAINER_MARLENE                     1370
#define TRAINER_DEVAN                       1371
#define TRAINER_JOHNSON                     1372
#define TRAINER_MELINA                      1373
#define TRAINER_BRANDI                      1374
#define TRAINER_AISHA                       1375
#define TRAINER_MAKAYLA                     1376
#define TRAINER_FABIAN                      1377
#define TRAINER_DAYTON                      1378
#define TRAINER_RACHEL                      1379
#define TRAINER_LEONEL                      1380
#define TRAINER_CALLIE                      1381
#define TRAINER_CALE                        1382
#define TRAINER_MYLES                       1383
#define TRAINER_PAT                         1384
#define TRAINER_CRISTIN_1                   1385
#define TRAINER_MAY_RUSTBORO_TREECKO        1386
#define TRAINER_MAY_RUSTBORO_TORCHIC        1387
#define TRAINER_ROXANNE_2                   1388
#define TRAINER_ROXANNE_3                   1389
#define TRAINER_ROXANNE_4                   1390
#define TRAINER_ROXANNE_5                   1391
#define TRAINER_BRAWLY_2                    1392
#define TRAINER_BRAWLY_3                    1393
#define TRAINER_BRAWLY_4                    1394
#define TRAINER_BRAWLY_5                    1395
#define TRAINER_WATTSON_2                   1396
#define TRAINER_WATTSON_3                   1397
#define TRAINER_WATTSON_4                   1398
#define TRAINER_WATTSON_5                   1399
#define TRAINER_FLANNERY_2                  1400
#define TRAINER_FLANNERY_3                  1401
#define TRAINER_FLANNERY_4                  1402
#define TRAINER_FLANNERY_5                  1403
#define TRAINER_NORMAN_2                    1404
#define TRAINER_NORMAN_3                    1405
#define TRAINER_NORMAN_4                    1406
#define TRAINER_NORMAN_5                    1407
#define TRAINER_WINONA_2                    1408
#define TRAINER_WINONA_3                    1409
#define TRAINER_WINONA_4                    1410
#define TRAINER_WINONA_5                    1411
#define TRAINER_TATE_AND_LIZA_2             1412
#define TRAINER_TATE_AND_LIZA_3             1413
#define TRAINER_TATE_AND_LIZA_4             1414
#define TRAINER_TATE_AND_LIZA_5             1415
#define TRAINER_JUAN_2                      1416
#define TRAINER_JUAN_3                      1417
#define TRAINER_JUAN_4                      1418
#define TRAINER_JUAN_5                      1419
#define TRAINER_ANGELO                      1420
#define TRAINER_DARIUS                      1421
#define TRAINER_STEVEN                      1422
#define TRAINER_ANABEL                      1423
#define TRAINER_TUCKER                      1424
#define TRAINER_SPENSER                     1425
#define TRAINER_GRETA                       1426
#define TRAINER_NOLAND                      1427
#define TRAINER_LUCY                        1428
#define TRAINER_BRANDON                     1429
#define TRAINER_ANDRES_2                    1430
#define TRAINER_ANDRES_3                    1431
#define TRAINER_ANDRES_4                    1432
#define TRAINER_ANDRES_5                    1433
#define TRAINER_CORY_2                      1434
#define TRAINER_CORY_3                      1435
#define TRAINER_CORY_4                      1436
#define TRAINER_CORY_5                      1437
#define TRAINER_PABLO_2                     1438
#define TRAINER_PABLO_3                     1439
#define TRAINER_PABLO_4                     1440
#define TRAINER_PABLO_5                     1441
#define TRAINER_KOJI_2                      1442
#define TRAINER_KOJI_3                      1443
#define TRAINER_KOJI_4                      1444
#define TRAINER_KOJI_5                      1445
#define TRAINER_CRISTIN_2                   1446
#define TRAINER_CRISTIN_3                   1447
#define TRAINER_CRISTIN_4                   1448
#define TRAINER_CRISTIN_5                   1449
#define TRAINER_FERNANDO_2                  1450
#define TRAINER_FERNANDO_3                  1451
#define TRAINER_FERNANDO_4                  1452
#define TRAINER_FERNANDO_5                  1453
#define TRAINER_SAWYER_2                    1454
#define TRAINER_SAWYER_3                    1455
#define TRAINER_SAWYER_4                    1456
#define TRAINER_SAWYER_5                    1457
#define TRAINER_GABRIELLE_2                 1458
#define TRAINER_GABRIELLE_3                 1459
#define TRAINER_GABRIELLE_4                 1460
#define TRAINER_GABRIELLE_5                 1461
#define TRAINER_THALIA_2                    1462
#define TRAINER_THALIA_3                    1463
#define TRAINER_THALIA_4                    1464
#define TRAINER_THALIA_5                    1465
#define TRAINER_MARIELA                     1466
#define TRAINER_ALVARO                      1467
#define TRAINER_EVERETT                     1468
#define TRAINER_RED                         1469
#define TRAINER_LEAF                        1470
#define TRAINER_BRENDAN_PLACEHOLDER         1471
#define TRAINER_MAY_PLACEHOLDER             1472
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     855
#define MAX_TRAINERS_COUNT_EMERALD 864

#if defined(POKEMON_HNS)
#include "constants/opponents_frlg_hns.h"
#endif

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#elif IS_HNS
// Kanto-Merge: FRLG-Trainer liegen hinter den HnS/Hoenn-Trainern, die
// HnS-Rueckkampfstufen (HNS_REMATCH_TIERS_*) wiederum hinter den FRLG-Trainern.
#if HNS_REMATCH_TIERS_START != FRLG_TRAINERS_END + 1
#error "HNS_REMATCH_TIERS_START muss direkt hinter FRLG_TRAINERS_END liegen (opponents_hns.h anpassen)"
#endif
#define TRAINERS_COUNT                      (HNS_REMATCH_TIERS_END + 1)
#define MAX_TRAINERS_COUNT                  (HNS_REMATCH_TIERS_END + 3)
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
