#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_HNS_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_HNS_H

// Auto-generiert fuer den Kanto-Merge (test/kanto-start).
//
// opponents_frlg.h und opponents_hns.h werden beide unbedingt inkludiert und
// vergeben dieselben Zahlen: TRAINER_RIVAL_OAKS_LAB_SQUIRTLE = 226 =
// TRAINER_NICOLE_HNS (Schwimmerin Elke). Der erste Rivalenkampf lief deshalb
// gegen einen fremden Trainer.
//
// Gleiches Muster wie bei den Hoenn-Trainern, die in opponents.h bereits um
// TRAINERS_COUNT_HNS verschoben sind: FRLG bekommt hier seinen eigenen Block
// dahinter.

// Kanto-Merge: Der Offset bestimmt zugleich, wo die Trainerflags landen
// (TRAINER_FLAGS_START + id). Mit 1478 lagen sie ab 0xAC7 und damit mitten
// in SYS_FLAGS - besiegte Trainer setzten dort Ordensbits. Der Block liegt
// jetzt komplett oberhalb von HOENN_FLAGS_END (0xB72).
#define FRLG_TRAINER_OFFSET 1700

#undef  TRAINER_YOUNGSTER_BEN
#define TRAINER_YOUNGSTER_BEN                                (FRLG_TRAINER_OFFSET+1)
#undef  TRAINER_YOUNGSTER_CALVIN
#define TRAINER_YOUNGSTER_CALVIN                             (FRLG_TRAINER_OFFSET+2)
#undef  TRAINER_YOUNGSTER_JOSH
#define TRAINER_YOUNGSTER_JOSH                               (FRLG_TRAINER_OFFSET+3)
#undef  TRAINER_YOUNGSTER_TIMMY
#define TRAINER_YOUNGSTER_TIMMY                              (FRLG_TRAINER_OFFSET+4)
#undef  TRAINER_YOUNGSTER_JOEY
#define TRAINER_YOUNGSTER_JOEY                               (FRLG_TRAINER_OFFSET+5)
#undef  TRAINER_YOUNGSTER_DAN
#define TRAINER_YOUNGSTER_DAN                                (FRLG_TRAINER_OFFSET+6)
#undef  TRAINER_YOUNGSTER_CHAD
#define TRAINER_YOUNGSTER_CHAD                               (FRLG_TRAINER_OFFSET+7)
#undef  TRAINER_YOUNGSTER_TYLER
#define TRAINER_YOUNGSTER_TYLER                              (FRLG_TRAINER_OFFSET+8)
#undef  TRAINER_YOUNGSTER_EDDIE
#define TRAINER_YOUNGSTER_EDDIE                              (FRLG_TRAINER_OFFSET+9)
#undef  TRAINER_YOUNGSTER_DILLON
#define TRAINER_YOUNGSTER_DILLON                             (FRLG_TRAINER_OFFSET+10)
#undef  TRAINER_YOUNGSTER_YASU
#define TRAINER_YOUNGSTER_YASU                               (FRLG_TRAINER_OFFSET+11)
#undef  TRAINER_YOUNGSTER_DAVE
#define TRAINER_YOUNGSTER_DAVE                               (FRLG_TRAINER_OFFSET+12)
#undef  TRAINER_YOUNGSTER_BEN_2
#define TRAINER_YOUNGSTER_BEN_2                              (FRLG_TRAINER_OFFSET+13)
#undef  TRAINER_BUG_CATCHER_RICK
#define TRAINER_BUG_CATCHER_RICK                             (FRLG_TRAINER_OFFSET+14)
#undef  TRAINER_BUG_CATCHER_DOUG
#define TRAINER_BUG_CATCHER_DOUG                             (FRLG_TRAINER_OFFSET+15)
#undef  TRAINER_BUG_CATCHER_SAMMY
#define TRAINER_BUG_CATCHER_SAMMY                            (FRLG_TRAINER_OFFSET+16)
#undef  TRAINER_BUG_CATCHER_COLTON
#define TRAINER_BUG_CATCHER_COLTON                           (FRLG_TRAINER_OFFSET+17)
#undef  TRAINER_BUG_CATCHER_GREG
#define TRAINER_BUG_CATCHER_GREG                             (FRLG_TRAINER_OFFSET+18)
#undef  TRAINER_BUG_CATCHER_JAMES
#define TRAINER_BUG_CATCHER_JAMES                            (FRLG_TRAINER_OFFSET+19)
#undef  TRAINER_BUG_CATCHER_KENT
#define TRAINER_BUG_CATCHER_KENT                             (FRLG_TRAINER_OFFSET+20)
#undef  TRAINER_BUG_CATCHER_ROBBY
#define TRAINER_BUG_CATCHER_ROBBY                            (FRLG_TRAINER_OFFSET+21)
#undef  TRAINER_BUG_CATCHER_CALE
#define TRAINER_BUG_CATCHER_CALE                             (FRLG_TRAINER_OFFSET+22)
#undef  TRAINER_BUG_CATCHER_KEIGO
#define TRAINER_BUG_CATCHER_KEIGO                            (FRLG_TRAINER_OFFSET+23)
#undef  TRAINER_BUG_CATCHER_ELIJAH
#define TRAINER_BUG_CATCHER_ELIJAH                           (FRLG_TRAINER_OFFSET+24)
#undef  TRAINER_BUG_CATCHER_BRENT
#define TRAINER_BUG_CATCHER_BRENT                            (FRLG_TRAINER_OFFSET+25)
#undef  TRAINER_BUG_CATCHER_CONNER
#define TRAINER_BUG_CATCHER_CONNER                           (FRLG_TRAINER_OFFSET+26)
#undef  TRAINER_LASS_JANICE
#define TRAINER_LASS_JANICE                                  (FRLG_TRAINER_OFFSET+27)
#undef  TRAINER_LASS_SALLY
#define TRAINER_LASS_SALLY                                   (FRLG_TRAINER_OFFSET+28)
#undef  TRAINER_LASS_ROBIN
#define TRAINER_LASS_ROBIN                                   (FRLG_TRAINER_OFFSET+29)
#undef  TRAINER_LASS_CRISSY
#define TRAINER_LASS_CRISSY                                  (FRLG_TRAINER_OFFSET+30)
#undef  TRAINER_LASS_MIRIAM
#define TRAINER_LASS_MIRIAM                                  (FRLG_TRAINER_OFFSET+31)
#undef  TRAINER_LASS_IRIS
#define TRAINER_LASS_IRIS                                    (FRLG_TRAINER_OFFSET+32)
#undef  TRAINER_LASS_RELI
#define TRAINER_LASS_RELI                                    (FRLG_TRAINER_OFFSET+33)
#undef  TRAINER_LASS_ALI
#define TRAINER_LASS_ALI                                     (FRLG_TRAINER_OFFSET+34)
#undef  TRAINER_LASS_HALEY
#define TRAINER_LASS_HALEY                                   (FRLG_TRAINER_OFFSET+35)
#undef  TRAINER_LASS_ANN
#define TRAINER_LASS_ANN                                     (FRLG_TRAINER_OFFSET+36)
#undef  TRAINER_LASS_DAWN
#define TRAINER_LASS_DAWN                                    (FRLG_TRAINER_OFFSET+37)
#undef  TRAINER_LASS_PAIGE
#define TRAINER_LASS_PAIGE                                   (FRLG_TRAINER_OFFSET+38)
#undef  TRAINER_LASS_ANDREA
#define TRAINER_LASS_ANDREA                                  (FRLG_TRAINER_OFFSET+39)
#undef  TRAINER_LASS_MEGAN
#define TRAINER_LASS_MEGAN                                   (FRLG_TRAINER_OFFSET+40)
#undef  TRAINER_LASS_JULIA
#define TRAINER_LASS_JULIA                                   (FRLG_TRAINER_OFFSET+41)
#undef  TRAINER_LASS_KAY
#define TRAINER_LASS_KAY                                     (FRLG_TRAINER_OFFSET+42)
#undef  TRAINER_LASS_LISA
#define TRAINER_LASS_LISA                                    (FRLG_TRAINER_OFFSET+43)
#undef  TRAINER_SAILOR_EDMOND
#define TRAINER_SAILOR_EDMOND                                (FRLG_TRAINER_OFFSET+44)
#undef  TRAINER_SAILOR_TREVOR
#define TRAINER_SAILOR_TREVOR                                (FRLG_TRAINER_OFFSET+45)
#undef  TRAINER_SAILOR_LEONARD
#define TRAINER_SAILOR_LEONARD                               (FRLG_TRAINER_OFFSET+46)
#undef  TRAINER_SAILOR_DUNCAN
#define TRAINER_SAILOR_DUNCAN                                (FRLG_TRAINER_OFFSET+47)
#undef  TRAINER_SAILOR_HUEY
#define TRAINER_SAILOR_HUEY                                  (FRLG_TRAINER_OFFSET+48)
#undef  TRAINER_SAILOR_DYLAN
#define TRAINER_SAILOR_DYLAN                                 (FRLG_TRAINER_OFFSET+49)
#undef  TRAINER_SAILOR_PHILLIP
#define TRAINER_SAILOR_PHILLIP                               (FRLG_TRAINER_OFFSET+50)
#undef  TRAINER_SAILOR_DWAYNE
#define TRAINER_SAILOR_DWAYNE                                (FRLG_TRAINER_OFFSET+51)
#undef  TRAINER_CAMPER_LIAM
#define TRAINER_CAMPER_LIAM                                  (FRLG_TRAINER_OFFSET+52)
#undef  TRAINER_CAMPER_SHANE
#define TRAINER_CAMPER_SHANE                                 (FRLG_TRAINER_OFFSET+53)
#undef  TRAINER_CAMPER_ETHAN
#define TRAINER_CAMPER_ETHAN                                 (FRLG_TRAINER_OFFSET+54)
#undef  TRAINER_CAMPER_RICKY
#define TRAINER_CAMPER_RICKY                                 (FRLG_TRAINER_OFFSET+55)
#undef  TRAINER_CAMPER_JEFF
#define TRAINER_CAMPER_JEFF                                  (FRLG_TRAINER_OFFSET+56)
#undef  TRAINER_CAMPER_CHRIS
#define TRAINER_CAMPER_CHRIS                                 (FRLG_TRAINER_OFFSET+57)
#undef  TRAINER_CAMPER_DREW
#define TRAINER_CAMPER_DREW                                  (FRLG_TRAINER_OFFSET+58)
#undef  TRAINER_PICNICKER_DIANA
#define TRAINER_PICNICKER_DIANA                              (FRLG_TRAINER_OFFSET+59)
#undef  TRAINER_PICNICKER_NANCY
#define TRAINER_PICNICKER_NANCY                              (FRLG_TRAINER_OFFSET+60)
#undef  TRAINER_PICNICKER_ISABELLE
#define TRAINER_PICNICKER_ISABELLE                           (FRLG_TRAINER_OFFSET+61)
#undef  TRAINER_PICNICKER_KELSEY
#define TRAINER_PICNICKER_KELSEY                             (FRLG_TRAINER_OFFSET+62)
#undef  TRAINER_PICNICKER_ALICIA
#define TRAINER_PICNICKER_ALICIA                             (FRLG_TRAINER_OFFSET+63)
#undef  TRAINER_PICNICKER_CAITLIN
#define TRAINER_PICNICKER_CAITLIN                            (FRLG_TRAINER_OFFSET+64)
#undef  TRAINER_PICNICKER_HEIDI
#define TRAINER_PICNICKER_HEIDI                              (FRLG_TRAINER_OFFSET+65)
#undef  TRAINER_PICNICKER_CAROL
#define TRAINER_PICNICKER_CAROL                              (FRLG_TRAINER_OFFSET+66)
#undef  TRAINER_PICNICKER_SOFIA
#define TRAINER_PICNICKER_SOFIA                              (FRLG_TRAINER_OFFSET+67)
#undef  TRAINER_PICNICKER_MARTHA
#define TRAINER_PICNICKER_MARTHA                             (FRLG_TRAINER_OFFSET+68)
#undef  TRAINER_PICNICKER_TINA
#define TRAINER_PICNICKER_TINA                               (FRLG_TRAINER_OFFSET+69)
#undef  TRAINER_PICNICKER_HANNAH
#define TRAINER_PICNICKER_HANNAH                             (FRLG_TRAINER_OFFSET+70)
#undef  TRAINER_POKEMANIAC_MARK
#define TRAINER_POKEMANIAC_MARK                              (FRLG_TRAINER_OFFSET+71)
#undef  TRAINER_POKEMANIAC_HERMAN
#define TRAINER_POKEMANIAC_HERMAN                            (FRLG_TRAINER_OFFSET+72)
#undef  TRAINER_POKEMANIAC_COOPER
#define TRAINER_POKEMANIAC_COOPER                            (FRLG_TRAINER_OFFSET+73)
#undef  TRAINER_POKEMANIAC_STEVE
#define TRAINER_POKEMANIAC_STEVE                             (FRLG_TRAINER_OFFSET+74)
#undef  TRAINER_POKEMANIAC_WINSTON
#define TRAINER_POKEMANIAC_WINSTON                           (FRLG_TRAINER_OFFSET+75)
#undef  TRAINER_POKEMANIAC_DAWSON
#define TRAINER_POKEMANIAC_DAWSON                            (FRLG_TRAINER_OFFSET+76)
#undef  TRAINER_POKEMANIAC_ASHTON
#define TRAINER_POKEMANIAC_ASHTON                            (FRLG_TRAINER_OFFSET+77)
#undef  TRAINER_SUPER_NERD_JOVAN
#define TRAINER_SUPER_NERD_JOVAN                             (FRLG_TRAINER_OFFSET+78)
#undef  TRAINER_SUPER_NERD_MIGUEL
#define TRAINER_SUPER_NERD_MIGUEL                            (FRLG_TRAINER_OFFSET+79)
#undef  TRAINER_SUPER_NERD_AIDAN
#define TRAINER_SUPER_NERD_AIDAN                             (FRLG_TRAINER_OFFSET+80)
#undef  TRAINER_SUPER_NERD_GLENN
#define TRAINER_SUPER_NERD_GLENN                             (FRLG_TRAINER_OFFSET+81)
#undef  TRAINER_SUPER_NERD_LESLIE
#define TRAINER_SUPER_NERD_LESLIE                            (FRLG_TRAINER_OFFSET+82)
#undef  TRAINER_SUPER_NERD_ERIK
#define TRAINER_SUPER_NERD_ERIK                              (FRLG_TRAINER_OFFSET+83)
#undef  TRAINER_SUPER_NERD_AVERY
#define TRAINER_SUPER_NERD_AVERY                             (FRLG_TRAINER_OFFSET+84)
#undef  TRAINER_SUPER_NERD_DEREK
#define TRAINER_SUPER_NERD_DEREK                             (FRLG_TRAINER_OFFSET+85)
#undef  TRAINER_SUPER_NERD_ZAC
#define TRAINER_SUPER_NERD_ZAC                               (FRLG_TRAINER_OFFSET+86)
#undef  TRAINER_HIKER_MARCOS
#define TRAINER_HIKER_MARCOS                                 (FRLG_TRAINER_OFFSET+87)
#undef  TRAINER_HIKER_FRANKLIN
#define TRAINER_HIKER_FRANKLIN                               (FRLG_TRAINER_OFFSET+88)
#undef  TRAINER_HIKER_NOB
#define TRAINER_HIKER_NOB                                    (FRLG_TRAINER_OFFSET+89)
#undef  TRAINER_HIKER_WAYNE
#define TRAINER_HIKER_WAYNE                                  (FRLG_TRAINER_OFFSET+90)
#undef  TRAINER_HIKER_ALAN
#define TRAINER_HIKER_ALAN                                   (FRLG_TRAINER_OFFSET+91)
#undef  TRAINER_HIKER_BRICE
#define TRAINER_HIKER_BRICE                                  (FRLG_TRAINER_OFFSET+92)
#undef  TRAINER_HIKER_CLARK
#define TRAINER_HIKER_CLARK                                  (FRLG_TRAINER_OFFSET+93)
#undef  TRAINER_HIKER_TRENT
#define TRAINER_HIKER_TRENT                                  (FRLG_TRAINER_OFFSET+94)
#undef  TRAINER_HIKER_DUDLEY
#define TRAINER_HIKER_DUDLEY                                 (FRLG_TRAINER_OFFSET+95)
#undef  TRAINER_HIKER_ALLEN
#define TRAINER_HIKER_ALLEN                                  (FRLG_TRAINER_OFFSET+96)
#undef  TRAINER_HIKER_ERIC
#define TRAINER_HIKER_ERIC                                   (FRLG_TRAINER_OFFSET+97)
#undef  TRAINER_HIKER_LENNY
#define TRAINER_HIKER_LENNY                                  (FRLG_TRAINER_OFFSET+98)
#undef  TRAINER_HIKER_OLIVER
#define TRAINER_HIKER_OLIVER                                 (FRLG_TRAINER_OFFSET+99)
#undef  TRAINER_HIKER_LUCAS
#define TRAINER_HIKER_LUCAS                                  (FRLG_TRAINER_OFFSET+100)
#undef  TRAINER_BIKER_JARED
#define TRAINER_BIKER_JARED                                  (FRLG_TRAINER_OFFSET+101)
#undef  TRAINER_BIKER_MALIK
#define TRAINER_BIKER_MALIK                                  (FRLG_TRAINER_OFFSET+102)
#undef  TRAINER_BIKER_ERNEST
#define TRAINER_BIKER_ERNEST                                 (FRLG_TRAINER_OFFSET+103)
#undef  TRAINER_BIKER_ALEX
#define TRAINER_BIKER_ALEX                                   (FRLG_TRAINER_OFFSET+104)
#undef  TRAINER_BIKER_LAO
#define TRAINER_BIKER_LAO                                    (FRLG_TRAINER_OFFSET+105)
#undef  TRAINER_BIKER_HIDEO
#define TRAINER_BIKER_HIDEO                                  (FRLG_TRAINER_OFFSET+106)
#undef  TRAINER_BIKER_RUBEN
#define TRAINER_BIKER_RUBEN                                  (FRLG_TRAINER_OFFSET+107)
#undef  TRAINER_BIKER_BILLY
#define TRAINER_BIKER_BILLY                                  (FRLG_TRAINER_OFFSET+108)
#undef  TRAINER_BIKER_NIKOLAS
#define TRAINER_BIKER_NIKOLAS                                (FRLG_TRAINER_OFFSET+109)
#undef  TRAINER_BIKER_JAXON
#define TRAINER_BIKER_JAXON                                  (FRLG_TRAINER_OFFSET+110)
#undef  TRAINER_BIKER_WILLIAM
#define TRAINER_BIKER_WILLIAM                                (FRLG_TRAINER_OFFSET+111)
#undef  TRAINER_BIKER_LUKAS
#define TRAINER_BIKER_LUKAS                                  (FRLG_TRAINER_OFFSET+112)
#undef  TRAINER_BIKER_ISAAC
#define TRAINER_BIKER_ISAAC                                  (FRLG_TRAINER_OFFSET+113)
#undef  TRAINER_BIKER_GERALD
#define TRAINER_BIKER_GERALD                                 (FRLG_TRAINER_OFFSET+114)
#undef  TRAINER_BURGLAR_QUINN
#define TRAINER_BURGLAR_QUINN                                (FRLG_TRAINER_OFFSET+115)
#undef  TRAINER_BURGLAR_RAMON
#define TRAINER_BURGLAR_RAMON                                (FRLG_TRAINER_OFFSET+116)
#undef  TRAINER_BURGLAR_DUSTY
#define TRAINER_BURGLAR_DUSTY                                (FRLG_TRAINER_OFFSET+117)
#undef  TRAINER_BURGLAR_ARNIE
#define TRAINER_BURGLAR_ARNIE                                (FRLG_TRAINER_OFFSET+118)
#undef  TRAINER_BURGLAR_SIMON
#define TRAINER_BURGLAR_SIMON                                (FRLG_TRAINER_OFFSET+119)
#undef  TRAINER_BURGLAR_LEWIS
#define TRAINER_BURGLAR_LEWIS                                (FRLG_TRAINER_OFFSET+120)
#undef  TRAINER_ENGINEER_BAILY
#define TRAINER_ENGINEER_BAILY                               (FRLG_TRAINER_OFFSET+121)
#undef  TRAINER_ENGINEER_BRAXTON
#define TRAINER_ENGINEER_BRAXTON                             (FRLG_TRAINER_OFFSET+122)
#undef  TRAINER_ENGINEER_BERNIE
#define TRAINER_ENGINEER_BERNIE                              (FRLG_TRAINER_OFFSET+123)
#undef  TRAINER_FISHERMAN_DALE
#define TRAINER_FISHERMAN_DALE                               (FRLG_TRAINER_OFFSET+124)
#undef  TRAINER_FISHERMAN_BARNY
#define TRAINER_FISHERMAN_BARNY                              (FRLG_TRAINER_OFFSET+125)
#undef  TRAINER_FISHERMAN_NED
#define TRAINER_FISHERMAN_NED                                (FRLG_TRAINER_OFFSET+126)
#undef  TRAINER_FISHERMAN_CHIP
#define TRAINER_FISHERMAN_CHIP                               (FRLG_TRAINER_OFFSET+127)
#undef  TRAINER_FISHERMAN_HANK
#define TRAINER_FISHERMAN_HANK                               (FRLG_TRAINER_OFFSET+128)
#undef  TRAINER_FISHERMAN_ELLIOT
#define TRAINER_FISHERMAN_ELLIOT                             (FRLG_TRAINER_OFFSET+129)
#undef  TRAINER_FISHERMAN_RONALD
#define TRAINER_FISHERMAN_RONALD                             (FRLG_TRAINER_OFFSET+130)
#undef  TRAINER_FISHERMAN_CLAUDE
#define TRAINER_FISHERMAN_CLAUDE                             (FRLG_TRAINER_OFFSET+131)
#undef  TRAINER_FISHERMAN_WADE
#define TRAINER_FISHERMAN_WADE                               (FRLG_TRAINER_OFFSET+132)
#undef  TRAINER_FISHERMAN_NOLAN
#define TRAINER_FISHERMAN_NOLAN                              (FRLG_TRAINER_OFFSET+133)
#undef  TRAINER_FISHERMAN_ANDREW
#define TRAINER_FISHERMAN_ANDREW                             (FRLG_TRAINER_OFFSET+134)
#undef  TRAINER_SWIMMER_MALE_LUIS
#define TRAINER_SWIMMER_MALE_LUIS                            (FRLG_TRAINER_OFFSET+135)
#undef  TRAINER_SWIMMER_MALE_RICHARD
#define TRAINER_SWIMMER_MALE_RICHARD                         (FRLG_TRAINER_OFFSET+136)
#undef  TRAINER_SWIMMER_MALE_REECE
#define TRAINER_SWIMMER_MALE_REECE                           (FRLG_TRAINER_OFFSET+137)
#undef  TRAINER_SWIMMER_MALE_MATTHEW
#define TRAINER_SWIMMER_MALE_MATTHEW                         (FRLG_TRAINER_OFFSET+138)
#undef  TRAINER_SWIMMER_MALE_DOUGLAS
#define TRAINER_SWIMMER_MALE_DOUGLAS                         (FRLG_TRAINER_OFFSET+139)
#undef  TRAINER_SWIMMER_MALE_DAVID
#define TRAINER_SWIMMER_MALE_DAVID                           (FRLG_TRAINER_OFFSET+140)
#undef  TRAINER_SWIMMER_MALE_TONY
#define TRAINER_SWIMMER_MALE_TONY                            (FRLG_TRAINER_OFFSET+141)
#undef  TRAINER_SWIMMER_MALE_AXLE
#define TRAINER_SWIMMER_MALE_AXLE                            (FRLG_TRAINER_OFFSET+142)
#undef  TRAINER_SWIMMER_MALE_BARRY
#define TRAINER_SWIMMER_MALE_BARRY                           (FRLG_TRAINER_OFFSET+143)
#undef  TRAINER_SWIMMER_MALE_DEAN
#define TRAINER_SWIMMER_MALE_DEAN                            (FRLG_TRAINER_OFFSET+144)
#undef  TRAINER_SWIMMER_MALE_DARRIN
#define TRAINER_SWIMMER_MALE_DARRIN                          (FRLG_TRAINER_OFFSET+145)
#undef  TRAINER_SWIMMER_MALE_SPENCER
#define TRAINER_SWIMMER_MALE_SPENCER                         (FRLG_TRAINER_OFFSET+146)
#undef  TRAINER_SWIMMER_MALE_JACK
#define TRAINER_SWIMMER_MALE_JACK                            (FRLG_TRAINER_OFFSET+147)
#undef  TRAINER_SWIMMER_MALE_JEROME
#define TRAINER_SWIMMER_MALE_JEROME                          (FRLG_TRAINER_OFFSET+148)
#undef  TRAINER_SWIMMER_MALE_ROLAND
#define TRAINER_SWIMMER_MALE_ROLAND                          (FRLG_TRAINER_OFFSET+149)
#undef  TRAINER_CUE_BALL_KOJI
#define TRAINER_CUE_BALL_KOJI                                (FRLG_TRAINER_OFFSET+150)
#undef  TRAINER_CUE_BALL_LUKE
#define TRAINER_CUE_BALL_LUKE                                (FRLG_TRAINER_OFFSET+151)
#undef  TRAINER_CUE_BALL_CAMRON
#define TRAINER_CUE_BALL_CAMRON                              (FRLG_TRAINER_OFFSET+152)
#undef  TRAINER_CUE_BALL_RAUL
#define TRAINER_CUE_BALL_RAUL                                (FRLG_TRAINER_OFFSET+153)
#undef  TRAINER_CUE_BALL_ISAIAH
#define TRAINER_CUE_BALL_ISAIAH                              (FRLG_TRAINER_OFFSET+154)
#undef  TRAINER_CUE_BALL_ZEEK
#define TRAINER_CUE_BALL_ZEEK                                (FRLG_TRAINER_OFFSET+155)
#undef  TRAINER_CUE_BALL_JAMAL
#define TRAINER_CUE_BALL_JAMAL                               (FRLG_TRAINER_OFFSET+156)
#undef  TRAINER_CUE_BALL_COREY
#define TRAINER_CUE_BALL_COREY                               (FRLG_TRAINER_OFFSET+157)
#undef  TRAINER_CUE_BALL_CHASE
#define TRAINER_CUE_BALL_CHASE                               (FRLG_TRAINER_OFFSET+158)
#undef  TRAINER_GAMER_HUGO
#define TRAINER_GAMER_HUGO                                   (FRLG_TRAINER_OFFSET+159)
#undef  TRAINER_GAMER_JASPER
#define TRAINER_GAMER_JASPER                                 (FRLG_TRAINER_OFFSET+160)
#undef  TRAINER_GAMER_DIRK
#define TRAINER_GAMER_DIRK                                   (FRLG_TRAINER_OFFSET+161)
#undef  TRAINER_GAMER_DARIAN
#define TRAINER_GAMER_DARIAN                                 (FRLG_TRAINER_OFFSET+162)
#undef  TRAINER_GAMER_STAN
#define TRAINER_GAMER_STAN                                   (FRLG_TRAINER_OFFSET+163)
#undef  TRAINER_GAMER_RICH
#define TRAINER_GAMER_RICH                                   (FRLG_TRAINER_OFFSET+164)
#undef  TRAINER_BEAUTY_BRIDGET
#define TRAINER_BEAUTY_BRIDGET                               (FRLG_TRAINER_OFFSET+165)
#undef  TRAINER_BEAUTY_TAMIA
#define TRAINER_BEAUTY_TAMIA                                 (FRLG_TRAINER_OFFSET+166)
#undef  TRAINER_BEAUTY_LORI
#define TRAINER_BEAUTY_LORI                                  (FRLG_TRAINER_OFFSET+167)
#undef  TRAINER_BEAUTY_LOLA
#define TRAINER_BEAUTY_LOLA                                  (FRLG_TRAINER_OFFSET+168)
#undef  TRAINER_BEAUTY_SHEILA
#define TRAINER_BEAUTY_SHEILA                                (FRLG_TRAINER_OFFSET+169)
#undef  TRAINER_SWIMMER_FEMALE_TIFFANY
#define TRAINER_SWIMMER_FEMALE_TIFFANY                       (FRLG_TRAINER_OFFSET+170)
#undef  TRAINER_SWIMMER_FEMALE_NORA
#define TRAINER_SWIMMER_FEMALE_NORA                          (FRLG_TRAINER_OFFSET+171)
#undef  TRAINER_SWIMMER_FEMALE_MELISSA
#define TRAINER_SWIMMER_FEMALE_MELISSA                       (FRLG_TRAINER_OFFSET+172)
#undef  TRAINER_BEAUTY_GRACE
#define TRAINER_BEAUTY_GRACE                                 (FRLG_TRAINER_OFFSET+173)
#undef  TRAINER_BEAUTY_OLIVIA
#define TRAINER_BEAUTY_OLIVIA                                (FRLG_TRAINER_OFFSET+174)
#undef  TRAINER_BEAUTY_LAUREN
#define TRAINER_BEAUTY_LAUREN                                (FRLG_TRAINER_OFFSET+175)
#undef  TRAINER_SWIMMER_FEMALE_ANYA
#define TRAINER_SWIMMER_FEMALE_ANYA                          (FRLG_TRAINER_OFFSET+176)
#undef  TRAINER_SWIMMER_FEMALE_ALICE
#define TRAINER_SWIMMER_FEMALE_ALICE                         (FRLG_TRAINER_OFFSET+177)
#undef  TRAINER_SWIMMER_FEMALE_CONNIE
#define TRAINER_SWIMMER_FEMALE_CONNIE                        (FRLG_TRAINER_OFFSET+178)
#undef  TRAINER_SWIMMER_FEMALE_SHIRLEY
#define TRAINER_SWIMMER_FEMALE_SHIRLEY                       (FRLG_TRAINER_OFFSET+179)
#undef  TRAINER_PSYCHIC_JOHAN
#define TRAINER_PSYCHIC_JOHAN                                (FRLG_TRAINER_OFFSET+180)
#undef  TRAINER_PSYCHIC_TYRON
#define TRAINER_PSYCHIC_TYRON                                (FRLG_TRAINER_OFFSET+181)
#undef  TRAINER_PSYCHIC_CAMERON
#define TRAINER_PSYCHIC_CAMERON                              (FRLG_TRAINER_OFFSET+182)
#undef  TRAINER_PSYCHIC_PRESTON
#define TRAINER_PSYCHIC_PRESTON                              (FRLG_TRAINER_OFFSET+183)
#undef  TRAINER_ROCKER_RANDALL
#define TRAINER_ROCKER_RANDALL                               (FRLG_TRAINER_OFFSET+184)
#undef  TRAINER_ROCKER_LUCA
#define TRAINER_ROCKER_LUCA                                  (FRLG_TRAINER_OFFSET+185)
#undef  TRAINER_JUGGLER_DALTON
#define TRAINER_JUGGLER_DALTON                               (FRLG_TRAINER_OFFSET+186)
#undef  TRAINER_JUGGLER_NELSON
#define TRAINER_JUGGLER_NELSON                               (FRLG_TRAINER_OFFSET+187)
#undef  TRAINER_JUGGLER_KIRK
#define TRAINER_JUGGLER_KIRK                                 (FRLG_TRAINER_OFFSET+188)
#undef  TRAINER_JUGGLER_SHAWN
#define TRAINER_JUGGLER_SHAWN                                (FRLG_TRAINER_OFFSET+189)
#undef  TRAINER_JUGGLER_GREGORY
#define TRAINER_JUGGLER_GREGORY                              (FRLG_TRAINER_OFFSET+190)
#undef  TRAINER_JUGGLER_EDWARD
#define TRAINER_JUGGLER_EDWARD                               (FRLG_TRAINER_OFFSET+191)
#undef  TRAINER_JUGGLER_KAYDEN
#define TRAINER_JUGGLER_KAYDEN                               (FRLG_TRAINER_OFFSET+192)
#undef  TRAINER_JUGGLER_NATE
#define TRAINER_JUGGLER_NATE                                 (FRLG_TRAINER_OFFSET+193)
#undef  TRAINER_TAMER_PHIL
#define TRAINER_TAMER_PHIL                                   (FRLG_TRAINER_OFFSET+194)
#undef  TRAINER_TAMER_EDGAR
#define TRAINER_TAMER_EDGAR                                  (FRLG_TRAINER_OFFSET+195)
#undef  TRAINER_TAMER_JASON
#define TRAINER_TAMER_JASON                                  (FRLG_TRAINER_OFFSET+196)
#undef  TRAINER_TAMER_COLE
#define TRAINER_TAMER_COLE                                   (FRLG_TRAINER_OFFSET+197)
#undef  TRAINER_TAMER_VINCENT
#define TRAINER_TAMER_VINCENT                                (FRLG_TRAINER_OFFSET+198)
#undef  TRAINER_TAMER_JOHN
#define TRAINER_TAMER_JOHN                                   (FRLG_TRAINER_OFFSET+199)
#undef  TRAINER_BIRD_KEEPER_SEBASTIAN
#define TRAINER_BIRD_KEEPER_SEBASTIAN                        (FRLG_TRAINER_OFFSET+200)
#undef  TRAINER_BIRD_KEEPER_PERRY
#define TRAINER_BIRD_KEEPER_PERRY                            (FRLG_TRAINER_OFFSET+201)
#undef  TRAINER_BIRD_KEEPER_ROBERT
#define TRAINER_BIRD_KEEPER_ROBERT                           (FRLG_TRAINER_OFFSET+202)
#undef  TRAINER_BIRD_KEEPER_DONALD
#define TRAINER_BIRD_KEEPER_DONALD                           (FRLG_TRAINER_OFFSET+203)
#undef  TRAINER_BIRD_KEEPER_BENNY
#define TRAINER_BIRD_KEEPER_BENNY                            (FRLG_TRAINER_OFFSET+204)
#undef  TRAINER_BIRD_KEEPER_EDWIN
#define TRAINER_BIRD_KEEPER_EDWIN                            (FRLG_TRAINER_OFFSET+205)
#undef  TRAINER_BIRD_KEEPER_CHESTER
#define TRAINER_BIRD_KEEPER_CHESTER                          (FRLG_TRAINER_OFFSET+206)
#undef  TRAINER_BIRD_KEEPER_WILTON
#define TRAINER_BIRD_KEEPER_WILTON                           (FRLG_TRAINER_OFFSET+207)
#undef  TRAINER_BIRD_KEEPER_RAMIRO
#define TRAINER_BIRD_KEEPER_RAMIRO                           (FRLG_TRAINER_OFFSET+208)
#undef  TRAINER_BIRD_KEEPER_JACOB
#define TRAINER_BIRD_KEEPER_JACOB                            (FRLG_TRAINER_OFFSET+209)
#undef  TRAINER_BIRD_KEEPER_ROGER
#define TRAINER_BIRD_KEEPER_ROGER                            (FRLG_TRAINER_OFFSET+210)
#undef  TRAINER_BIRD_KEEPER_REED
#define TRAINER_BIRD_KEEPER_REED                             (FRLG_TRAINER_OFFSET+211)
#undef  TRAINER_BIRD_KEEPER_KEITH
#define TRAINER_BIRD_KEEPER_KEITH                            (FRLG_TRAINER_OFFSET+212)
#undef  TRAINER_BIRD_KEEPER_CARTER
#define TRAINER_BIRD_KEEPER_CARTER                           (FRLG_TRAINER_OFFSET+213)
#undef  TRAINER_BIRD_KEEPER_MITCH
#define TRAINER_BIRD_KEEPER_MITCH                            (FRLG_TRAINER_OFFSET+214)
#undef  TRAINER_BIRD_KEEPER_BECK
#define TRAINER_BIRD_KEEPER_BECK                             (FRLG_TRAINER_OFFSET+215)
#undef  TRAINER_BIRD_KEEPER_MARLON
#define TRAINER_BIRD_KEEPER_MARLON                           (FRLG_TRAINER_OFFSET+216)
#undef  TRAINER_BLACK_BELT_KOICHI
#define TRAINER_BLACK_BELT_KOICHI                            (FRLG_TRAINER_OFFSET+217)
#undef  TRAINER_BLACK_BELT_MIKE
#define TRAINER_BLACK_BELT_MIKE                              (FRLG_TRAINER_OFFSET+218)
#undef  TRAINER_BLACK_BELT_HIDEKI
#define TRAINER_BLACK_BELT_HIDEKI                            (FRLG_TRAINER_OFFSET+219)
#undef  TRAINER_BLACK_BELT_AARON
#define TRAINER_BLACK_BELT_AARON                             (FRLG_TRAINER_OFFSET+220)
#undef  TRAINER_BLACK_BELT_HITOSHI
#define TRAINER_BLACK_BELT_HITOSHI                           (FRLG_TRAINER_OFFSET+221)
#undef  TRAINER_BLACK_BELT_ATSUSHI
#define TRAINER_BLACK_BELT_ATSUSHI                           (FRLG_TRAINER_OFFSET+222)
#undef  TRAINER_BLACK_BELT_KIYO
#define TRAINER_BLACK_BELT_KIYO                              (FRLG_TRAINER_OFFSET+223)
#undef  TRAINER_BLACK_BELT_TAKASHI
#define TRAINER_BLACK_BELT_TAKASHI                           (FRLG_TRAINER_OFFSET+224)
#undef  TRAINER_BLACK_BELT_DAISUKE
#define TRAINER_BLACK_BELT_DAISUKE                           (FRLG_TRAINER_OFFSET+225)
#undef  TRAINER_RIVAL_OAKS_LAB_SQUIRTLE
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE                      (FRLG_TRAINER_OFFSET+226)
#undef  TRAINER_RIVAL_OAKS_LAB_BULBASAUR
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR                     (FRLG_TRAINER_OFFSET+227)
#undef  TRAINER_RIVAL_OAKS_LAB_CHARMANDER
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER                    (FRLG_TRAINER_OFFSET+228)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE                 (FRLG_TRAINER_OFFSET+229)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR                (FRLG_TRAINER_OFFSET+230)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER               (FRLG_TRAINER_OFFSET+231)
#undef  TRAINER_RIVAL_CERULEAN_SQUIRTLE
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE                      (FRLG_TRAINER_OFFSET+232)
#undef  TRAINER_RIVAL_CERULEAN_BULBASAUR
#define TRAINER_RIVAL_CERULEAN_BULBASAUR                     (FRLG_TRAINER_OFFSET+233)
#undef  TRAINER_RIVAL_CERULEAN_CHARMANDER
#define TRAINER_RIVAL_CERULEAN_CHARMANDER                    (FRLG_TRAINER_OFFSET+234)
#undef  TRAINER_SCIENTIST_TED
#define TRAINER_SCIENTIST_TED                                (FRLG_TRAINER_OFFSET+235)
#undef  TRAINER_SCIENTIST_CONNOR
#define TRAINER_SCIENTIST_CONNOR                             (FRLG_TRAINER_OFFSET+236)
#undef  TRAINER_SCIENTIST_JERRY
#define TRAINER_SCIENTIST_JERRY                              (FRLG_TRAINER_OFFSET+237)
#undef  TRAINER_SCIENTIST_JOSE
#define TRAINER_SCIENTIST_JOSE                               (FRLG_TRAINER_OFFSET+238)
#undef  TRAINER_SCIENTIST_RODNEY
#define TRAINER_SCIENTIST_RODNEY                             (FRLG_TRAINER_OFFSET+239)
#undef  TRAINER_SCIENTIST_BEAU
#define TRAINER_SCIENTIST_BEAU                               (FRLG_TRAINER_OFFSET+240)
#undef  TRAINER_SCIENTIST_TAYLOR
#define TRAINER_SCIENTIST_TAYLOR                             (FRLG_TRAINER_OFFSET+241)
#undef  TRAINER_SCIENTIST_JOSHUA
#define TRAINER_SCIENTIST_JOSHUA                             (FRLG_TRAINER_OFFSET+242)
#undef  TRAINER_SCIENTIST_PARKER
#define TRAINER_SCIENTIST_PARKER                             (FRLG_TRAINER_OFFSET+243)
#undef  TRAINER_SCIENTIST_ED
#define TRAINER_SCIENTIST_ED                                 (FRLG_TRAINER_OFFSET+244)
#undef  TRAINER_SCIENTIST_TRAVIS
#define TRAINER_SCIENTIST_TRAVIS                             (FRLG_TRAINER_OFFSET+245)
#undef  TRAINER_SCIENTIST_BRAYDON
#define TRAINER_SCIENTIST_BRAYDON                            (FRLG_TRAINER_OFFSET+246)
#undef  TRAINER_SCIENTIST_IVAN
#define TRAINER_SCIENTIST_IVAN                               (FRLG_TRAINER_OFFSET+247)
#undef  TRAINER_BOSS_GIOVANNI
#define TRAINER_BOSS_GIOVANNI                                (FRLG_TRAINER_OFFSET+248)
#undef  TRAINER_BOSS_GIOVANNI_2
#define TRAINER_BOSS_GIOVANNI_2                              (FRLG_TRAINER_OFFSET+249)
#undef  TRAINER_LEADER_GIOVANNI
#define TRAINER_LEADER_GIOVANNI                              (FRLG_TRAINER_OFFSET+250)
#undef  TRAINER_TEAM_ROCKET_GRUNT
#define TRAINER_TEAM_ROCKET_GRUNT                            (FRLG_TRAINER_OFFSET+251)
#undef  TRAINER_TEAM_ROCKET_GRUNT_2
#define TRAINER_TEAM_ROCKET_GRUNT_2                          (FRLG_TRAINER_OFFSET+252)
#undef  TRAINER_TEAM_ROCKET_GRUNT_3
#define TRAINER_TEAM_ROCKET_GRUNT_3                          (FRLG_TRAINER_OFFSET+253)
#undef  TRAINER_TEAM_ROCKET_GRUNT_4
#define TRAINER_TEAM_ROCKET_GRUNT_4                          (FRLG_TRAINER_OFFSET+254)
#undef  TRAINER_TEAM_ROCKET_GRUNT_5
#define TRAINER_TEAM_ROCKET_GRUNT_5                          (FRLG_TRAINER_OFFSET+255)
#undef  TRAINER_TEAM_ROCKET_GRUNT_6
#define TRAINER_TEAM_ROCKET_GRUNT_6                          (FRLG_TRAINER_OFFSET+256)
#undef  TRAINER_TEAM_ROCKET_GRUNT_7
#define TRAINER_TEAM_ROCKET_GRUNT_7                          (FRLG_TRAINER_OFFSET+257)
#undef  TRAINER_TEAM_ROCKET_GRUNT_8
#define TRAINER_TEAM_ROCKET_GRUNT_8                          (FRLG_TRAINER_OFFSET+258)
#undef  TRAINER_TEAM_ROCKET_GRUNT_9
#define TRAINER_TEAM_ROCKET_GRUNT_9                          (FRLG_TRAINER_OFFSET+259)
#undef  TRAINER_TEAM_ROCKET_GRUNT_10
#define TRAINER_TEAM_ROCKET_GRUNT_10                         (FRLG_TRAINER_OFFSET+260)
#undef  TRAINER_TEAM_ROCKET_GRUNT_11
#define TRAINER_TEAM_ROCKET_GRUNT_11                         (FRLG_TRAINER_OFFSET+261)
#undef  TRAINER_TEAM_ROCKET_GRUNT_12
#define TRAINER_TEAM_ROCKET_GRUNT_12                         (FRLG_TRAINER_OFFSET+262)
#undef  TRAINER_TEAM_ROCKET_GRUNT_13
#define TRAINER_TEAM_ROCKET_GRUNT_13                         (FRLG_TRAINER_OFFSET+263)
#undef  TRAINER_TEAM_ROCKET_GRUNT_14
#define TRAINER_TEAM_ROCKET_GRUNT_14                         (FRLG_TRAINER_OFFSET+264)
#undef  TRAINER_TEAM_ROCKET_GRUNT_15
#define TRAINER_TEAM_ROCKET_GRUNT_15                         (FRLG_TRAINER_OFFSET+265)
#undef  TRAINER_TEAM_ROCKET_GRUNT_16
#define TRAINER_TEAM_ROCKET_GRUNT_16                         (FRLG_TRAINER_OFFSET+266)
#undef  TRAINER_TEAM_ROCKET_GRUNT_17
#define TRAINER_TEAM_ROCKET_GRUNT_17                         (FRLG_TRAINER_OFFSET+267)
#undef  TRAINER_TEAM_ROCKET_GRUNT_18
#define TRAINER_TEAM_ROCKET_GRUNT_18                         (FRLG_TRAINER_OFFSET+268)
#undef  TRAINER_TEAM_ROCKET_GRUNT_19
#define TRAINER_TEAM_ROCKET_GRUNT_19                         (FRLG_TRAINER_OFFSET+269)
#undef  TRAINER_TEAM_ROCKET_GRUNT_20
#define TRAINER_TEAM_ROCKET_GRUNT_20                         (FRLG_TRAINER_OFFSET+270)
#undef  TRAINER_TEAM_ROCKET_GRUNT_21
#define TRAINER_TEAM_ROCKET_GRUNT_21                         (FRLG_TRAINER_OFFSET+271)
#undef  TRAINER_TEAM_ROCKET_GRUNT_22
#define TRAINER_TEAM_ROCKET_GRUNT_22                         (FRLG_TRAINER_OFFSET+272)
#undef  TRAINER_TEAM_ROCKET_GRUNT_23
#define TRAINER_TEAM_ROCKET_GRUNT_23                         (FRLG_TRAINER_OFFSET+273)
#undef  TRAINER_TEAM_ROCKET_GRUNT_24
#define TRAINER_TEAM_ROCKET_GRUNT_24                         (FRLG_TRAINER_OFFSET+274)
#undef  TRAINER_TEAM_ROCKET_GRUNT_25
#define TRAINER_TEAM_ROCKET_GRUNT_25                         (FRLG_TRAINER_OFFSET+275)
#undef  TRAINER_TEAM_ROCKET_GRUNT_26
#define TRAINER_TEAM_ROCKET_GRUNT_26                         (FRLG_TRAINER_OFFSET+276)
#undef  TRAINER_TEAM_ROCKET_GRUNT_27
#define TRAINER_TEAM_ROCKET_GRUNT_27                         (FRLG_TRAINER_OFFSET+277)
#undef  TRAINER_TEAM_ROCKET_GRUNT_28
#define TRAINER_TEAM_ROCKET_GRUNT_28                         (FRLG_TRAINER_OFFSET+278)
#undef  TRAINER_TEAM_ROCKET_GRUNT_29
#define TRAINER_TEAM_ROCKET_GRUNT_29                         (FRLG_TRAINER_OFFSET+279)
#undef  TRAINER_TEAM_ROCKET_GRUNT_30
#define TRAINER_TEAM_ROCKET_GRUNT_30                         (FRLG_TRAINER_OFFSET+280)
#undef  TRAINER_TEAM_ROCKET_GRUNT_31
#define TRAINER_TEAM_ROCKET_GRUNT_31                         (FRLG_TRAINER_OFFSET+281)
#undef  TRAINER_TEAM_ROCKET_GRUNT_32
#define TRAINER_TEAM_ROCKET_GRUNT_32                         (FRLG_TRAINER_OFFSET+282)
#undef  TRAINER_TEAM_ROCKET_GRUNT_33
#define TRAINER_TEAM_ROCKET_GRUNT_33                         (FRLG_TRAINER_OFFSET+283)
#undef  TRAINER_TEAM_ROCKET_GRUNT_34
#define TRAINER_TEAM_ROCKET_GRUNT_34                         (FRLG_TRAINER_OFFSET+284)
#undef  TRAINER_TEAM_ROCKET_GRUNT_35
#define TRAINER_TEAM_ROCKET_GRUNT_35                         (FRLG_TRAINER_OFFSET+285)
#undef  TRAINER_TEAM_ROCKET_GRUNT_36
#define TRAINER_TEAM_ROCKET_GRUNT_36                         (FRLG_TRAINER_OFFSET+286)
#undef  TRAINER_TEAM_ROCKET_GRUNT_37
#define TRAINER_TEAM_ROCKET_GRUNT_37                         (FRLG_TRAINER_OFFSET+287)
#undef  TRAINER_TEAM_ROCKET_GRUNT_38
#define TRAINER_TEAM_ROCKET_GRUNT_38                         (FRLG_TRAINER_OFFSET+288)
#undef  TRAINER_TEAM_ROCKET_GRUNT_39
#define TRAINER_TEAM_ROCKET_GRUNT_39                         (FRLG_TRAINER_OFFSET+289)
#undef  TRAINER_TEAM_ROCKET_GRUNT_40
#define TRAINER_TEAM_ROCKET_GRUNT_40                         (FRLG_TRAINER_OFFSET+290)
#undef  TRAINER_TEAM_ROCKET_GRUNT_41
#define TRAINER_TEAM_ROCKET_GRUNT_41                         (FRLG_TRAINER_OFFSET+291)
#undef  TRAINER_COOLTRAINER_SAMUEL
#define TRAINER_COOLTRAINER_SAMUEL                           (FRLG_TRAINER_OFFSET+292)
#undef  TRAINER_COOLTRAINER_GEORGE
#define TRAINER_COOLTRAINER_GEORGE                           (FRLG_TRAINER_OFFSET+293)
#undef  TRAINER_COOLTRAINER_COLBY
#define TRAINER_COOLTRAINER_COLBY                            (FRLG_TRAINER_OFFSET+294)
#undef  TRAINER_COOLTRAINER_PAUL
#define TRAINER_COOLTRAINER_PAUL                             (FRLG_TRAINER_OFFSET+295)
#undef  TRAINER_COOLTRAINER_ROLANDO
#define TRAINER_COOLTRAINER_ROLANDO                          (FRLG_TRAINER_OFFSET+296)
#undef  TRAINER_COOLTRAINER_GILBERT
#define TRAINER_COOLTRAINER_GILBERT                          (FRLG_TRAINER_OFFSET+297)
#undef  TRAINER_COOLTRAINER_OWEN
#define TRAINER_COOLTRAINER_OWEN                             (FRLG_TRAINER_OFFSET+298)
#undef  TRAINER_COOLTRAINER_BERKE
#define TRAINER_COOLTRAINER_BERKE                            (FRLG_TRAINER_OFFSET+299)
#undef  TRAINER_COOLTRAINER_YUJI
#define TRAINER_COOLTRAINER_YUJI                             (FRLG_TRAINER_OFFSET+300)
#undef  TRAINER_COOLTRAINER_WARREN
#define TRAINER_COOLTRAINER_WARREN                           (FRLG_TRAINER_OFFSET+301)
#undef  TRAINER_COOLTRAINER_MARY
#define TRAINER_COOLTRAINER_MARY                             (FRLG_TRAINER_OFFSET+302)
#undef  TRAINER_COOLTRAINER_CAROLINE
#define TRAINER_COOLTRAINER_CAROLINE                         (FRLG_TRAINER_OFFSET+303)
#undef  TRAINER_COOLTRAINER_ALEXA
#define TRAINER_COOLTRAINER_ALEXA                            (FRLG_TRAINER_OFFSET+304)
#undef  TRAINER_COOLTRAINER_SHANNON
#define TRAINER_COOLTRAINER_SHANNON                          (FRLG_TRAINER_OFFSET+305)
#undef  TRAINER_COOLTRAINER_NAOMI
#define TRAINER_COOLTRAINER_NAOMI                            (FRLG_TRAINER_OFFSET+306)
#undef  TRAINER_COOLTRAINER_BROOKE
#define TRAINER_COOLTRAINER_BROOKE                           (FRLG_TRAINER_OFFSET+307)
#undef  TRAINER_COOLTRAINER_AUSTINA
#define TRAINER_COOLTRAINER_AUSTINA                          (FRLG_TRAINER_OFFSET+308)
#undef  TRAINER_COOLTRAINER_JULIE
#define TRAINER_COOLTRAINER_JULIE                            (FRLG_TRAINER_OFFSET+309)
#undef  TRAINER_ELITE_FOUR_LORELEI
#define TRAINER_ELITE_FOUR_LORELEI                           (FRLG_TRAINER_OFFSET+310)
#undef  TRAINER_ELITE_FOUR_BRUNO
#define TRAINER_ELITE_FOUR_BRUNO                             (FRLG_TRAINER_OFFSET+311)
#undef  TRAINER_ELITE_FOUR_AGATHA
#define TRAINER_ELITE_FOUR_AGATHA                            (FRLG_TRAINER_OFFSET+312)
#undef  TRAINER_ELITE_FOUR_LANCE
#define TRAINER_ELITE_FOUR_LANCE                             (FRLG_TRAINER_OFFSET+313)
#undef  TRAINER_LEADER_BROCK
#define TRAINER_LEADER_BROCK                                 (FRLG_TRAINER_OFFSET+314)
#undef  TRAINER_LEADER_MISTY
#define TRAINER_LEADER_MISTY                                 (FRLG_TRAINER_OFFSET+315)
#undef  TRAINER_LEADER_LT_SURGE
#define TRAINER_LEADER_LT_SURGE                              (FRLG_TRAINER_OFFSET+316)
#undef  TRAINER_LEADER_ERIKA
#define TRAINER_LEADER_ERIKA                                 (FRLG_TRAINER_OFFSET+317)
#undef  TRAINER_LEADER_KOGA
#define TRAINER_LEADER_KOGA                                  (FRLG_TRAINER_OFFSET+318)
#undef  TRAINER_LEADER_BLAINE
#define TRAINER_LEADER_BLAINE                                (FRLG_TRAINER_OFFSET+319)
#undef  TRAINER_LEADER_SABRINA
#define TRAINER_LEADER_SABRINA                               (FRLG_TRAINER_OFFSET+320)
#undef  TRAINER_GENTLEMAN_THOMAS
#define TRAINER_GENTLEMAN_THOMAS                             (FRLG_TRAINER_OFFSET+321)
#undef  TRAINER_GENTLEMAN_ARTHUR
#define TRAINER_GENTLEMAN_ARTHUR                             (FRLG_TRAINER_OFFSET+322)
#undef  TRAINER_GENTLEMAN_TUCKER
#define TRAINER_GENTLEMAN_TUCKER                             (FRLG_TRAINER_OFFSET+323)
#undef  TRAINER_GENTLEMAN_NORTON
#define TRAINER_GENTLEMAN_NORTON                             (FRLG_TRAINER_OFFSET+324)
#undef  TRAINER_GENTLEMAN_WALTER
#define TRAINER_GENTLEMAN_WALTER                             (FRLG_TRAINER_OFFSET+325)
#undef  TRAINER_RIVAL_SS_ANNE_SQUIRTLE
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE                       (FRLG_TRAINER_OFFSET+326)
#undef  TRAINER_RIVAL_SS_ANNE_BULBASAUR
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR                      (FRLG_TRAINER_OFFSET+327)
#undef  TRAINER_RIVAL_SS_ANNE_CHARMANDER
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER                     (FRLG_TRAINER_OFFSET+328)
#undef  TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE                 (FRLG_TRAINER_OFFSET+329)
#undef  TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR                (FRLG_TRAINER_OFFSET+330)
#undef  TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER               (FRLG_TRAINER_OFFSET+331)
#undef  TRAINER_RIVAL_SILPH_SQUIRTLE
#define TRAINER_RIVAL_SILPH_SQUIRTLE                         (FRLG_TRAINER_OFFSET+332)
#undef  TRAINER_RIVAL_SILPH_BULBASAUR
#define TRAINER_RIVAL_SILPH_BULBASAUR                        (FRLG_TRAINER_OFFSET+333)
#undef  TRAINER_RIVAL_SILPH_CHARMANDER
#define TRAINER_RIVAL_SILPH_CHARMANDER                       (FRLG_TRAINER_OFFSET+334)
#undef  TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE                  (FRLG_TRAINER_OFFSET+335)
#undef  TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR                 (FRLG_TRAINER_OFFSET+336)
#undef  TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER                (FRLG_TRAINER_OFFSET+337)
#undef  TRAINER_CHAMPION_FIRST_SQUIRTLE
#define TRAINER_CHAMPION_FIRST_SQUIRTLE                      (FRLG_TRAINER_OFFSET+338)
#undef  TRAINER_CHAMPION_FIRST_BULBASAUR
#define TRAINER_CHAMPION_FIRST_BULBASAUR                     (FRLG_TRAINER_OFFSET+339)
#undef  TRAINER_CHAMPION_FIRST_CHARMANDER
#define TRAINER_CHAMPION_FIRST_CHARMANDER                    (FRLG_TRAINER_OFFSET+340)
#undef  TRAINER_CHANNELER_PATRICIA
#define TRAINER_CHANNELER_PATRICIA                           (FRLG_TRAINER_OFFSET+341)
#undef  TRAINER_CHANNELER_CARLY
#define TRAINER_CHANNELER_CARLY                              (FRLG_TRAINER_OFFSET+342)
#undef  TRAINER_CHANNELER_HOPE
#define TRAINER_CHANNELER_HOPE                               (FRLG_TRAINER_OFFSET+343)
#undef  TRAINER_CHANNELER_PAULA
#define TRAINER_CHANNELER_PAULA                              (FRLG_TRAINER_OFFSET+344)
#undef  TRAINER_CHANNELER_LAUREL
#define TRAINER_CHANNELER_LAUREL                             (FRLG_TRAINER_OFFSET+345)
#undef  TRAINER_CHANNELER_JODY
#define TRAINER_CHANNELER_JODY                               (FRLG_TRAINER_OFFSET+346)
#undef  TRAINER_CHANNELER_TAMMY
#define TRAINER_CHANNELER_TAMMY                              (FRLG_TRAINER_OFFSET+347)
#undef  TRAINER_CHANNELER_RUTH
#define TRAINER_CHANNELER_RUTH                               (FRLG_TRAINER_OFFSET+348)
#undef  TRAINER_CHANNELER_KARINA
#define TRAINER_CHANNELER_KARINA                             (FRLG_TRAINER_OFFSET+349)
#undef  TRAINER_CHANNELER_JANAE
#define TRAINER_CHANNELER_JANAE                              (FRLG_TRAINER_OFFSET+350)
#undef  TRAINER_CHANNELER_ANGELICA
#define TRAINER_CHANNELER_ANGELICA                           (FRLG_TRAINER_OFFSET+351)
#undef  TRAINER_CHANNELER_EMILIA
#define TRAINER_CHANNELER_EMILIA                             (FRLG_TRAINER_OFFSET+352)
#undef  TRAINER_CHANNELER_JENNIFER
#define TRAINER_CHANNELER_JENNIFER                           (FRLG_TRAINER_OFFSET+353)
#undef  TRAINER_CHANNELER_AMANDA
#define TRAINER_CHANNELER_AMANDA                             (FRLG_TRAINER_OFFSET+354)
#undef  TRAINER_CHANNELER_STACY
#define TRAINER_CHANNELER_STACY                              (FRLG_TRAINER_OFFSET+355)
#undef  TRAINER_CHANNELER_TASHA
#define TRAINER_CHANNELER_TASHA                              (FRLG_TRAINER_OFFSET+356)
#undef  TRAINER_HIKER_JEREMY
#define TRAINER_HIKER_JEREMY                                 (FRLG_TRAINER_OFFSET+357)
#undef  TRAINER_PICNICKER_ALMA
#define TRAINER_PICNICKER_ALMA                               (FRLG_TRAINER_OFFSET+358)
#undef  TRAINER_PICNICKER_SUSIE
#define TRAINER_PICNICKER_SUSIE                              (FRLG_TRAINER_OFFSET+359)
#undef  TRAINER_PICNICKER_VALERIE
#define TRAINER_PICNICKER_VALERIE                            (FRLG_TRAINER_OFFSET+360)
#undef  TRAINER_PICNICKER_GWEN
#define TRAINER_PICNICKER_GWEN                               (FRLG_TRAINER_OFFSET+361)
#undef  TRAINER_BIKER_VIRGIL
#define TRAINER_BIKER_VIRGIL                                 (FRLG_TRAINER_OFFSET+362)
#undef  TRAINER_CAMPER_FLINT
#define TRAINER_CAMPER_FLINT                                 (FRLG_TRAINER_OFFSET+363)
#undef  TRAINER_PICNICKER_MISSY
#define TRAINER_PICNICKER_MISSY                              (FRLG_TRAINER_OFFSET+364)
#undef  TRAINER_PICNICKER_IRENE
#define TRAINER_PICNICKER_IRENE                              (FRLG_TRAINER_OFFSET+365)
#undef  TRAINER_PICNICKER_DANA
#define TRAINER_PICNICKER_DANA                               (FRLG_TRAINER_OFFSET+366)
#undef  TRAINER_PICNICKER_ARIANA
#define TRAINER_PICNICKER_ARIANA                             (FRLG_TRAINER_OFFSET+367)
#undef  TRAINER_PICNICKER_LEAH
#define TRAINER_PICNICKER_LEAH                               (FRLG_TRAINER_OFFSET+368)
#undef  TRAINER_CAMPER_JUSTIN
#define TRAINER_CAMPER_JUSTIN                                (FRLG_TRAINER_OFFSET+369)
#undef  TRAINER_PICNICKER_YAZMIN
#define TRAINER_PICNICKER_YAZMIN                             (FRLG_TRAINER_OFFSET+370)
#undef  TRAINER_PICNICKER_KINDRA
#define TRAINER_PICNICKER_KINDRA                             (FRLG_TRAINER_OFFSET+371)
#undef  TRAINER_PICNICKER_BECKY
#define TRAINER_PICNICKER_BECKY                              (FRLG_TRAINER_OFFSET+372)
#undef  TRAINER_PICNICKER_CELIA
#define TRAINER_PICNICKER_CELIA                              (FRLG_TRAINER_OFFSET+373)
#undef  TRAINER_GENTLEMAN_BROOKS
#define TRAINER_GENTLEMAN_BROOKS                             (FRLG_TRAINER_OFFSET+374)
#undef  TRAINER_GENTLEMAN_LAMAR
#define TRAINER_GENTLEMAN_LAMAR                              (FRLG_TRAINER_OFFSET+375)
#undef  TRAINER_TWINS_ELI_ANNE
#define TRAINER_TWINS_ELI_ANNE                               (FRLG_TRAINER_OFFSET+376)
#undef  TRAINER_COOL_COUPLE_RAY_TYRA
#define TRAINER_COOL_COUPLE_RAY_TYRA                         (FRLG_TRAINER_OFFSET+377)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES
#define TRAINER_YOUNG_COUPLE_GIA_JES                         (FRLG_TRAINER_OFFSET+378)
#undef  TRAINER_TWINS_KIRI_JAN
#define TRAINER_TWINS_KIRI_JAN                               (FRLG_TRAINER_OFFSET+379)
#undef  TRAINER_CRUSH_KIN_RON_MYA
#define TRAINER_CRUSH_KIN_RON_MYA                            (FRLG_TRAINER_OFFSET+380)
#undef  TRAINER_YOUNG_COUPLE_LEA_JED
#define TRAINER_YOUNG_COUPLE_LEA_JED                         (FRLG_TRAINER_OFFSET+381)
#undef  TRAINER_SIS_AND_BRO_LIA_LUC
#define TRAINER_SIS_AND_BRO_LIA_LUC                          (FRLG_TRAINER_OFFSET+382)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN
#define TRAINER_SIS_AND_BRO_LIL_IAN                          (FRLG_TRAINER_OFFSET+383)
#undef  TRAINER_YOUNGSTER_BEN_3
#define TRAINER_YOUNGSTER_BEN_3                              (FRLG_TRAINER_OFFSET+384)
#undef  TRAINER_YOUNGSTER_BEN_4
#define TRAINER_YOUNGSTER_BEN_4                              (FRLG_TRAINER_OFFSET+385)
#undef  TRAINER_YOUNGSTER_CHAD_2
#define TRAINER_YOUNGSTER_CHAD_2                             (FRLG_TRAINER_OFFSET+386)
#undef  TRAINER_LASS_RELI_2
#define TRAINER_LASS_RELI_2                                  (FRLG_TRAINER_OFFSET+387)
#undef  TRAINER_LASS_RELI_3
#define TRAINER_LASS_RELI_3                                  (FRLG_TRAINER_OFFSET+388)
#undef  TRAINER_YOUNGSTER_TIMMY_2
#define TRAINER_YOUNGSTER_TIMMY_2                            (FRLG_TRAINER_OFFSET+389)
#undef  TRAINER_YOUNGSTER_TIMMY_3
#define TRAINER_YOUNGSTER_TIMMY_3                            (FRLG_TRAINER_OFFSET+390)
#undef  TRAINER_YOUNGSTER_TIMMY_4
#define TRAINER_YOUNGSTER_TIMMY_4                            (FRLG_TRAINER_OFFSET+391)
#undef  TRAINER_YOUNGSTER_CHAD_3
#define TRAINER_YOUNGSTER_CHAD_3                             (FRLG_TRAINER_OFFSET+392)
#undef  TRAINER_LASS_JANICE_2
#define TRAINER_LASS_JANICE_2                                (FRLG_TRAINER_OFFSET+393)
#undef  TRAINER_LASS_JANICE_3
#define TRAINER_LASS_JANICE_3                                (FRLG_TRAINER_OFFSET+394)
#undef  TRAINER_YOUNGSTER_CHAD_4
#define TRAINER_YOUNGSTER_CHAD_4                             (FRLG_TRAINER_OFFSET+395)
#undef  TRAINER_HIKER_FRANKLIN_2
#define TRAINER_HIKER_FRANKLIN_2                             (FRLG_TRAINER_OFFSET+396)
#undef  TRAINER_PKMN_PROF_PROF_OAK
#define TRAINER_PKMN_PROF_PROF_OAK                           (FRLG_TRAINER_OFFSET+397)
#undef  TRAINER_TEAM_ROCKET_GRUNT_42
#define TRAINER_TEAM_ROCKET_GRUNT_42                         (FRLG_TRAINER_OFFSET+398)
#undef  TRAINER_PSYCHIC_JACLYN
#define TRAINER_PSYCHIC_JACLYN                               (FRLG_TRAINER_OFFSET+399)
#undef  TRAINER_CRUSH_GIRL_SHARON
#define TRAINER_CRUSH_GIRL_SHARON                            (FRLG_TRAINER_OFFSET+400)
#undef  TRAINER_TUBER_AMIRA
#define TRAINER_TUBER_AMIRA                                  (FRLG_TRAINER_OFFSET+401)
#undef  TRAINER_PKMN_BREEDER_ALIZE
#define TRAINER_PKMN_BREEDER_ALIZE                           (FRLG_TRAINER_OFFSET+402)
#undef  TRAINER_PKMN_RANGER_NICOLAS
#define TRAINER_PKMN_RANGER_NICOLAS                          (FRLG_TRAINER_OFFSET+403)
#undef  TRAINER_PKMN_RANGER_MADELINE
#define TRAINER_PKMN_RANGER_MADELINE                         (FRLG_TRAINER_OFFSET+404)
#undef  TRAINER_AROMA_LADY_NIKKI
#define TRAINER_AROMA_LADY_NIKKI                             (FRLG_TRAINER_OFFSET+405)
#undef  TRAINER_RUIN_MANIAC_STANLY
#define TRAINER_RUIN_MANIAC_STANLY                           (FRLG_TRAINER_OFFSET+406)
#undef  TRAINER_LADY_JACKI
#define TRAINER_LADY_JACKI                                   (FRLG_TRAINER_OFFSET+407)
#undef  TRAINER_PAINTER_DAISY
#define TRAINER_PAINTER_DAISY                                (FRLG_TRAINER_OFFSET+408)
#undef  TRAINER_BIKER_GOON
#define TRAINER_BIKER_GOON                                   (FRLG_TRAINER_OFFSET+409)
#undef  TRAINER_BIKER_GOON_2
#define TRAINER_BIKER_GOON_2                                 (FRLG_TRAINER_OFFSET+410)
#undef  TRAINER_BIKER_GOON_3
#define TRAINER_BIKER_GOON_3                                 (FRLG_TRAINER_OFFSET+411)
#undef  TRAINER_BUG_CATCHER_ANTHONY
#define TRAINER_BUG_CATCHER_ANTHONY                          (FRLG_TRAINER_OFFSET+412)
#undef  TRAINER_BUG_CATCHER_CHARLIE
#define TRAINER_BUG_CATCHER_CHARLIE                          (FRLG_TRAINER_OFFSET+413)
#undef  TRAINER_TWINS_ELI_ANNE_2
#define TRAINER_TWINS_ELI_ANNE_2                             (FRLG_TRAINER_OFFSET+414)
#undef  TRAINER_YOUNGSTER_JOHNSON
#define TRAINER_YOUNGSTER_JOHNSON                            (FRLG_TRAINER_OFFSET+415)
#undef  TRAINER_BIKER_RICARDO
#define TRAINER_BIKER_RICARDO                                (FRLG_TRAINER_OFFSET+416)
#undef  TRAINER_BIKER_JAREN
#define TRAINER_BIKER_JAREN                                  (FRLG_TRAINER_OFFSET+417)
#undef  TRAINER_TEAM_ROCKET_GRUNT_43
#define TRAINER_TEAM_ROCKET_GRUNT_43                         (FRLG_TRAINER_OFFSET+418)
#undef  TRAINER_TEAM_ROCKET_GRUNT_44
#define TRAINER_TEAM_ROCKET_GRUNT_44                         (FRLG_TRAINER_OFFSET+419)
#undef  TRAINER_TEAM_ROCKET_GRUNT_45
#define TRAINER_TEAM_ROCKET_GRUNT_45                         (FRLG_TRAINER_OFFSET+420)
#undef  TRAINER_TEAM_ROCKET_GRUNT_46
#define TRAINER_TEAM_ROCKET_GRUNT_46                         (FRLG_TRAINER_OFFSET+421)
#undef  TRAINER_TEAM_ROCKET_GRUNT_47
#define TRAINER_TEAM_ROCKET_GRUNT_47                         (FRLG_TRAINER_OFFSET+422)
#undef  TRAINER_TEAM_ROCKET_GRUNT_48
#define TRAINER_TEAM_ROCKET_GRUNT_48                         (FRLG_TRAINER_OFFSET+423)
#undef  TRAINER_TEAM_ROCKET_ADMIN
#define TRAINER_TEAM_ROCKET_ADMIN                            (FRLG_TRAINER_OFFSET+424)
#undef  TRAINER_TEAM_ROCKET_ADMIN_2
#define TRAINER_TEAM_ROCKET_ADMIN_2                          (FRLG_TRAINER_OFFSET+425)
#undef  TRAINER_SCIENTIST_GIDEON
#define TRAINER_SCIENTIST_GIDEON                             (FRLG_TRAINER_OFFSET+426)
#undef  TRAINER_SWIMMER_FEMALE_AMARA
#define TRAINER_SWIMMER_FEMALE_AMARA                         (FRLG_TRAINER_OFFSET+427)
#undef  TRAINER_SWIMMER_FEMALE_MARIA
#define TRAINER_SWIMMER_FEMALE_MARIA                         (FRLG_TRAINER_OFFSET+428)
#undef  TRAINER_SWIMMER_FEMALE_ABIGAIL
#define TRAINER_SWIMMER_FEMALE_ABIGAIL                       (FRLG_TRAINER_OFFSET+429)
#undef  TRAINER_SWIMMER_MALE_FINN
#define TRAINER_SWIMMER_MALE_FINN                            (FRLG_TRAINER_OFFSET+430)
#undef  TRAINER_SWIMMER_MALE_GARRETT
#define TRAINER_SWIMMER_MALE_GARRETT                         (FRLG_TRAINER_OFFSET+431)
#undef  TRAINER_FISHERMAN_TOMMY
#define TRAINER_FISHERMAN_TOMMY                              (FRLG_TRAINER_OFFSET+432)
#undef  TRAINER_CRUSH_GIRL_TANYA
#define TRAINER_CRUSH_GIRL_TANYA                             (FRLG_TRAINER_OFFSET+433)
#undef  TRAINER_BLACK_BELT_SHEA
#define TRAINER_BLACK_BELT_SHEA                              (FRLG_TRAINER_OFFSET+434)
#undef  TRAINER_BLACK_BELT_HUGH
#define TRAINER_BLACK_BELT_HUGH                              (FRLG_TRAINER_OFFSET+435)
#undef  TRAINER_CAMPER_BRYCE
#define TRAINER_CAMPER_BRYCE                                 (FRLG_TRAINER_OFFSET+436)
#undef  TRAINER_PICNICKER_CLAIRE
#define TRAINER_PICNICKER_CLAIRE                             (FRLG_TRAINER_OFFSET+437)
#undef  TRAINER_CRUSH_KIN_MIK_KIA
#define TRAINER_CRUSH_KIN_MIK_KIA                            (FRLG_TRAINER_OFFSET+438)
#undef  TRAINER_AROMA_LADY_VIOLET
#define TRAINER_AROMA_LADY_VIOLET                            (FRLG_TRAINER_OFFSET+439)
#undef  TRAINER_TUBER_ALEXIS
#define TRAINER_TUBER_ALEXIS                                 (FRLG_TRAINER_OFFSET+440)
#undef  TRAINER_TWINS_JOY_MEG
#define TRAINER_TWINS_JOY_MEG                                (FRLG_TRAINER_OFFSET+441)
#undef  TRAINER_SWIMMER_FEMALE_TISHA
#define TRAINER_SWIMMER_FEMALE_TISHA                         (FRLG_TRAINER_OFFSET+442)
#undef  TRAINER_PAINTER_CELINA
#define TRAINER_PAINTER_CELINA                               (FRLG_TRAINER_OFFSET+443)
#undef  TRAINER_PAINTER_RAYNA
#define TRAINER_PAINTER_RAYNA                                (FRLG_TRAINER_OFFSET+444)
#undef  TRAINER_LADY_GILLIAN
#define TRAINER_LADY_GILLIAN                                 (FRLG_TRAINER_OFFSET+445)
#undef  TRAINER_YOUNGSTER_DESTIN
#define TRAINER_YOUNGSTER_DESTIN                             (FRLG_TRAINER_OFFSET+446)
#undef  TRAINER_SWIMMER_MALE_TOBY
#define TRAINER_SWIMMER_MALE_TOBY                            (FRLG_TRAINER_OFFSET+447)
#undef  TRAINER_TEAM_ROCKET_GRUNT_49
#define TRAINER_TEAM_ROCKET_GRUNT_49                         (FRLG_TRAINER_OFFSET+448)
#undef  TRAINER_TEAM_ROCKET_GRUNT_50
#define TRAINER_TEAM_ROCKET_GRUNT_50                         (FRLG_TRAINER_OFFSET+449)
#undef  TRAINER_TEAM_ROCKET_GRUNT_51
#define TRAINER_TEAM_ROCKET_GRUNT_51                         (FRLG_TRAINER_OFFSET+450)
#undef  TRAINER_BIRD_KEEPER_MILO
#define TRAINER_BIRD_KEEPER_MILO                             (FRLG_TRAINER_OFFSET+451)
#undef  TRAINER_BIRD_KEEPER_CHAZ
#define TRAINER_BIRD_KEEPER_CHAZ                             (FRLG_TRAINER_OFFSET+452)
#undef  TRAINER_BIRD_KEEPER_HAROLD
#define TRAINER_BIRD_KEEPER_HAROLD                           (FRLG_TRAINER_OFFSET+453)
#undef  TRAINER_FISHERMAN_TYLOR
#define TRAINER_FISHERMAN_TYLOR                              (FRLG_TRAINER_OFFSET+454)
#undef  TRAINER_SWIMMER_MALE_MYMO
#define TRAINER_SWIMMER_MALE_MYMO                            (FRLG_TRAINER_OFFSET+455)
#undef  TRAINER_SWIMMER_FEMALE_NICOLE
#define TRAINER_SWIMMER_FEMALE_NICOLE                        (FRLG_TRAINER_OFFSET+456)
#undef  TRAINER_SIS_AND_BRO_AVA_GEB
#define TRAINER_SIS_AND_BRO_AVA_GEB                          (FRLG_TRAINER_OFFSET+457)
#undef  TRAINER_AROMA_LADY_ROSE
#define TRAINER_AROMA_LADY_ROSE                              (FRLG_TRAINER_OFFSET+458)
#undef  TRAINER_SWIMMER_MALE_SAMIR
#define TRAINER_SWIMMER_MALE_SAMIR                           (FRLG_TRAINER_OFFSET+459)
#undef  TRAINER_SWIMMER_FEMALE_DENISE
#define TRAINER_SWIMMER_FEMALE_DENISE                        (FRLG_TRAINER_OFFSET+460)
#undef  TRAINER_TWINS_MIU_MIA
#define TRAINER_TWINS_MIU_MIA                                (FRLG_TRAINER_OFFSET+461)
#undef  TRAINER_HIKER_EARL
#define TRAINER_HIKER_EARL                                   (FRLG_TRAINER_OFFSET+462)
#undef  TRAINER_RUIN_MANIAC_FOSTER
#define TRAINER_RUIN_MANIAC_FOSTER                           (FRLG_TRAINER_OFFSET+463)
#undef  TRAINER_RUIN_MANIAC_LARRY
#define TRAINER_RUIN_MANIAC_LARRY                            (FRLG_TRAINER_OFFSET+464)
#undef  TRAINER_HIKER_DARYL
#define TRAINER_HIKER_DARYL                                  (FRLG_TRAINER_OFFSET+465)
#undef  TRAINER_POKEMANIAC_HECTOR
#define TRAINER_POKEMANIAC_HECTOR                            (FRLG_TRAINER_OFFSET+466)
#undef  TRAINER_PSYCHIC_DARIO
#define TRAINER_PSYCHIC_DARIO                                (FRLG_TRAINER_OFFSET+467)
#undef  TRAINER_PSYCHIC_RODETTE
#define TRAINER_PSYCHIC_RODETTE                              (FRLG_TRAINER_OFFSET+468)
#undef  TRAINER_AROMA_LADY_MIAH
#define TRAINER_AROMA_LADY_MIAH                              (FRLG_TRAINER_OFFSET+469)
#undef  TRAINER_YOUNG_COUPLE_EVE_JON
#define TRAINER_YOUNG_COUPLE_EVE_JON                         (FRLG_TRAINER_OFFSET+470)
#undef  TRAINER_JUGGLER_MASON
#define TRAINER_JUGGLER_MASON                                (FRLG_TRAINER_OFFSET+471)
#undef  TRAINER_CRUSH_GIRL_CYNDY
#define TRAINER_CRUSH_GIRL_CYNDY                             (FRLG_TRAINER_OFFSET+472)
#undef  TRAINER_CRUSH_GIRL_JOCELYN
#define TRAINER_CRUSH_GIRL_JOCELYN                           (FRLG_TRAINER_OFFSET+473)
#undef  TRAINER_TAMER_EVAN
#define TRAINER_TAMER_EVAN                                   (FRLG_TRAINER_OFFSET+474)
#undef  TRAINER_POKEMANIAC_MARK_2
#define TRAINER_POKEMANIAC_MARK_2                            (FRLG_TRAINER_OFFSET+475)
#undef  TRAINER_PKMN_RANGER_LOGAN
#define TRAINER_PKMN_RANGER_LOGAN                            (FRLG_TRAINER_OFFSET+476)
#undef  TRAINER_PKMN_RANGER_JACKSON
#define TRAINER_PKMN_RANGER_JACKSON                          (FRLG_TRAINER_OFFSET+477)
#undef  TRAINER_PKMN_RANGER_BETH
#define TRAINER_PKMN_RANGER_BETH                             (FRLG_TRAINER_OFFSET+478)
#undef  TRAINER_PKMN_RANGER_KATELYN
#define TRAINER_PKMN_RANGER_KATELYN                          (FRLG_TRAINER_OFFSET+479)
#undef  TRAINER_COOLTRAINER_LEROY
#define TRAINER_COOLTRAINER_LEROY                            (FRLG_TRAINER_OFFSET+480)
#undef  TRAINER_COOLTRAINER_MICHELLE
#define TRAINER_COOLTRAINER_MICHELLE                         (FRLG_TRAINER_OFFSET+481)
#undef  TRAINER_COOL_COUPLE_LEX_NYA
#define TRAINER_COOL_COUPLE_LEX_NYA                          (FRLG_TRAINER_OFFSET+482)
#undef  TRAINER_RUIN_MANIAC_BRANDON
#define TRAINER_RUIN_MANIAC_BRANDON                          (FRLG_TRAINER_OFFSET+483)
#undef  TRAINER_RUIN_MANIAC_BENJAMIN
#define TRAINER_RUIN_MANIAC_BENJAMIN                         (FRLG_TRAINER_OFFSET+484)
#undef  TRAINER_PAINTER_EDNA
#define TRAINER_PAINTER_EDNA                                 (FRLG_TRAINER_OFFSET+485)
#undef  TRAINER_GENTLEMAN_CLIFFORD
#define TRAINER_GENTLEMAN_CLIFFORD                           (FRLG_TRAINER_OFFSET+486)
#undef  TRAINER_LADY_SELPHY
#define TRAINER_LADY_SELPHY                                  (FRLG_TRAINER_OFFSET+487)
#undef  TRAINER_RUIN_MANIAC_LAWSON
#define TRAINER_RUIN_MANIAC_LAWSON                           (FRLG_TRAINER_OFFSET+488)
#undef  TRAINER_PSYCHIC_LAURA
#define TRAINER_PSYCHIC_LAURA                                (FRLG_TRAINER_OFFSET+489)
#undef  TRAINER_PKMN_BREEDER_BETHANY
#define TRAINER_PKMN_BREEDER_BETHANY                         (FRLG_TRAINER_OFFSET+490)
#undef  TRAINER_PKMN_BREEDER_ALLISON
#define TRAINER_PKMN_BREEDER_ALLISON                         (FRLG_TRAINER_OFFSET+491)
#undef  TRAINER_BUG_CATCHER_GARRET
#define TRAINER_BUG_CATCHER_GARRET                           (FRLG_TRAINER_OFFSET+492)
#undef  TRAINER_BUG_CATCHER_JONAH
#define TRAINER_BUG_CATCHER_JONAH                            (FRLG_TRAINER_OFFSET+493)
#undef  TRAINER_BUG_CATCHER_VANCE
#define TRAINER_BUG_CATCHER_VANCE                            (FRLG_TRAINER_OFFSET+494)
#undef  TRAINER_YOUNGSTER_NASH
#define TRAINER_YOUNGSTER_NASH                               (FRLG_TRAINER_OFFSET+495)
#undef  TRAINER_YOUNGSTER_CORDELL
#define TRAINER_YOUNGSTER_CORDELL                            (FRLG_TRAINER_OFFSET+496)
#undef  TRAINER_LASS_DALIA
#define TRAINER_LASS_DALIA                                   (FRLG_TRAINER_OFFSET+497)
#undef  TRAINER_LASS_JOANA
#define TRAINER_LASS_JOANA                                   (FRLG_TRAINER_OFFSET+498)
#undef  TRAINER_CAMPER_RILEY
#define TRAINER_CAMPER_RILEY                                 (FRLG_TRAINER_OFFSET+499)
#undef  TRAINER_PICNICKER_MARCY
#define TRAINER_PICNICKER_MARCY                              (FRLG_TRAINER_OFFSET+500)
#undef  TRAINER_RUIN_MANIAC_LAYTON
#define TRAINER_RUIN_MANIAC_LAYTON                           (FRLG_TRAINER_OFFSET+501)
#undef  TRAINER_PICNICKER_KELSEY_2
#define TRAINER_PICNICKER_KELSEY_2                           (FRLG_TRAINER_OFFSET+502)
#undef  TRAINER_PICNICKER_KELSEY_3
#define TRAINER_PICNICKER_KELSEY_3                           (FRLG_TRAINER_OFFSET+503)
#undef  TRAINER_PICNICKER_KELSEY_4
#define TRAINER_PICNICKER_KELSEY_4                           (FRLG_TRAINER_OFFSET+504)
#undef  TRAINER_CAMPER_RICKY_2
#define TRAINER_CAMPER_RICKY_2                               (FRLG_TRAINER_OFFSET+505)
#undef  TRAINER_CAMPER_RICKY_3
#define TRAINER_CAMPER_RICKY_3                               (FRLG_TRAINER_OFFSET+506)
#undef  TRAINER_CAMPER_RICKY_4
#define TRAINER_CAMPER_RICKY_4                               (FRLG_TRAINER_OFFSET+507)
#undef  TRAINER_CAMPER_JEFF_2
#define TRAINER_CAMPER_JEFF_2                                (FRLG_TRAINER_OFFSET+508)
#undef  TRAINER_CAMPER_JEFF_3
#define TRAINER_CAMPER_JEFF_3                                (FRLG_TRAINER_OFFSET+509)
#undef  TRAINER_CAMPER_JEFF_4
#define TRAINER_CAMPER_JEFF_4                                (FRLG_TRAINER_OFFSET+510)
#undef  TRAINER_PICNICKER_ISABELLE_2
#define TRAINER_PICNICKER_ISABELLE_2                         (FRLG_TRAINER_OFFSET+511)
#undef  TRAINER_PICNICKER_ISABELLE_3
#define TRAINER_PICNICKER_ISABELLE_3                         (FRLG_TRAINER_OFFSET+512)
#undef  TRAINER_PICNICKER_ISABELLE_4
#define TRAINER_PICNICKER_ISABELLE_4                         (FRLG_TRAINER_OFFSET+513)
#undef  TRAINER_YOUNGSTER_YASU_2
#define TRAINER_YOUNGSTER_YASU_2                             (FRLG_TRAINER_OFFSET+514)
#undef  TRAINER_YOUNGSTER_YASU_3
#define TRAINER_YOUNGSTER_YASU_3                             (FRLG_TRAINER_OFFSET+515)
#undef  TRAINER_ENGINEER_BERNIE_2
#define TRAINER_ENGINEER_BERNIE_2                            (FRLG_TRAINER_OFFSET+516)
#undef  TRAINER_GAMER_DARIAN_2
#define TRAINER_GAMER_DARIAN_2                               (FRLG_TRAINER_OFFSET+517)
#undef  TRAINER_CAMPER_CHRIS_2
#define TRAINER_CAMPER_CHRIS_2                               (FRLG_TRAINER_OFFSET+518)
#undef  TRAINER_CAMPER_CHRIS_3
#define TRAINER_CAMPER_CHRIS_3                               (FRLG_TRAINER_OFFSET+519)
#undef  TRAINER_CAMPER_CHRIS_4
#define TRAINER_CAMPER_CHRIS_4                               (FRLG_TRAINER_OFFSET+520)
#undef  TRAINER_PICNICKER_ALICIA_2
#define TRAINER_PICNICKER_ALICIA_2                           (FRLG_TRAINER_OFFSET+521)
#undef  TRAINER_PICNICKER_ALICIA_3
#define TRAINER_PICNICKER_ALICIA_3                           (FRLG_TRAINER_OFFSET+522)
#undef  TRAINER_PICNICKER_ALICIA_4
#define TRAINER_PICNICKER_ALICIA_4                           (FRLG_TRAINER_OFFSET+523)
#undef  TRAINER_HIKER_JEREMY_2
#define TRAINER_HIKER_JEREMY_2                               (FRLG_TRAINER_OFFSET+524)
#undef  TRAINER_POKEMANIAC_MARK_3
#define TRAINER_POKEMANIAC_MARK_3                            (FRLG_TRAINER_OFFSET+525)
#undef  TRAINER_POKEMANIAC_HERMAN_2
#define TRAINER_POKEMANIAC_HERMAN_2                          (FRLG_TRAINER_OFFSET+526)
#undef  TRAINER_POKEMANIAC_HERMAN_3
#define TRAINER_POKEMANIAC_HERMAN_3                          (FRLG_TRAINER_OFFSET+527)
#undef  TRAINER_HIKER_TRENT_2
#define TRAINER_HIKER_TRENT_2                                (FRLG_TRAINER_OFFSET+528)
#undef  TRAINER_LASS_MEGAN_2
#define TRAINER_LASS_MEGAN_2                                 (FRLG_TRAINER_OFFSET+529)
#undef  TRAINER_LASS_MEGAN_3
#define TRAINER_LASS_MEGAN_3                                 (FRLG_TRAINER_OFFSET+530)
#undef  TRAINER_SUPER_NERD_GLENN_2
#define TRAINER_SUPER_NERD_GLENN_2                           (FRLG_TRAINER_OFFSET+531)
#undef  TRAINER_GAMER_RICH_2
#define TRAINER_GAMER_RICH_2                                 (FRLG_TRAINER_OFFSET+532)
#undef  TRAINER_BIKER_JAREN_2
#define TRAINER_BIKER_JAREN_2                                (FRLG_TRAINER_OFFSET+533)
#undef  TRAINER_FISHERMAN_ELLIOT_2
#define TRAINER_FISHERMAN_ELLIOT_2                           (FRLG_TRAINER_OFFSET+534)
#undef  TRAINER_ROCKER_LUCA_2
#define TRAINER_ROCKER_LUCA_2                                (FRLG_TRAINER_OFFSET+535)
#undef  TRAINER_BEAUTY_SHEILA_2
#define TRAINER_BEAUTY_SHEILA_2                              (FRLG_TRAINER_OFFSET+536)
#undef  TRAINER_BIRD_KEEPER_ROBERT_2
#define TRAINER_BIRD_KEEPER_ROBERT_2                         (FRLG_TRAINER_OFFSET+537)
#undef  TRAINER_BIRD_KEEPER_ROBERT_3
#define TRAINER_BIRD_KEEPER_ROBERT_3                         (FRLG_TRAINER_OFFSET+538)
#undef  TRAINER_PICNICKER_SUSIE_2
#define TRAINER_PICNICKER_SUSIE_2                            (FRLG_TRAINER_OFFSET+539)
#undef  TRAINER_PICNICKER_SUSIE_3
#define TRAINER_PICNICKER_SUSIE_3                            (FRLG_TRAINER_OFFSET+540)
#undef  TRAINER_PICNICKER_SUSIE_4
#define TRAINER_PICNICKER_SUSIE_4                            (FRLG_TRAINER_OFFSET+541)
#undef  TRAINER_BIKER_LUKAS_2
#define TRAINER_BIKER_LUKAS_2                                (FRLG_TRAINER_OFFSET+542)
#undef  TRAINER_BIRD_KEEPER_BENNY_2
#define TRAINER_BIRD_KEEPER_BENNY_2                          (FRLG_TRAINER_OFFSET+543)
#undef  TRAINER_BIRD_KEEPER_BENNY_3
#define TRAINER_BIRD_KEEPER_BENNY_3                          (FRLG_TRAINER_OFFSET+544)
#undef  TRAINER_BIRD_KEEPER_MARLON_2
#define TRAINER_BIRD_KEEPER_MARLON_2                         (FRLG_TRAINER_OFFSET+545)
#undef  TRAINER_BIRD_KEEPER_MARLON_3
#define TRAINER_BIRD_KEEPER_MARLON_3                         (FRLG_TRAINER_OFFSET+546)
#undef  TRAINER_BEAUTY_GRACE_2
#define TRAINER_BEAUTY_GRACE_2                               (FRLG_TRAINER_OFFSET+547)
#undef  TRAINER_BIRD_KEEPER_CHESTER_2
#define TRAINER_BIRD_KEEPER_CHESTER_2                        (FRLG_TRAINER_OFFSET+548)
#undef  TRAINER_BIRD_KEEPER_CHESTER_3
#define TRAINER_BIRD_KEEPER_CHESTER_3                        (FRLG_TRAINER_OFFSET+549)
#undef  TRAINER_PICNICKER_BECKY_2
#define TRAINER_PICNICKER_BECKY_2                            (FRLG_TRAINER_OFFSET+550)
#undef  TRAINER_PICNICKER_BECKY_3
#define TRAINER_PICNICKER_BECKY_3                            (FRLG_TRAINER_OFFSET+551)
#undef  TRAINER_PICNICKER_BECKY_4
#define TRAINER_PICNICKER_BECKY_4                            (FRLG_TRAINER_OFFSET+552)
#undef  TRAINER_CRUSH_KIN_RON_MYA_2
#define TRAINER_CRUSH_KIN_RON_MYA_2                          (FRLG_TRAINER_OFFSET+553)
#undef  TRAINER_CRUSH_KIN_RON_MYA_3
#define TRAINER_CRUSH_KIN_RON_MYA_3                          (FRLG_TRAINER_OFFSET+554)
#undef  TRAINER_CRUSH_KIN_RON_MYA_4
#define TRAINER_CRUSH_KIN_RON_MYA_4                          (FRLG_TRAINER_OFFSET+555)
#undef  TRAINER_BIKER_RUBEN_2
#define TRAINER_BIKER_RUBEN_2                                (FRLG_TRAINER_OFFSET+556)
#undef  TRAINER_CUE_BALL_CAMRON_2
#define TRAINER_CUE_BALL_CAMRON_2                            (FRLG_TRAINER_OFFSET+557)
#undef  TRAINER_BIKER_JAXON_2
#define TRAINER_BIKER_JAXON_2                                (FRLG_TRAINER_OFFSET+558)
#undef  TRAINER_CUE_BALL_ISAIAH_2
#define TRAINER_CUE_BALL_ISAIAH_2                            (FRLG_TRAINER_OFFSET+559)
#undef  TRAINER_CUE_BALL_COREY_2
#define TRAINER_CUE_BALL_COREY_2                             (FRLG_TRAINER_OFFSET+560)
#undef  TRAINER_BIRD_KEEPER_JACOB_2
#define TRAINER_BIRD_KEEPER_JACOB_2                          (FRLG_TRAINER_OFFSET+561)
#undef  TRAINER_BIRD_KEEPER_JACOB_3
#define TRAINER_BIRD_KEEPER_JACOB_3                          (FRLG_TRAINER_OFFSET+562)
#undef  TRAINER_SWIMMER_FEMALE_ALICE_2
#define TRAINER_SWIMMER_FEMALE_ALICE_2                       (FRLG_TRAINER_OFFSET+563)
#undef  TRAINER_SWIMMER_MALE_DARRIN_2
#define TRAINER_SWIMMER_MALE_DARRIN_2                        (FRLG_TRAINER_OFFSET+564)
#undef  TRAINER_PICNICKER_MISSY_2
#define TRAINER_PICNICKER_MISSY_2                            (FRLG_TRAINER_OFFSET+565)
#undef  TRAINER_PICNICKER_MISSY_3
#define TRAINER_PICNICKER_MISSY_3                            (FRLG_TRAINER_OFFSET+566)
#undef  TRAINER_FISHERMAN_WADE_2
#define TRAINER_FISHERMAN_WADE_2                             (FRLG_TRAINER_OFFSET+567)
#undef  TRAINER_SWIMMER_MALE_JACK_2
#define TRAINER_SWIMMER_MALE_JACK_2                          (FRLG_TRAINER_OFFSET+568)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_2
#define TRAINER_SIS_AND_BRO_LIL_IAN_2                        (FRLG_TRAINER_OFFSET+569)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_3
#define TRAINER_SIS_AND_BRO_LIL_IAN_3                        (FRLG_TRAINER_OFFSET+570)
#undef  TRAINER_SWIMMER_MALE_FINN_2
#define TRAINER_SWIMMER_MALE_FINN_2                          (FRLG_TRAINER_OFFSET+571)
#undef  TRAINER_CRUSH_GIRL_SHARON_2
#define TRAINER_CRUSH_GIRL_SHARON_2                          (FRLG_TRAINER_OFFSET+572)
#undef  TRAINER_CRUSH_GIRL_SHARON_3
#define TRAINER_CRUSH_GIRL_SHARON_3                          (FRLG_TRAINER_OFFSET+573)
#undef  TRAINER_CRUSH_GIRL_TANYA_2
#define TRAINER_CRUSH_GIRL_TANYA_2                           (FRLG_TRAINER_OFFSET+574)
#undef  TRAINER_CRUSH_GIRL_TANYA_3
#define TRAINER_CRUSH_GIRL_TANYA_3                           (FRLG_TRAINER_OFFSET+575)
#undef  TRAINER_BLACK_BELT_SHEA_2
#define TRAINER_BLACK_BELT_SHEA_2                            (FRLG_TRAINER_OFFSET+576)
#undef  TRAINER_BLACK_BELT_SHEA_3
#define TRAINER_BLACK_BELT_SHEA_3                            (FRLG_TRAINER_OFFSET+577)
#undef  TRAINER_BLACK_BELT_HUGH_2
#define TRAINER_BLACK_BELT_HUGH_2                            (FRLG_TRAINER_OFFSET+578)
#undef  TRAINER_BLACK_BELT_HUGH_3
#define TRAINER_BLACK_BELT_HUGH_3                            (FRLG_TRAINER_OFFSET+579)
#undef  TRAINER_CRUSH_KIN_MIK_KIA_2
#define TRAINER_CRUSH_KIN_MIK_KIA_2                          (FRLG_TRAINER_OFFSET+580)
#undef  TRAINER_CRUSH_KIN_MIK_KIA_3
#define TRAINER_CRUSH_KIN_MIK_KIA_3                          (FRLG_TRAINER_OFFSET+581)
#undef  TRAINER_TUBER_AMIRA_2
#define TRAINER_TUBER_AMIRA_2                                (FRLG_TRAINER_OFFSET+582)
#undef  TRAINER_TWINS_JOY_MEG_2
#define TRAINER_TWINS_JOY_MEG_2                              (FRLG_TRAINER_OFFSET+583)
#undef  TRAINER_PAINTER_RAYNA_2
#define TRAINER_PAINTER_RAYNA_2                              (FRLG_TRAINER_OFFSET+584)
#undef  TRAINER_YOUNGSTER_DESTIN_2
#define TRAINER_YOUNGSTER_DESTIN_2                           (FRLG_TRAINER_OFFSET+585)
#undef  TRAINER_PKMN_BREEDER_ALIZE_2
#define TRAINER_PKMN_BREEDER_ALIZE_2                         (FRLG_TRAINER_OFFSET+586)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_2
#define TRAINER_YOUNG_COUPLE_GIA_JES_2                       (FRLG_TRAINER_OFFSET+587)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_3
#define TRAINER_YOUNG_COUPLE_GIA_JES_3                       (FRLG_TRAINER_OFFSET+588)
#undef  TRAINER_BIRD_KEEPER_MILO_2
#define TRAINER_BIRD_KEEPER_MILO_2                           (FRLG_TRAINER_OFFSET+589)
#undef  TRAINER_BIRD_KEEPER_CHAZ_2
#define TRAINER_BIRD_KEEPER_CHAZ_2                           (FRLG_TRAINER_OFFSET+590)
#undef  TRAINER_BIRD_KEEPER_HAROLD_2
#define TRAINER_BIRD_KEEPER_HAROLD_2                         (FRLG_TRAINER_OFFSET+591)
#undef  TRAINER_SWIMMER_FEMALE_NICOLE_2
#define TRAINER_SWIMMER_FEMALE_NICOLE_2                      (FRLG_TRAINER_OFFSET+592)
#undef  TRAINER_PSYCHIC_JACLYN_2
#define TRAINER_PSYCHIC_JACLYN_2                             (FRLG_TRAINER_OFFSET+593)
#undef  TRAINER_SWIMMER_MALE_SAMIR_2
#define TRAINER_SWIMMER_MALE_SAMIR_2                         (FRLG_TRAINER_OFFSET+594)
#undef  TRAINER_HIKER_EARL_2
#define TRAINER_HIKER_EARL_2                                 (FRLG_TRAINER_OFFSET+595)
#undef  TRAINER_RUIN_MANIAC_LARRY_2
#define TRAINER_RUIN_MANIAC_LARRY_2                          (FRLG_TRAINER_OFFSET+596)
#undef  TRAINER_POKEMANIAC_HECTOR_2
#define TRAINER_POKEMANIAC_HECTOR_2                          (FRLG_TRAINER_OFFSET+597)
#undef  TRAINER_PSYCHIC_DARIO_2
#define TRAINER_PSYCHIC_DARIO_2                              (FRLG_TRAINER_OFFSET+598)
#undef  TRAINER_PSYCHIC_RODETTE_2
#define TRAINER_PSYCHIC_RODETTE_2                            (FRLG_TRAINER_OFFSET+599)
#undef  TRAINER_JUGGLER_MASON_2
#define TRAINER_JUGGLER_MASON_2                              (FRLG_TRAINER_OFFSET+600)
#undef  TRAINER_PKMN_RANGER_NICOLAS_2
#define TRAINER_PKMN_RANGER_NICOLAS_2                        (FRLG_TRAINER_OFFSET+601)
#undef  TRAINER_PKMN_RANGER_MADELINE_2
#define TRAINER_PKMN_RANGER_MADELINE_2                       (FRLG_TRAINER_OFFSET+602)
#undef  TRAINER_CRUSH_GIRL_CYNDY_2
#define TRAINER_CRUSH_GIRL_CYNDY_2                           (FRLG_TRAINER_OFFSET+603)
#undef  TRAINER_TAMER_EVAN_2
#define TRAINER_TAMER_EVAN_2                                 (FRLG_TRAINER_OFFSET+604)
#undef  TRAINER_PKMN_RANGER_JACKSON_2
#define TRAINER_PKMN_RANGER_JACKSON_2                        (FRLG_TRAINER_OFFSET+605)
#undef  TRAINER_PKMN_RANGER_KATELYN_2
#define TRAINER_PKMN_RANGER_KATELYN_2                        (FRLG_TRAINER_OFFSET+606)
#undef  TRAINER_COOLTRAINER_LEROY_2
#define TRAINER_COOLTRAINER_LEROY_2                          (FRLG_TRAINER_OFFSET+607)
#undef  TRAINER_COOLTRAINER_MICHELLE_2
#define TRAINER_COOLTRAINER_MICHELLE_2                       (FRLG_TRAINER_OFFSET+608)
#undef  TRAINER_COOL_COUPLE_LEX_NYA_2
#define TRAINER_COOL_COUPLE_LEX_NYA_2                        (FRLG_TRAINER_OFFSET+609)
#undef  TRAINER_BUG_CATCHER_COLTON_2
#define TRAINER_BUG_CATCHER_COLTON_2                         (FRLG_TRAINER_OFFSET+610)
#undef  TRAINER_BUG_CATCHER_COLTON_3
#define TRAINER_BUG_CATCHER_COLTON_3                         (FRLG_TRAINER_OFFSET+611)
#undef  TRAINER_BUG_CATCHER_COLTON_4
#define TRAINER_BUG_CATCHER_COLTON_4                         (FRLG_TRAINER_OFFSET+612)
#undef  TRAINER_SWIMMER_MALE_MATTHEW_2
#define TRAINER_SWIMMER_MALE_MATTHEW_2                       (FRLG_TRAINER_OFFSET+613)
#undef  TRAINER_SWIMMER_MALE_TONY_2
#define TRAINER_SWIMMER_MALE_TONY_2                          (FRLG_TRAINER_OFFSET+614)
#undef  TRAINER_SWIMMER_FEMALE_MELISSA_2
#define TRAINER_SWIMMER_FEMALE_MELISSA_2                     (FRLG_TRAINER_OFFSET+615)
#undef  TRAINER_ELITE_FOUR_LORELEI_2
#define TRAINER_ELITE_FOUR_LORELEI_2                         (FRLG_TRAINER_OFFSET+616)
#undef  TRAINER_ELITE_FOUR_BRUNO_2
#define TRAINER_ELITE_FOUR_BRUNO_2                           (FRLG_TRAINER_OFFSET+617)
#undef  TRAINER_ELITE_FOUR_AGATHA_2
#define TRAINER_ELITE_FOUR_AGATHA_2                          (FRLG_TRAINER_OFFSET+618)
#undef  TRAINER_ELITE_FOUR_LANCE_2
#define TRAINER_ELITE_FOUR_LANCE_2                           (FRLG_TRAINER_OFFSET+619)
#undef  TRAINER_CHAMPION_REMATCH_SQUIRTLE
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE                    (FRLG_TRAINER_OFFSET+620)
#undef  TRAINER_CHAMPION_REMATCH_BULBASAUR
#define TRAINER_CHAMPION_REMATCH_BULBASAUR                   (FRLG_TRAINER_OFFSET+621)
#undef  TRAINER_CHAMPION_REMATCH_CHARMANDER
#define TRAINER_CHAMPION_REMATCH_CHARMANDER                  (FRLG_TRAINER_OFFSET+622)
#undef  TRAINER_CUE_BALL_PAXTON
#define TRAINER_CUE_BALL_PAXTON                              (FRLG_TRAINER_OFFSET+623)

#define FRLG_TRAINERS_END (FRLG_TRAINER_OFFSET+623)

// ACHTUNG, Falle fuer die Zukunft: Direkt hinter FRLG_TRAINERS_END
// beginnen die HnS-Rueckkampfstufen (HNS_REMATCH_TIERS_START = 2324).
// Neue FRLG-Trainer koennen deshalb NICHT einfach angehaengt werden -
// ihre Trainerflags (0x500 + ID) wuerden mit den Rueckkampf-Flags
// kollidieren. Wenn nach dem Release Trainer dazukommen sollen: eigenen
// ID-Bereich hinter HNS_REMATCH_TIERS_END anlegen, viertes Flag-Array
// ans Ende von SaveBlock3 anhaengen und in GetFlagPointer routen.

// Die Trainerflags dieser IDs (TRAINER_FLAGS_START + id) laegen im
// SYS_FLAGS-Bereich. Sie werden in GetFlagPointer nach SaveBlock3 umgeleitet.
//
// ACHTUNG: 0x500 + id ergibt fuer diesen Block 0xBA5-0xE13 - und das liegt
// mitten im Hoenn-Flagblock (HOENN_FLAGS_START = 0xB72, HOENN_FLAGS_END =
// 0xF53). Der alte Kommentar oben las 0xB72 faelschlich als Ende statt als
// Anfang. Folge: 615 Hoenn-Flags teilten sich ein Bit mit je einem
// FRLG-Trainer - Kaefersammler Gregor auf Route 3 setzte z.B.
// FLAG_ENABLE_ROXANNE_FIRST_CALL und Felizia rief in Kanto an.
//
// Die Trainer-IDs bleiben unveraendert; nur die Flag-IDs bekommen ein
// eigenes virtuelles Fenster oberhalb aller Hoenn-Flags und unterhalb von
// SPECIAL_FLAGS_START (0x4000). Umgerechnet wird in TrainerIdToFlagId().
//
// Der Rest mod 8 muss dem alten Fensteranfang (0xBA5 -> 5) entsprechen:
// GetFlagPointer bildet Byte ueber (id - START) / 8, das Bit aber ueber
// id & 7. Bleibt der Rest gleich, liegen alle Bits in bestehenden
// Spielstaenden unveraendert an ihrem Platz.
#define FRLG_TRAINER_FLAGS_BASE  0x3400
#define FRLG_TRAINER_FLAGS_START (FRLG_TRAINER_FLAGS_BASE + ((0x500 + FRLG_TRAINER_OFFSET + 1) & 7))
#define FRLG_TRAINER_FLAGS_END   (FRLG_TRAINER_FLAGS_START + (FRLG_TRAINERS_END - FRLG_TRAINER_OFFSET) - 1)
#define FRLG_TRAINER_FLAG_BYTES  (((FRLG_TRAINER_FLAGS_END - FRLG_TRAINER_FLAGS_START + 1) + 7) / 8)

#endif // GUARD_CONSTANTS_OPPONENTS_FRLG_HNS_H
