#ifndef GUARD_CONSTANTS_VARS_HOENN_DE_H
#define GUARD_CONSTANTS_VARS_HOENN_DE_H

// =====================================================================
// Smaragd-/Hoenn-Bereich (hns_de / modern_hns_engde)
// Trennung der Nummernraeume: Vars der Hoenn-Welt (und Engine-Doppel-
// belegungen), deren Nummer im HnS-Build anderweitig belegt ist, liegen
// hier in einem eigenen Bereich ab 0x4100. vars_hns.h bleibt unan-
// getastet (Upstream-Mergefaehigkeit).
// Regel: Neue Smaragd-Vars NUR aus diesem Bereich vergeben.
// =====================================================================

#define HOENN_VARS_START 0x4100

#undef  VAR_BIRCH_LAB_STATE
#define VAR_BIRCH_LAB_STATE 0x4100
#undef  VAR_BOARD_BRINEY_BOAT_STATE
#define VAR_BOARD_BRINEY_BOAT_STATE 0x4101
#undef  VAR_BRINEY_HOUSE_STATE
#define VAR_BRINEY_HOUSE_STATE 0x4102
#undef  VAR_BRINEY_LOCATION
#define VAR_BRINEY_LOCATION 0x4103
#undef  VAR_CABLE_CAR_STATION_STATE
#define VAR_CABLE_CAR_STATION_STATE 0x4104
#undef  VAR_CABLE_CLUB_STATE
#define VAR_CABLE_CLUB_STATE 0x4105
#undef  VAR_CABLE_CLUB_TUTORIAL_STATE
#define VAR_CABLE_CLUB_TUTORIAL_STATE 0x4106
#undef  VAR_CONTEST_PRIZE_PICKUP_EM
#define VAR_CONTEST_PRIZE_PICKUP_EM 0x4107
#undef  VAR_CONTEST_TYPE
#define VAR_CONTEST_TYPE 0x4108
#undef  VAR_CURRENT_SECRET_BASE
#define VAR_CURRENT_SECRET_BASE 0x4109
#undef  VAR_CYCLING_CHALLENGE_STATE
#define VAR_CYCLING_CHALLENGE_STATE 0x410A
#undef  VAR_DEVON_CORP_3F_STATE
#define VAR_DEVON_CORP_3F_STATE 0x410B
#undef  VAR_DEX_UPGRADE_JOHTO_STARTER_STATE
#define VAR_DEX_UPGRADE_JOHTO_STARTER_STATE 0x410C
#undef  VAR_EGG_BRAG_STATE
#define VAR_EGG_BRAG_STATE 0x410D
#undef  VAR_ELITE_4_STATE
#define VAR_ELITE_4_STATE 0x410E
#undef  VAR_FARAWAY_ISLAND_STEP_COUNTER
#define VAR_FARAWAY_ISLAND_STEP_COUNTER 0x410F
#undef  VAR_FOSSIL_MANIAC_STATE
#define VAR_FOSSIL_MANIAC_STATE 0x4110
#undef  VAR_HOF_BRAG_STATE
#define VAR_HOF_BRAG_STATE 0x4111
#undef  VAR_INIT_SECRET_BASE
#define VAR_INIT_SECRET_BASE 0x4112
#undef  VAR_LAVARIDGE_TOWN_STATE
#define VAR_LAVARIDGE_TOWN_STATE 0x4113
#undef  VAR_LILYCOVE_FAN_CLUB_STATE
#define VAR_LILYCOVE_FAN_CLUB_STATE 0x4114
#undef  VAR_LILYCOVE_MUSEUM_2F_STATE
#define VAR_LILYCOVE_MUSEUM_2F_STATE 0x4115
#undef  VAR_LITTLEROOT_HOUSES_STATE_BRENDAN
#define VAR_LITTLEROOT_HOUSES_STATE_BRENDAN 0x4116
#undef  VAR_LITTLEROOT_HOUSES_STATE_MAY
#define VAR_LITTLEROOT_HOUSES_STATE_MAY 0x4117
#undef  VAR_LITTLEROOT_INTRO_STATE
#define VAR_LITTLEROOT_INTRO_STATE 0x4118
#undef  VAR_LITTLEROOT_RIVAL_STATE
#define VAR_LITTLEROOT_RIVAL_STATE 0x4119
#undef  VAR_MAGIKARP_SIZE_RECORD
#define VAR_MAGIKARP_SIZE_RECORD 0x411A
#undef  VAR_MAP_SCENE_CINNABAR_ISLAND
#define VAR_MAP_SCENE_CINNABAR_ISLAND 0x411B
#undef  VAR_MAP_SCENE_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE
#define VAR_MAP_SCENE_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE 0x411C
#undef  VAR_MAP_SCENE_INDIGO_PLATEAU_EXTERIOR
#define VAR_MAP_SCENE_INDIGO_PLATEAU_EXTERIOR 0x411D
#undef  VAR_MAP_SCENE_ONE_ISLAND_POKEMON_CENTER_1F
#define VAR_MAP_SCENE_ONE_ISLAND_POKEMON_CENTER_1F 0x411E
#undef  VAR_MAP_SCENE_PALLET_TOWN_OAK
#define VAR_MAP_SCENE_PALLET_TOWN_OAK 0x411F
#undef  VAR_MAP_SCENE_POKEMON_CENTER_TEALA
#define VAR_MAP_SCENE_POKEMON_CENTER_TEALA 0x4120
#undef  VAR_MAP_SCENE_POKEMON_LEAGUE
#define VAR_MAP_SCENE_POKEMON_LEAGUE 0x4121
#undef  VAR_MAP_SCENE_ROUTE16
#define VAR_MAP_SCENE_ROUTE16 0x4122
#undef  VAR_MAP_SCENE_ROUTE23
#define VAR_MAP_SCENE_ROUTE23 0x4123
#undef  VAR_MAP_SCENE_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB
#define VAR_MAP_SCENE_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB 0x4124
#undef  VAR_MAP_SCENE_TRAINER_TOWER
#define VAR_MAP_SCENE_TRAINER_TOWER 0x4125
#undef  VAR_MAUVILLE_GYM_STATE
#define VAR_MAUVILLE_GYM_STATE 0x4126
#undef  VAR_MIRAGE_RND_L
#define VAR_MIRAGE_RND_L 0x4127
#undef  VAR_MIRAGE_TOWER_STATE
#define VAR_MIRAGE_TOWER_STATE 0x4128
#undef  VAR_MOSSDEEP_CITY_STATE
#define VAR_MOSSDEEP_CITY_STATE 0x4129
#undef  VAR_MOSSDEEP_SPACE_CENTER_STAIR_GUARD_STATE
#define VAR_MOSSDEEP_SPACE_CENTER_STAIR_GUARD_STATE 0x412A
#undef  VAR_MOSSDEEP_SPACE_CENTER_STATE
#define VAR_MOSSDEEP_SPACE_CENTER_STATE 0x412B
#undef  VAR_NOBLE_ELECTRODE
#define VAR_NOBLE_ELECTRODE 0x412C
#undef  VAR_NOBLE_OVERQWIL
#define VAR_NOBLE_OVERQWIL 0x412D
#undef  VAR_NOBLE_SNEASLER
#define VAR_NOBLE_SNEASLER 0x412E
#undef  VAR_PETALBURG_CITY_STATE
#define VAR_PETALBURG_CITY_STATE 0x412F
#undef  VAR_PETALBURG_GYM_STATE
#define VAR_PETALBURG_GYM_STATE 0x4130
#undef  VAR_PETALBURG_WOODS_STATE
#define VAR_PETALBURG_WOODS_STATE 0x4131
#undef  VAR_PLATECOUNTER
#define VAR_PLATECOUNTER 0x4132
#undef  VAR_POKELOT_RND1
#define VAR_POKELOT_RND1 0x4133
#undef  VAR_REGICE_STEPS_3
#define VAR_REGICE_STEPS_3 0x4134
#undef  VAR_REGIS_SCANNED
#define VAR_REGIS_SCANNED 0x4135
#undef  VAR_RESORT_GOREGEOUS_STEP_COUNTER
#define VAR_RESORT_GOREGEOUS_STEP_COUNTER 0x4136
#undef  VAR_RESORT_GORGEOUS_REQUESTED_MON
#define VAR_RESORT_GORGEOUS_REQUESTED_MON 0x4137
#undef  VAR_RESORT_GORGEOUS_REWARD
#define VAR_RESORT_GORGEOUS_REWARD 0x4138
#undef  VAR_ROAMER_POKEMON
#define VAR_ROAMER_POKEMON 0x4139
#undef  VAR_ROUTE101_STATE
#define VAR_ROUTE101_STATE 0x413A
#undef  VAR_ROUTE104_STATE
#define VAR_ROUTE104_STATE 0x413B
#undef  VAR_ROUTE110_STATE
#define VAR_ROUTE110_STATE 0x413C
#undef  VAR_ROUTE116_STATE
#define VAR_ROUTE116_STATE 0x413D
#undef  VAR_ROUTE118_STATE
#define VAR_ROUTE118_STATE 0x413E
#undef  VAR_ROUTE119_STATE
#define VAR_ROUTE119_STATE 0x413F
#undef  VAR_ROUTE121_STATE
#define VAR_ROUTE121_STATE 0x4140
#undef  VAR_ROUTE128_STATE
#define VAR_ROUTE128_STATE 0x4141
#undef  VAR_RUSTBORO_CITY_STATE
#define VAR_RUSTBORO_CITY_STATE 0x4142
#undef  VAR_RUSTURF_TUNNEL_STATE
#define VAR_RUSTURF_TUNNEL_STATE 0x4143
#undef  VAR_SEAFLOOR_CAVERN_STATE
#define VAR_SEAFLOOR_CAVERN_STATE 0x4144
#undef  VAR_SECRET_BASE_INITIALIZED
#define VAR_SECRET_BASE_INITIALIZED 0x4145
#undef  VAR_SKY_PILLAR_RAYQUAZA_CRY_DONE
#define VAR_SKY_PILLAR_RAYQUAZA_CRY_DONE 0x4146
#undef  VAR_SLATEPORT_CITY_STATE
#define VAR_SLATEPORT_CITY_STATE 0x4147
#undef  VAR_SLATEPORT_HARBOR_STATE
#define VAR_SLATEPORT_HARBOR_STATE 0x4148
#undef  VAR_SLATEPORT_MUSEUM_1F_STATE
#define VAR_SLATEPORT_MUSEUM_1F_STATE 0x4149
#undef  VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE
#define VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE 0x414A
#undef  VAR_SOOTOPOLIS_CITY_STATE
#define VAR_SOOTOPOLIS_CITY_STATE 0x414B
#undef  VAR_SS_TIDAL_SCOTT_STATE
#define VAR_SS_TIDAL_SCOTT_STATE 0x414C
#undef  VAR_TRAINER_CARD_MON_ICON_1
#define VAR_TRAINER_CARD_MON_ICON_1 0x414D
#undef  VAR_TRAINER_CARD_MON_ICON_3
#define VAR_TRAINER_CARD_MON_ICON_3 0x414E
#undef  VAR_TRAINER_CARD_MON_ICON_4
#define VAR_TRAINER_CARD_MON_ICON_4 0x414F
#undef  VAR_TRAINER_CARD_MON_ICON_5
#define VAR_TRAINER_CARD_MON_ICON_5 0x4150
#undef  VAR_TRAINER_CARD_MON_ICON_6
#define VAR_TRAINER_CARD_MON_ICON_6 0x4151
#undef  VAR_TRAINER_CARD_MON_ICON_TINT_IDX
#define VAR_TRAINER_CARD_MON_ICON_TINT_IDX 0x4152
#undef  VAR_TRICK_HOUSE_BEING_WATCHED_STATE
#define VAR_TRICK_HOUSE_BEING_WATCHED_STATE 0x4153
#undef  VAR_TRICK_HOUSE_ENTRANCE_STATE
#define VAR_TRICK_HOUSE_ENTRANCE_STATE 0x4154
#undef  VAR_TRICK_HOUSE_FOUND_TRICK_MASTER
#define VAR_TRICK_HOUSE_FOUND_TRICK_MASTER 0x4155
#undef  VAR_TRICK_HOUSE_LEVEL
#define VAR_TRICK_HOUSE_LEVEL 0x4156
#undef  VAR_TRICK_HOUSE_PUZZLE_1_STATE
#define VAR_TRICK_HOUSE_PUZZLE_1_STATE 0x4157
#undef  VAR_TRICK_HOUSE_PUZZLE_2_STATE
#define VAR_TRICK_HOUSE_PUZZLE_2_STATE 0x4158

// Neue Vars der Hoenn-Anbindung
#define VAR_HOENN_ARRIVAL_STATE 0x4159
// Hoenn-Orden als Bitmaske (Bit 0 = Steinorden ... Bit 7 = Regenorden).
// Die Vanilla-Arenascripts setzen weiterhin FLAG_BADGE0X_GET (beim
// Champion bereits gesetzt = wirkungslos); das Hoenn-System zaehlt hier.
#define VAR_HOENN_BADGES 0x415A
// VM-Lizenzen als Bitmaske (siehe include/hoenn_licenses.h). Nur innerhalb
// von Hoenn wirksam; Fliegen und Blitz sind bewusst nicht enthalten.
#define VAR_HOENN_LICENSES 0x415B
// Stand der Troy-Ticketkette: 0 = nichts, 1 = Versprechen in Orania gegeben,
// 2 = Anruf nach der Kanto-Liga erfolgt (Troy wartet in der Silph Co.),
// 3 = Hoennticket uebergeben.
#define VAR_HOENN_TICKET_STATE 0x415C
// Schrittzaehler fuer Normans Anruf nach einer Ordenuebergabe.
#define VAR_HNS_NORMAN_CALL_STEPS 0x415D

#define HOENN_VARS_END 0x4176

// Var-Speicher erweitern: bleibt in SaveBlock1 (STATIC_ASSERT in save.c),
// Flashgroesse unveraendert 128 KiB (FLASH_1M) -> emulator-nativ.
#undef  VARS_END
#undef  VARS_COUNT
#define VARS_END HOENN_VARS_END
#define VARS_COUNT (VARS_END - VARS_START + 1)

#endif // GUARD_CONSTANTS_VARS_HOENN_DE_H
