
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
#if GERMAN
	.string "Willkommen im Kampfcamp von\n"
	.string "Laubwechselfeld!\p"
	.string "Ich begleite dich zu dem K.O.-\n"
	.string "Teamturnier.$"
#else
	.string "I welcome you to the BATTLE TENT!\p"
	.string "I am your guide to the Set KO Tourney!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
#if GERMAN
	.string "Möchtest du dich der Herausforderung\n"
	.string "des K.O.-Kampfturniers stellen?$"
#else
	.string "Now, do you wish to take the challenge\n"
	.string "of a Set KO Tourney?$"
#endif

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
#if GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
#else
	.string "We await your challenge on\n"
	.string "another occasion!$"
#endif

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
#if GERMAN
#if IS_HNS
	.string "Im Arena-Kampfcamp\n"
#else
	.string "Im Kampfcamp von Laubwechselfeld\n"
#endif
	.string "findet das K.O.-Teamturnier statt.\p"
	.string "Jeder Teilnehmer darf drei Pokémon\n"
	.string "in den Kampf mitnehmen.\p"
	.string "Diese müssen in der Reihenfolge\n"
	.string "angeordnet werden, in der sie kämpfen\l"
	.string "sollen.\p"
	.string "Diese Reihenfolge wird im Kampf strikt\n"
	.string "eingehalten.\p"
	.string "Ein Pokémon bleibt solange im Kampf,\n"
	.string "bis der Kampf entschieden ist.\p"
	.string "Wenn ein Kampf nach drei Runden noch\n"
	.string "nicht entschieden ist, wird der Sieger\l"
	.string "durch ein richterliches Urteil bestimmt.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen möchtest, speichere\l"
	.string "bitte dein Spiel.\p"
	.string "Wenn du ohne Speichern unterbrichst,\n"
	.string "ist die Herausforderung beendet.\p"
	.string "Besiegst du drei Trainer in Folge,\n"
	.string "gewinnst du einen fantastischen Preis.$"
#else
#if IS_HNS
	.string "In the ARENA BATTLE TENT,\n"
#else
	.string "In the FALLARBOR BATTLE TENT,\n"
#endif
	.string "we undertake the Set KO Tourney.\p"
	.string "All participants enter with a team of\n"
	.string "three POKéMON.\p"
	.string "The three POKéMON must be lined up\n"
	.string "in the order that they are to appear in.\p"
	.string "During battle, the POKéMON will appear\n"
	.string "one at a time in the preset order.\p"
	.string "Once a POKéMON enters battle, it must\n"
	.string "remain out until the match is decided.\p"
	.string "If a match remains undecided in\n"
	.string "three turns, it goes to judging.\p"
	.string "If you wish to interrupt your challenge,\n"
	.string "please save the game.\p"
	.string "If you don't save, you will not be able\n"
	.string "to continue with your challenge.\p"
	.string "If you pull off the feat of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a fine prize.$"
#endif

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
#if GERMAN
	.string "Bevor du das Kampfcamp betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"
#else
	.string "Before showing you to the BATTLE\n"
	.string "TENT, I must save. Is that okay?$"
#endif

FallarborTown_BattleTentLobby_Text_WhichLevelMode:
#if GERMAN
	.string "Jedes Turnier bietet zwei Kategorien\n"
	.string "an: Level 50 und Offene Kämpfe. Wofür\l"
	.string "entscheidest du dich?$"
#else
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"
#endif

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
#if GERMAN
	.string "Sehr schön! Dann bestimme jetzt bitte\n"
	.string "deine drei Pokémon.$"
#else
	.string "Very well, now select your\n"
	.string "three POKéMON, please.$"
#endif

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
#if GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
#else
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"
#endif

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
#if GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
#else
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "To qualify, you must bring three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"
#endif

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
#if GERMAN
	.string "Ich werde dich nun zum Kampfcamp\n"
	.string "begleiten.$"
#else
	.string "I shall now guide you to\n"
	.string "the BATTLE TENT.$"
#endif

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
#if GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du leider für diese\n"
	.string "Herausforderung disqualifiziert.\l"
	.string "Schade!\p"
	.string "Natürlich kannst du dich einer neuen\n"
	.string "Herausforderung stellen!$"
#else
	.string "My dear challenger!\p"
	.string "You did not save the game before\n"
	.string "shutting down, did you?\p"
	.string "It is unfortunate, but that has\n"
	.string "resulted in your disqualification\l"
	.string "from your challenge.\p"
	.string "You may, of course, start with a fresh\n"
	.string "challenge.$"
#endif

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
#if GERMAN
	.string "Hervorragend! Du hast drei Trainer in\n"
	.string "Folge besiegt!$"
#else
	.string "How splendid! You have beaten\n"
	.string "three TRAINERS in succession!$"
#endif

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
#if GERMAN
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warten.$"
#else
	.string "Please wait while I save the game.$"
#endif

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
#if GERMAN
	.string "In Anerkennung deines dreifachen\n"
	.string "Sieges überreichen wir dir diesen Preis.$"
#else
	.string "In commemoration of your 3-win streak,\n"
	.string "we present you with this prize.$"
#endif

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
#if GERMAN
	.string "{PLAYER} gewinnt {STR_VAR_1}.$"
#else
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
#endif

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
#if GERMAN
	.string "Oh, dein Beutel ist voll.\p"
	.string "Bitte schaffe Platz in deinem Beutel\n"
	.string "und komme dann wieder.$"
#else
	.string "Oh?\n"
	.string "Your BAG seems to be full.\p"
	.string "I urge you to clear space and\n"
	.string "return for your prize.$"
#endif

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
#if GERMAN
	.string "Vielen Dank für die Teilnahme!\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warten.$"
#else
	.string "Thank you so much for participating!\p"
	.string "Please wait while I save the game.$"
#endif

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
#if GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
#else
	.string "We await your challenge on\n"
	.string "another occasion!$"
#endif

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
#if GERMAN
	.string "Wir haben schon auf dich gewartet!\p"
	.string "Bevor du das Kampfcamp betrittst, wird\n"
	.string "dein Spiel gespeichert.\l"
	.string "Bitte warten.$"
#else
	.string "We have been looking forward to\n"
	.string "your arrival.\p"
	.string "Before I show you to the BATTLE TENT,\n"
	.string "I must save the game. Please wait.$"
#endif

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
#if GERMAN
	.string "Willkommen im Kampfcamp von Wiesenflur!\p"
	.string "Hier wird das Vertrauen der Trainer in\n"
	.string "ihre Pokémon getestet.$"
#else
	.string "I welcome you to the BATTLE TENT!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#endif

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
#if GERMAN
	.string "Möchtest du dich der Herausforderung\n"
	.string "des Wiesenflur Kampfcamps stellen?$"
#else
#if IS_HNS
	.string "Do you wish to take the PALACE\n"
#else
	.string "Do you wish to take the VERDANTURF\n"
#endif
	.string "BATTLE TENT challenge?$"
#endif

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
#if GERMAN
#if IS_HNS
	.string "Im Palast-Kampfcamp gibt es\n"
#else
	.string "Im Kampfcamp von Wiesenflur gibt es\n"
#endif
	.string "eine entscheidende Regel, die beachtet\l"
	.string "werden muss.\p"
	.string "Trainer dürfen ihre Pokémon lediglich\n"
	.string "in den Kampf rufen und zurückziehen.\p"
	.string "Ansonsten ist es ihnen nicht erlaubt,\n"
	.string "in den Kampf einzugreifen.\p"
	.string "Die Pokémon sollen sich gemäß ihres\n"
	.string "Wesens verhalten und kämpfen.\p"
	.string "Du musst deinen Pokémon vertrauen und\n"
	.string "sie beobachten.\p"
	.string "Wenn du es schaffst, drei Trainer in\n"
	.string "Folge zu besiegen, bekommst du einen\l"
	.string "Preis von uns.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen willst, speichere bitte\l"
	.string "dein Spiel.\p"
	.string "Brichst du die Herausforderung ohne zu\n"
	.string "speichern ab, wirst du disqualifiziert.$"
#else
#if IS_HNS
	.string "In the PALACE BATTLE TENT,\n"
#else
	.string "In the VERDANTURF BATTLE TENT,\n"
#endif
	.string "there is one crucial rule that must\l"
	.string "be obeyed.\p"
	.string "TRAINERS are permitted only to switch\n"
	.string "their POKéMON in and out.\p"
	.string "TRAINERS are otherwise forbidden to\n"
	.string "command their POKéMON.\p"
	.string "The POKéMON are to behave according\n"
	.string "to their nature and battle on their own.\p"
	.string "You must put your trust in your\n"
	.string "POKéMON and watch over them.\p"
	.string "If you achieve the honor of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"
#endif

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
#if GERMAN
	.string "Hast du dein Herz gestärkt und deine\n"
	.string "Pokémon, dann komm wieder.$"
#else
	.string "When you have fortified your heart\n"
	.string "and POKéMON, you must return.$"
#endif

VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
#if GERMAN
	.string "Es gibt zwei Schwierigkeitsgrade: Level\n"
	.string "50 und Offene Kämpfe. Wofür\l"
	.string "entscheidest du dich?$"
#else
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"
#endif

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
#if GERMAN
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
#else
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"
#endif

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
#if GERMAN
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
#else
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"
#endif

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
#if GERMAN
	.string "Gut. Dann bestimme jetzt deine drei\n"
	.string "Pokémon.$"
#else
	.string "Good. Now, you must select your\n"
	.string "three POKéMON.$"
#endif

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
#if GERMAN
	.string "Bevor du das Kampfcamp betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"
#else
	.string "I must save before I show you to\n"
	.string "the BATTLE TENT. Is that okay?$"
#endif

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
#if GERMAN
	.string "Gut. Dann folge mir.$"
#else
	.string "Good.\n"
	.string "Now, follow me.$"
#endif

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
#if GERMAN
	.string "Ich fühle mich geehrt, dass ich deinen\n"
	.string "Pokémon zuschauen durfte.\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"
#else
	.string "I feel privileged for having seen\n"
	.string "your POKéMON's exploits.\p"
	.string "The results will be recorded.\n"
	.string "I must ask you to briefly wait.$"
#endif

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
#if GERMAN
	.string "Drei Siege in Folge…\p"
	.string "Das Band zwischen dir und deinen\n"
	.string "Pokémon ist wirklich stark.$"
#else
	.string "To achieve a 3-win streak…\p"
	.string "The bonds that bind your heart with\n"
	.string "your POKéMON seem firm and true.$"
#endif

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
#if GERMAN
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"
#else
	.string "Your feat will be recorded.\n"
	.string "I must ask you to briefly wait.$"
#endif

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
#if GERMAN
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"
#else
	.string "For the feat of your 3-win streak,\n"
	.string "we present you with this prize.$"
#endif


SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
#if GERMAN
	.string "Willkommen im Kampfcamp von\n"
	.string "Graphitport City.\p"
	.string "Ich begleite dich zum Wechselkampf-\n"
	.string "Turnier.$"
#else
	.string "Welcome to the BATTLE TENT!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#endif

SlateportCity_BattleTentLobby_Text_TakeChallenge:
#if GERMAN
	.string "Möchtest du am Wechselkampf\n"
	.string "teilnehmen?$"
#else
	.string "Would you like to take the Battle\n"
	.string "Swap challenge?$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
#if GERMAN
#if IS_HNS
	.string "Hier im Fabrik-Kampfcamp\n"
#else
	.string "Hier im Kampfcamp von Graphitport City\n"
#endif
	.string "halten wir Wechselkampf-Turniere ab,\l"
	.string "die mit Leih-Pkmn ausgetragen werden.\p"
	.string "Als Erstes leihst du dir drei Pokémon.\p"
	.string "Mit diesen kannst du an einem\n"
	.string "Einzelkampf teilnehmen.\p"
	.string "Gewinnst du, darfst du ein Leih-\n"
	.string "Pokémon tauschen.\p"
	.string "Wiederhole diese Folge von Siegen und\n"
	.string "Tausch. Gewinnst du drei Mal in Folge,\l"
	.string "erhältst du einen Preis.\p"
	.string "Wenn du die Herausforderung abbrechen\n"
	.string "willst, speichere dein Spiel.\p"
	.string "Wenn du ohne zu speichern abbrichst,\n"
	.string "wirst du disqualifiziert.$"
#else
#if IS_HNS
	.string "Here at the FACTORY BATTLE TENT,\n"
#else
	.string "Here at the SLATEPORT BATTLE TENT,\n"
#endif
	.string "we hold Battle Swap events\l"
	.string "using rental POKéMON.\p"
	.string "First, you will be loaned three\n"
	.string "POKéMON specifically for this event.\p"
	.string "Using the supplied rental POKéMON,\n"
	.string "you must conduct a SINGLE BATTLE.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental POKéMON.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"
#endif

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
#if GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
#else
	.string "We look forward to your next visit.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
#if GERMAN
	.string "An welcher Stufe möchtest du teil-\n"
	.string "nehmen? Level 50 oder Offene Kämpfe?$"
#else
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"
#endif

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
#if GERMAN
	.string "Bevor du dich der Herausforderung\n"
	.string "stellst, speichere ich dein Spiel. Okay?$"
#else
	.string "Before you begin your challenge,\n"
	.string "I need to save data. Is that okay?$"
#endif

SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
#if GERMAN
	.string "Gut, ich werde deine Pokémon sicher für\n"
	.string "dich aufbewahren, während du\l"
	.string "teilnimmst.$"
#else
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"
#endif

SlateportCity_BattleTentLobby_Text_StepThisWay:
#if GERMAN
	.string "Bitte hier entlang.$"
#else
	.string "Please step this way.$"
#endif

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
#if GERMAN
	.string "Vielen Dank für deine Teilnahme!\p"
	.string "Ich gebe dir nun deine Pokémon\n"
	.string "zurück.\p"
	.string "Ich werde das Ergebnis speichern.\n"
	.string "Bitte warte einen Moment.$"
#else
	.string "Thank you for participating!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
#if GERMAN
	.string "Ich gebe dir deine Pokémon zurück und\n"
	.string "nehme dafür unsere Leih-Pokémon\l"
	.string "entgegen.$"
#else
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"
#endif

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
#if GERMAN
	.string "Herzlichen Glückwunsch!\n"
	.string "Du hast drei Kämpfe in Folge gewonnen!\p"
	.string "Ich gebe dir nun deine Pokémon\n"
	.string "zurück.\p"
	.string "Ich werde deinen Erfolg speichern.\n"
	.string "Bitte warte einen Moment.$"
#else
	.string "Congratulations!\n"
	.string "You've won three straight matches!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
#endif

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
#if GERMAN
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"
#else
	.string "In recognition of your 3-win streak,\n"
	.string "we award you this prize.$"
#endif

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
#if GERMAN
	.string "Oh, dein Beutel ist voll.\p"
	.string "Bitte schaffe Platz in deinem Beutel\n"
	.string "und komme dann wieder.$"
#else
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"
#endif

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
#if GERMAN
	.string "Wir haben auf dich gewartet!\p"
	.string "Bevor du die Herausforderung\n"
	.string "fortsetzt, speichere ich dein Spiel.$"
#else
	.string "We've been waiting for you!\p"
	.string "Before we resume your challenge,\n"
	.string "I must save the game.$"
#endif

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
#if GERMAN
	.string "Entschuldigung!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du für diese Herausforde-\n"
	.string "rung disqualifiziert. Schade!$"
#else
	.string "I'm sorry to say this, but you didn't\n"
	.string "save before you quit playing last time.\p"
	.string "As a result, you have been disqualified\n"
	.string "from your challenge.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
#if GERMAN
	.string "Wir geben dir nun deine eigenen\n"
	.string "Pokémon zurück.$"
#else
	.string "We'll return your personal POKéMON.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
#if GERMAN
	.string "{PLAYER} gewinnt {STR_VAR_1}.$"
#else
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
#if GERMAN
	.string "Die Regeln des Wechselkampfes hängen\n"
	.string "öffentlich aus.$"
#else
	.string "The Battle Swap rules are listed.$"
#endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
#if GERMAN
	.string "Wähle bitte ein Themengebiet aus.$"
#else
	.string "Which heading do you want to read?$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
#if GERMAN
	.string "In einem Wechselkampf darfst du\n"
	.string "nur drei Pokémon einsetzen.\p"
	.string "Egal, ob du sie dir ausleihst oder\n"
	.string "tauschst, du darfst keine zwei gleichen\l"
	.string "Pokémon in deinem Team haben.$"
#else
	.string "In a Battle Swap event, you may use\n"
	.string "only three POKéMON.\p"
	.string "Whether you are renting or swapping,\n"
	.string "your team may not have two or more\l"
	.string "of the same POKéMON.$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
#if GERMAN
	.string "Du kannst mit dem Trainer Pokémon\n"
	.string "tauschen, den du besiegt hast.\p"
	.string "Allerdings nur die Pokémon, die dieser im\n"
	.string "Kampf eingesetzt hat. Ein genereller\l"
	.string "Tausch ist nicht möglich.$"
#else
	.string "You may swap POKéMON only with\n"
	.string "the TRAINER you have just defeated.\p"
	.string "You may swap for only those POKéMON\n"
	.string "used by the beaten TRAINER.$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
#if GERMAN
	.string "Nach jedem gewonnenen Kampf kannst du\n"
	.string "eines deiner Pokémon gegen das deines\l"
	.string "Gegners tauschen.\p"
	.string "Du kannst mit dem dritten Trainer\n"
	.string "allerdings keine Pokémon tauschen.$"
#else
	.string "After every battle you win, you may\n"
	.string "swap for one of your defeated\l"
	.string "opponent's POKéMON.\p"
	.string "You will not be able to swap POKéMON\n"
	.string "with the third TRAINER in the event.$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
#if GERMAN
	.string "Beim Pokémon-Tausch musst du auf zwei\n"
	.string "Dinge achten!\p"
	.string "Du kannst den Status des Pokémon, das\n"
	.string "du haben möchtest, vor dem Tausch\l"
	.string "nicht überprüfen.\p"
	.string "Denk daran, dass deine Pokémon in einer\n"
	.string "bestimmten Reihenfolge angeordnet\l"
	.string "sind.\p"
	.string "Diese bleibt auch nach dem Tausch\n"
	.string "unverändert.$"
#else
	.string "There are two key points to be aware\n"
	.string "of when swapping POKéMON.\p"
	.string "First, when swapping, you can't check\n"
	.string "the stats of the POKéMON you are\l"
	.string "about to receive.\p"
	.string "Second, the POKéMON on your team\n"
	.string "are lined up in sequence, depending on\l"
	.string "the order in which you rented them.\p"
	.string "This sequence remains unchanged\n"
	.string "even when swaps are made.$"
#endif

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
#if GERMAN
	.string "Die Pokémon im Kampfcamp von\n"
	.string "Graphitport City sind alle\l"
	.string "Leih-Pokémon.\p"
	.string "Diese stehen auf Level 30.$"
#else
	.string "The POKéMON of the SLATEPORT\n"
	.string "BATTLE TENT are all rentals.\p"
	.string "All rental POKéMON are kept at\n"
	.string "Level 30.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
#if GERMAN
	.string "Die Regeln des Wiesenflur Kampfcamps\n"
	.string "hängen öffentlich aus.$"
#else
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
#if GERMAN
	.string "Wähle bitte ein Themengebiet aus.$"
#else
	.string "Which heading do you want to read?$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
#if GERMAN
	.string "Hier müssen die Pokémon selbständig\n"
	.string "handeln und kämpfen.\p"
	.string "Anders als wilde Pokémon reagieren\n"
	.string "Pokémon, die mit Menschen zusammen-\l"
	.string "leben, abhängig von ihrem Wesen.$"
#else
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
#if GERMAN
	.string "Je nach Wesenheit wird ein Pokémon\n"
	.string "eventuell angreifen, egal, was passiert.\p"
	.string "Ein anderes wird sich vielleicht seinem\n"
	.string "Wesen entsprechend unter allen\p"
	.string "Umständen schützen wollen. Ein anderes\n"
	.string "irritiert oder verwirrt seinen Gegner.\p"
	.string "Abhängig von seinem Wesen wird ein\n"
	.string "Pokémon Lieblingsattacken haben, die\l"
	.string "es hervorragend beherrscht.\p"
	.string "Auf der anderen Seite wird es Attacken\n"
	.string "kennen, die es nicht mag und die ihm\l"
	.string "Schwierigkeiten machen.$"
#else
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
#if GERMAN
	.string "Es gibt offensive Attacken, die dem\n"
	.string "Gegner Schaden zufügen.\p"
	.string "Es gibt defensive Attacken, die auf\n"
	.string "gegnerische Attacken vorbereiten oder\l"
	.string "aber KP wiederherstellen können.\p"
	.string "Und es gibt Attacken, die den Gegner\n"
	.string "schwächen, indem sie Statusprobleme\l"
	.string "verursachen, wie Vergiftungen oder\l"
	.string "Paralyse.\p"
	.string "Pokémon werden diese 3 Kategorien mit\n"
	.string "Sicherheit im Kampf in Betracht ziehen!$"
#else
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
#if GERMAN
	.string "Gibt ein Trainer seinem Pokémon keine\n"
	.string "Anweisungen, wird es vielleicht nicht in\l"
	.string "der Lage sein, bestimmte Attacken\p"
	.string "einzusetzen. Ein Pokémon hat\n"
	.string "Schwierigkeiten mit Attacken, die es\l"
	.string "nicht mag.\p"
	.string "Kennt ein Pokémon nur Attacken, die\n"
	.string "seinem Wesen widersprechen, so kann es\l"
	.string "nicht immer sein ganzes Können zeigen.$"
#else
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"
#endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
#if GERMAN
	.string "Abhängig von seinem Wesen, wird ein\n"
	.string "Pokémon vielleicht auch Attacken ein-\l"
	.string "setzen, die seinem Wesen widersprechen.\p"
	.string "Benimmt es sich in bestimmten\n"
	.string "Situationen merkwürdig, beobachte es\l"
	.string "genau.$"
#else
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"
#endif

BattleTentLobby_Text_ExplainLevelRules:
#if GERMAN
	.string "In diesem Kampfcamp werden die Level\n"
	.string "der gegnerischen Pokémon an die Level\l"
	.string "deiner Pokémon angepasst.\p"
	.string "Trotzdem wird kein Trainer, auf den du\n"
	.string "triffst, Pokémon unter Level 30 haben.$"
#else
	.string "At this BATTLE TENT, the levels of\n"
	.string "your opponents will be adjusted to\l"
	.string "match the levels of your POKéMON.\p"
	.string "However, no TRAINER you face will\n"
	.string "have any POKéMON below Level 30.$"
#endif

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
#if GERMAN
	.string "Die Regeln des Wiesenflur Kampfcamps\n"
	.string "hängen öffentlich aus.$"
#else
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
#endif

