@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
#if GERMAN
	.string "Ich bin der Pensionsleiter.\p"
	.string "Ich kümmere mich um die wertvollen\n"
	.string "Pokémon der Trainer.\p"
	.string "Wenn ich eines deiner Pokémon auf-\n"
	.string "ziehen soll, sprich mit meiner Frau.$"
#else
	.string "I'm the DAY-CARE MAN.\p"
	.string "I help take care of the precious\n"
	.string "POKéMON of TRAINERS.\p"
	.string "If you'd like me to raise your\n"
	.string "POKéMON, have a word with my wife.$"
#endif

DayCare_Text_DoYouWantEgg::
#if GERMAN
	.string "Ach, du bist es!\p"
	.string "Wir haben deine Pokémon aufgezogen\n"
	.string "und wurden überrascht!\p"
	.string "Deine Pokémon haben nun ein Ei!\p"
	.string "Wir wissen nicht, wie das passiert ist,\n"
	.string "aber deine Pokémon haben es.\p"
	.string "Möchtest du es haben?$"
#else
	.string "Ah, it's you!\p"
	.string "We were raising your POKéMON, and\n"
	.string "my goodness, were we surprised!\p"
	.string "Your POKéMON had an EGG!\p"
	.string "We don't know how it got there,\n"
	.string "but your POKéMON had it.\p"
	.string "You do want it, yes?$"
#endif

DayCare_Text_YourMonIsDoingFine::
#if GERMAN
	.string "Ach, du bist es! Schön, dich zu sehen.\n"
	.string "Deinem {STR_VAR_1} geht es sehr gut.$"
#else
	.string "Ah, it's you! Good to see you.\n"
	.string "Your {STR_VAR_1}'s doing fine.$"
#endif

DayCare_Text_IllKeepIt::
#if GERMAN
	.string "Ich werde es behalten.$"
#else
	.string "Well then, I'll keep it.\n"
	.string "Thanks!$"
#endif

DayCare_Text_YouHaveNoRoomForIt::
#if GERMAN
	.string "Du hast keinen Platz dafür… Komm\n"
	.string "wieder, wenn du Platz geschafft hast.$"
#else
	.string "You have no room for it…\n"
	.string "Come back when you've made room.$"
#endif

DayCare_Text_ReceivedEgg::
#if GERMAN
	.string "{PLAYER} erhält das Ei vom\n"
	.string "Pensionsleiter.$"
#else
	.string "{PLAYER} received the EGG from\n"
	.string "the DAY-CARE MAN.$"
#endif

DayCare_Text_TakeGoodCareOfIt::
#if GERMAN
	.string "Kümmere dich gut darum.$"
#else
	.string "Take good care of it.$"
#endif

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
#if GERMAN
	.string "Wenn du dein Pokémon abholen\n"
	.string "willst, sprich mit meiner Frau.$"
#else
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"
#endif

DayCare_Text_YourMonsAreDoingFine::
#if GERMAN
	.string "Ah, du bist es! Deine Pokémon {STR_VAR_1}\n"
	.string "und {STR_VAR_2} entwickeln sich prächtig.$"
#else
	.string "Ah, it's you! Your {STR_VAR_1} and\n"
	.string "{STR_VAR_2} are doing fine.$"
#endif

DayCare_Text_IWillKeepDoYouWantIt::
#if GERMAN
	.string "Ich werde es behalten.\n"
	.string "Oder möchtest du es haben?$"
#else
	.string "I really will keep it.\n"
	.string "You do want this, yes?$"
#endif

DayCare_Text_WouldYouLikeUsToRaiseMon::
#if GERMAN
	.string "Ich bin die Pensionsleiterin.\p"
	.string "Wir ziehen Pokémon für dich auf.\p"
	.string "Sollen wir eins für dich aufziehen?$"
#else
	.string "I'm the DAY-CARE LADY.\p"
	.string "We can raise POKéMON for you.\p"
	.string "Would you like us to raise one?$"
#endif

DayCare_Text_WhichMonShouldWeRaise::
#if GERMAN
	.string "Welches Pokémon sollen wir für dich\n"
	.string "aufziehen?$"
#else
	.string "Which POKéMON should we raise for\n"
	.string "you?$"
#endif

DayCare_Text_WellRaiseYourMon::
#if GERMAN
	.string "Fein, dann nehmen wir dein {STR_VAR_1}\n"
	.string "für eine Weile in Pflege.\p"
	.string "Schau später mal nach ihm.$"
#else
	.string "Fine, we'll raise your {STR_VAR_1}\n"
	.string "for a while.\p"
	.string "Come back for it later.$"
#endif

DayCare_Text_WeCanRaiseOneMore::
#if GERMAN
	.string "Wir können zwei deiner Pokémon nehmen.\n"
	.string "Möchtest du noch eines in Pflege\l"
	.string "geben?$"
#else
	.string "We can raise two of your POKéMON.\p"
	.string "Would you like us to raise one\n"
	.string "more POKéMON for you?$"
#endif

DayCare_Text_HusbandWasLookingForYou::
#if GERMAN
	.string "Mein Mann hat dich schon gesucht.$"
#else
	.string "My husband was looking for you.$"
#endif

DayCare_Text_FineThenComeAgain::
#if GERMAN
	.string "Na schön.\n"
	.string "Schau wieder vorbei.$"
#else
	.string "Oh, fine, then.\n"
	.string "Come again.$"
#endif

DayCare_Text_NotEnoughMoney::
#if GERMAN
	.string "Du hast nicht genug Geld…$"
#else
	.string "You don't have enough money…$"
#endif

DayCare_Text_TakeOtherOneBackToo::
#if GERMAN
	.string "Möchtest du das andere auch wieder\n"
	.string "mitnehmen?$"
#else
	.string "Will you take back the other one,\n"
	.string "too?$"
#endif

DayCare_Text_ComeAgain::
#if GERMAN
	.string "In Ordnung.\n"
	.string "Schau wieder vorbei.$"
#else
	.string "Fine.\n"
	.string "Come again.$"
#endif

DayCare_Text_GoodToSeeYou::
#if GERMAN
	.string "Ach, du bist es! Schön, dich zu sehen.\n"
	.string "Deinen Pokémon kann es einfach nur gut\l"
	.string "gehen!$"
#else
	.string "Ah, it's you!\n"
	.string "Good to see you.\p"
	.string "Your POKéMON can only be doing\n"
	.string "good!$"
#endif

DayCare_Text_YourMonHasGrownXLevels::
#if GERMAN
	.string "Dein {STR_VAR_1} ist um {STR_VAR_2} Level\n"
	.string "gewachsen.$"
#else
	.string "By level, your {STR_VAR_1} has\n"
	.string "grown by {STR_VAR_2}.$"
#endif

DayCare_Text_YourPartyIsFull::
#if GERMAN
	.string "Dein Pokémon-Team ist vollzählig.\n"
	.string "Schaffe Platz und komm dann wieder.$"
#else
	.string "Your POKéMON party is full.\n"
	.string "Make room, then come see me.$"
#endif

DayCare_Text_TakeBackWhichMon::
#if GERMAN
	.string "Welches Pokémon möchtest du\n"
	.string "abholen?$"
#else
	.string "どっちの　ポケモンを　ひきとるかい？$"
#endif

DayCare_Text_ItWillCostX::
#if GERMAN
	.string "Wenn du dein {STR_VAR_1} mitnehmen willst,\n"
	.string "kostet das ¥{STR_VAR_2}.$"
#else
	.string "If you want your {STR_VAR_1} back,\n"
	.string "it will cost ¥{STR_VAR_2}.$"
#endif

DayCare_Text_HeresYourMon::
#if GERMAN
	.string "Sehr schön!\n"
	.string "Hier ist dein Pokémon!$"
#else
	.string "Perfect!\n"
	.string "Here's your POKéMON.$"
#endif

DayCare_Text_TookBackMon::
#if GERMAN
	.string "{PLAYER} hat {STR_VAR_1} von der\n"
	.string "Pensionsleiterin zurückerhalten.$"
#else
	.string "{PLAYER} took back {STR_VAR_1} from\n"
	.string "the DAY-CARE LADY.$"
#endif

DayCare_Text_YouHaveJustOneMon::
#if GERMAN
	.string "Oh! Du hast aber nur ein Pokémon.\p"
	.string "Komm einfach später wieder.$"
#else
	.string "Oh? But you have just one\n"
	.string "POKéMON.\p"
	.string "Come back another time.$"
#endif

DayCare_Text_TakeYourMonBack::
#if GERMAN
	.string "Möchtest du dein Pokémon wieder\n"
	.string "mitnehmen?$"
#else
	.string "Will you take your POKéMON back?$"
#endif

DayCare_Text_WhatWillYouBattleWith::
#if GERMAN
	.string "Wenn du das Pokémon hier lässt, womit\n"
	.string "willst du denn dann kämpfen?\p"
	.string "Komm einfach später wieder.$"
#else
	.string "If you leave me that POKéMON,\n"
	.string "what will you battle with?\p"
	.string "Come back another time.$"
#endif

DayCare_Text_Huh::
#if GERMAN
	.string "Wie?$"
#else
	.string "Huh?$"
#endif
