EventTicket_Text_OldSeaMapTooFar:
#if GERMAN
	.string "Nun, was gibt’s, Kindchen?\p"
	.string "Wie? Du besitzt eine alte, zerknitterte\n"
	.string "Karte?\p"
	.string "Zeig sie mir mal.\n"
	.string "… … … … …\l"
	.string "…\p"
	.string "Junge, Junge. Das ist aber weit weg. Ich\n"
	.string "glaube nicht, dass ich dir helfen kann…$"
#else
	.string "What's up, youngster?\p"
	.string "What, it's you who's supposed to have\n"
	.string "a tattered old map?\p"
	.string "Let's have a look.\n"
	.string "… … … … … …\p"
	.string "Boy, this is quite a ways away.\n"
	.string "I'm afraid I can't help you…$"
#endif

EventTicket_Text_BrineyHoldOnASecond:
#if GERMAN
	.string "Brack: Warte einen Moment!\p"
	.string "Warum sollte ich jemandem Hilfe\n"
	.string "verweigern, dem ich so viel zu verdanken\l"
	.string "habe?$"
#else
	.string "BRINEY: Hold on a second!\p"
	.string "What's the idea of turning down\n"
	.string "someone that I owe so much to?$"
#endif

EventTicket_Text_BrineyLetsSail:
#if GERMAN
	.string "{PLAYER}{KUN}, es tut mir schrecklich Leid!\p"
	.string "Du hast mich um Hilfe gebeten und ich\n"
	.string "hätte dich beinahe im Stich gelassen.\p"
	.string "Nun, lass mich das wieder hinbiegen.\p"
	.string "Wir setzen sofort Segel!\p"
	.string "Schauen wir auf die alte Karte.\n"
	.string "Wo wir die Insel finden.$"
#else
	.string "{PLAYER}{KUN}, I'm terribly sorry.\p"
	.string "You came to me seeking my help,\n"
	.string "and we almost turned you away.\p"
	.string "Well, let me make things right.\p"
	.string "We'll sail right away, of course!\p"
	.string "Let's find this island on\n"
	.string "this OLD SEA MAP!$"
#endif

EventTicket_Text_OddTicketGetOnBoard:
#if GERMAN
	.string "Ach, du besitzt dieses komische Ticket?\p"
	.string "Willst du zu dieser Insel, die weit, weit\n"
	.string "weg ist?\p"
	.string "Niemand kann sagen, was uns dort\n"
	.string "erwartet…\p"
	.string "Und das bringt mein Seemannsblut\n"
	.string "in Wallung, so gespannt bin ich!\p"
	.string "Dann komm an Bord, Kindchen!$"
#else
	.string "Is it you who brought that odd\n"
	.string "ticket?\p"
	.string "Where you're trying to go is an island\n"
	.string "that's far, far away.\p"
	.string "No one knows what awaits there…\p"
	.string "The very thought excites my blood\n"
	.string "as a sailing man!\p"
	.string "Get on board, youngster!$"
#endif

FarawayIsland_Entrance_Text_SailorReturn:
#if GERMAN
	.string "Kapitän Brack ist manchmal\n"
	.string "unberechenbar…\p"
#if IS_HNS
	.string "Möchtest du zurück nach Oliviana\n"
	.string "City?$"
#else
	.string "Möchtest du zurück nach Seegrasulb\n"
	.string "City?$"
#endif
#else
	.string "CAPT. BRINEY can be so maddeningly\n"
	.string "fickle…\p"
#if IS_HNS
	.string "Do you want to return to OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif
#endif

BirthIsland_Harbor_Text_SailorReturn:
#if GERMAN
	.string "Diese Insel hat wirklich eine höchst\n"
	.string "merkwürdige Form, findest du nicht?\l"
#if IS_HNS
	.string "Möchtest du zurück nach Oliviana\l"
	.string "City?$"
#else
	.string "Möchtest du zurück nach Seegrasulb\l"
	.string "City?$"
#endif
#else
	.string "What an oddly shaped island, eh?\n"
#if IS_HNS
	.string "Do you want to return to OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif
#endif

EventTicket_Text_OddTicketsWhereTo:
#if GERMAN
	.string "Ach, du besitzt diese merkwürdigen\n"
	.string "Tickets.\p"
	.string "Hm… … …\p"
	.string "Damit kannst du zu diesen weit, weit\n"
	.string "entfernten Inseln fahren.\p"
	.string "Niemand weiß, was einen dort erwartet\n"
	.string "oder was dort alles passieren kann.\p"
	.string "Und das bringt mein Blut in Wallung, so\n"
	.string "spannend finde ich das.\p"
	.string "Dann komm an Bord, Kindchen!\n"
	.string "Wohin fahren wir zuerst?$"
#else
	.string "Is it you who brought those\n"
	.string "odd tickets?\p"
	.string "… … …Hm.\p"
	.string "These tickets will get you to islands\n"
	.string "that are far, far away.\p"
	.string "No one knows what awaits there,\n"
	.string "or what may happen there.\p"
	.string "The very thought excites my blood\n"
	.string "as a sailing man!\p"
	.string "Get on board, youngster!\n"
	.string "Where shall we sail first?$"
#endif

NavelRock_Harbor_Text_SailorReturn:
#if GERMAN
	.string "Hast du… Hast du gehört?\n"
	.string "Von dort unten kam ein Knurren.\p"
	.string "Bist du sicher, dass es nicht gefährlich\n"
	.string "ist? Sollten wir nicht lieber umkehren?$"
#else
	.string "Did… Did you hear that?\n"
	.string "That low growling from deep in there.\p"
	.string "Are you sure it's safe?\n"
	.string "Do you think we should leave?$"
#endif

FarawayIsland_Entrance_Text_Sign:
#if GERMAN
	.string "Die Schrift ist verblasst, so als sei sie\n"
	.string "vor uralten Zeiten geschrieben worden…\p"
	.string "“…ber, 6. Tag Sollte jemals wieder ein\n"
	.string "Mensch… seinen Fuß auf die Insel… ffe,\l"
	.string "dass es ein weichherziger Mens…\p"
	.string "…it dieser Hoffnung gehe i…$"
#else
	.string "The writing is fading as if it was\n"
	.string "written a long time ago…\p"
	.string "“…ber, 6th day\n"
	.string "If any human…sets foot here…\l"
	.string "again…et it be a kindhearted pers…\l"
	.string "…ith that hope, I depar…”$"
#endif

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"

