Trade_Text_LookingForMonWannaTradeForMon::
#if GERMAN
	.string "Ich suche nach {STR_VAR_1}!\p"
	.string "Tauschst du es gegen {STR_VAR_2}?$"
#else
	.string "I'm looking for the POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Wanna trade one for my\n"
	.string "{STR_VAR_2}?$"
#endif

Trade_Text_AwwOhWell::
#if GERMAN
	.string "Ach…\n"
	.string "Na gut.$"
#else
	.string "Awww!\n"
	.string "Oh, well…$"
#endif

Trade_Text_WhatThatsNoMon::
#if GERMAN
	.string "Was?\n"
	.string "Das ist aber kein {STR_VAR_1}!$"
#else
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"
#endif

Trade_Text_HeyThanks::
#if GERMAN
	.string "Hey, danke!$"
#else
	.string "Hey, thanks!$"
#endif

Trade_Text_IsntMyOldMonGreat::
#if GERMAN
	.string "Ist {STR_VAR_2} nicht cool?$"
#else
	.string "Isn't my old {STR_VAR_2} great?$"
#endif

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
#if GERMAN
	.string "Hallo!\p"
	.string "Willst du dein {STR_VAR_1} nicht\n"
	.string "gegen ein {STR_VAR_2} tauschen?$"
#else
	.string "Hello, there! Do you happen to\n"
	.string "have a {STR_VAR_1}?\p"
	.string "Would you agree to a trade for\n"
	.string "my {STR_VAR_2}?$"
#endif

Trade_Text_WellIfYouDontWantTo::
#if GERMAN
	.string "Wenn du nicht magst, kann man\n"
	.string "nichts machen!$"
#else
	.string "Well, if you don't want to…$"
#endif

Trade_Text_ThisIsntMon::
#if GERMAN
	.string "Hm?\n"
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Denk an mich, wenn du eins gefangen\n"
	.string "hast!$"
#else
	.string "Hmmm?\n"
	.string "This isn't a {STR_VAR_1}.\p"
	.string "Think of me if you get one.$"
#endif

Trade_Text_Thanks::
#if GERMAN
	.string "Danke!$"
#else
	.string "Thanks!$"
#endif

Trade_Text_HasTradedMonGrownStronger::
#if GERMAN
	.string "Das {STR_VAR_2}, das ich mit dir getauscht\n"
	.string "habe - ist es stärker geworden?$"
#else
	.string "The {STR_VAR_2} that I traded you,\n"
	.string "has it grown stronger?$"
#endif

Trade_Text_DoYouHaveMonWantToTradeForMon::
#if GERMAN
	.string "Besitzt du ein {STR_VAR_1}?\p"
	.string "Willst du es gegen {STR_VAR_2} tauschen?$"
#else
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"
#endif

Trade_Text_ThatsTooBad::
#if GERMAN
	.string "Schade!$"
#else
	.string "That's too bad.$"
#endif

Trade_Text_ThisIsNoMon::
#if GERMAN
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Komm wieder, wenn du eines besitzt!$"
#else
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, trade it with me.$"
#endif

Trade_Text_ThanksYoureAPal::
#if GERMAN
	.string "Vielen Dank!$"
#else
	.string "Thanks, you're a pal!$"
#endif

Trade_Text_HowIsMyOldMon::
#if GERMAN
	.string "Wie geht es {STR_VAR_2}?\p"
	.string "Mein {STR_VAR_1} fühlt sich super!$"
#else
	.string "How is my old {STR_VAR_2}?\n"
	.string "My {STR_VAR_1} is doing great!$"
#endif
