Route3_Text_ColtonRematchIntro::
#if GERMAN
	.string "Heh! Ich kenne dich aus dem\n"
	.string "Vertania-Wald!$"
#else
	.string "Hey!\n"
	.string "I saw you in VIRIDIAN FOREST!$"
#endif

Route3_Text_BenRematchIntro::
#if GERMAN
	.string "Überall sind Brennnesseln! Und ich\n"
	.string "trage Shorts! So ein Mist!$"
#else
	.string "Hi! I like shorts!\n"
	.string "They're comfy and easy to wear!\p"
	.string "You should be wearing shorts, too!$"
#endif

Route3_Text_JaniceRematchIntro::
#if GERMAN
	.string "Was starrst du mich so an?$"
#else
	.string "Excuse me!\n"
	.string "You keep looking at me, don't you?$"
#endif

Route3_Text_GregRematchIntro::
#if GERMAN
	.string "Bist du auch ein Trainer?\n"
	.string "Lass uns kämpfen!$"
#else
	.string "You're a TRAINER, aren't you?\n"
	.string "Let's get with it right away!$"
#endif

Route3_Text_SallyRematchIntro::
#if GERMAN
	.string "Warum schaust du mich so fasziniert\n"
	.string "an?$"
#else
	.string "That look you give me…\n"
	.string "It intrigues me so!$"
#endif

Route3_Text_CalvinRematchIntro::
#if GERMAN
	.string "Hehe! Ich habe meinem Bruder\n"
	.string "gesagt, er soll Shorts anziehen!$"
#else
	.string "Hey! What's wrong with you?\n"
	.string "You're still not wearing shorts!$"
#endif

Route3_Text_JamesRematchIntro::
#if GERMAN
	.string "Ich setzte beim Kampf gegen dich die\n"
	.string "Pokémon ein, die ich von Grund auf\l"
	.string "trainiert habe.$"
#else
	.string "I'll battle you with the POKéMON\n"
	.string "I started raising.$"
#endif

Route3_Text_RobinRematchIntro::
#if GERMAN
	.string "Iiih!\n"
	.string "Hast du mich gestoßen?$"
#else
	.string "Eek!\n"
	.string "Did you push me?$"
#endif

Route4_Text_CrissyRematchIntro::
#if GERMAN
	.string "Ich fange immer Pilz-Pokémon\n"
	.string "am Mondberg.$"
#else
	.string "I always catch mushroom POKéMON\n"
	.string "on MT. MOON.$"
#endif

Route6_Text_RickyRematchIntro::
#if GERMAN
	.string "Oh! Du bist dieses neugierige Kind,\n"
	.string "das uns belauscht hat.$"
#else
	.string "Oh! You're that nosy kid who\n"
	.string "eavesdropped on us!$"
#endif

Route6_Text_NancyRematchIntro::
#if GERMAN
	.string "Entschuldigung! Hatte ich dir nicht\n"
	.string "gesagt, dass dies ein Privatgespräch\l"
	.string "ist?\l"
	.string "Du solltest uns nicht belauschen, das\l"
	.string "gehört sich nicht!$"
#else
	.string "Excuse me! Didn't I tell you that\n"
	.string "this is a private conversation?\p"
	.string "You shouldn't be listening in,\n"
	.string "you uncouth person!$"
#endif

Route6_Text_KeigoRematchIntro::
#if GERMAN
	.string "Ich suche nach etwas Gutem, das kein\n"
	.string "Käfer-Pokémon ist, aber…$"
#else
	.string "I'm trying to find something good\n"
	.string "that's not a BUG POKéMON, but…$"
#endif

Route6_Text_JeffRematchIntro::
#if GERMAN
	.string "Häh!\n"
	.string "Du möchtest erneut mit mir kommen?$"
#else
	.string "Huh?\n"
	.string "You want to go with me again?$"
#endif

Route6_Text_IsabelleRematchIntro::
#if GERMAN
	.string "Kämpfen? Meinst du mich?\n"
	.string "Na gut!$"
#else
	.string "Me?\n"
	.string "Well, okay. I'll play this once.$"
#endif

Route6_Text_ElijahRematchIntro::
#if GERMAN
	.string "Heh, lange nicht gesehen!\n"
	.string "Geht es dir besser?$"
#else
	.string "Hey, long time!\n"
	.string "Have you gotten better?$"
#endif

Route8_Text_AidanRematchIntro::
#if GERMAN
	.string "Du weißt viel über Pokémon!\n"
	.string "Doch wie sieht es mit Chemie aus?$"
#else
	.string "You are good at POKéMON, but how\n"
	.string "is your chemistry grade?$"
#endif

Route8_Text_StanRematchIntro::
#if GERMAN
	.string "O.K.!\n"
	.string "Die Spiele mögen beginnen!$"
#else
	.string "All right!\n"
	.string "Let's play another game!$"
#endif

Route8_Text_GlennRematchIntro::
#if GERMAN
	.string "Um zu gewinnen, benötigst du eine\n"
	.string "gute Strategie!\p"
	.string "Befolgst du meinen Rat?$"
#else
	.string "You need strategy to win at\n"
	.string "battling.\p"
	.string "Are you following my advice?$"
#endif

Route8_Text_PaigeRematchIntro::
#if GERMAN
	.string "Ich habe viele Nidoran gefangen!\n"
	.string "Ich möchte nicht, dass sie sich\l"
	.string "entwickeln, aber…$"
#else
	.string "I've collected many NIDORAN.\n"
	.string "I don't want them to evolve, but…$"
#endif

Route8_Text_LeslieRematchIntro::
#if GERMAN
	.string "Die Schule macht Spaß! Pokémon zu\n"
	.string "trainieren aber auch!$"
#else
	.string "School is fun, but I still think\n"
	.string "POKéMON are fun, too.$"
#endif

Route8_Text_AndreaRematchIntro::
#if GERMAN
	.string "Mauzi ist so süß!\n"
	.string "Miau, miauz!$"
#else
	.string "MEOWTH and PERSIAN are so cute,\n"
	.string "meow, meow, meow!$"
#endif

Route8_Text_MeganRematchIntro::
#if GERMAN
	.string "Es mag dämlich aussehen, wie wir hier\n"
	.string "herumstehen, aber ich kann dennoch\l"
	.string "kämpfen!$"
#else
	.string "We may look silly standing here\n"
	.string "like this, but I can still battle.$"
#endif

Route8_Text_RichRematchIntro::
#if GERMAN
	.string "Ich bin ein weit herumgekommener\n"
	.string "Glücksspieler!$"
#else
	.string "I'm a rambling, gaming dude!\n"
	.string "I'm on a winning streak!$"
#endif

Route8_Text_JuliaRematchIntro::
#if GERMAN
	.string "Welches Pokémon ist süß, pummelig\n"
	.string "und kuschlig?$"
#else
	.string "What's a cute, round, and fluffy\n"
	.string "POKéMON?\p"
	.string "You already know, don't you?$"
#endif

Route8_Text_RicardoRematchIntro::
#if GERMAN
	.string "Mein Motorrad macht immer noch Mucken!$"
#else
	.string "My bike's still acting up, man.$"
#endif

Route8_Text_JarenRematchIntro::
#if GERMAN
	.string "O.k., Kiddie!\n"
	.string "Dieses Mal bin ich nicht so gnädig!$"
#else
	.string "Okay, kid!\n"
	.string "Don't expect mercy this time!$"
#endif

Route8_Text_EliRematchIntro::
#if GERMAN
	.string "Nora: Zusammen sind wir jetzt\n"
	.string "noch stärker!$"
#else
	.string "ELI: Our twin power became even\n"
	.string "better!$"
#endif

Route8_Text_AnneRematchIntro::
#if GERMAN
	.string "Jo: Zwillinge sind doppelt stark!$"
#else
	.string "ANNE: Our twin power powered up!$"
#endif

Route9_Text_AliciaRematchIntro::
#if GERMAN
	.string "Kämpfen wir erneut?\n"
	.string "Dieses Mal bist du dran!$"
#else
	.string "We're to battle again?\n"
	.string "This time, you're mine!$"
#endif

Route9_Text_ChrisRematchIntro::
#if GERMAN
	.string "Ich habe nicht vergessen, dass du mit\n"
	.string "diesen bezaubernden Pokémon\l"
	.string "unterwegs bist.$"
#else
	.string "I haven't forgotten you were with\n"
	.string "those good-looking POKéMON.$"
#endif

Route9_Text_DrewRematchIntro::
#if GERMAN
	.string "Ich gehe über den Felstunnel nach\n"
	.string "Lavandia…\l"
	.string "Aber auf meinem Weg dorthin halten mich\l"
	.string "alle, denen ich begegne, auf…$"
#else
	.string "I'm taking ROCK TUNNEL to go to\n"
	.string "LAVENDER…\p"
	.string "But I keep getting stopped by\n"
	.string "everyone along the way…$"
#endif

Route9_Text_CaitlinRematchIntro::
#if GERMAN
	.string "Wage nicht, mich heute zu ärgern!\n"
	.string "Heute meinen wir es ernst!$"
#else
	.string "Don't you dare patronize me today!\n"
	.string "We're playing for keeps!$"
#endif

Route9_Text_JeremyRematchIntro::
#if GERMAN
	.string "Endlich kommt jemand!\n"
	.string "Mir war richtig langweilig!$"
#else
	.string "Bwahaha!\n"
	.string "Great! I was bored again, eh!$"
#endif

Route9_Text_BriceRematchIntro::
#if GERMAN
	.string "Du hast keine Chance, Kiddie!$"
#else
	.string "Hahaha!\n"
	.string "A little toughie, as always!$"
#endif

Route9_Text_BrentRematchIntro::
#if GERMAN
	.string "Jeden Tag stehe ich auf, um meine\n"
	.string "Pokémon von klein auf zu trainieren!$"
#else
	.string "I got up early every day to train\n"
	.string "my POKéMON from cocoons!$"
#endif

Route9_Text_AlanRematchIntro::
#if GERMAN
	.string "Hahahaha!\n"
	.string "Dieses Mal werde ich gewinnen!$"
#else
	.string "Hahahaha!\n"
	.string "I'll win this time!$"
#endif

Route9_Text_ConnerRematchIntro::
#if GERMAN
	.string "Du hast keine Chance gegen meine\n"
	.string "Käfer-Pokémon!$"
#else
	.string "Go win, my super BUG POKéMON!$"
#endif

Route10_Text_MarkRematchIntro::
#if GERMAN
	.string "Wow, du bist zurück? Vielleicht bist du\n"
	.string "auch ein Pokémaniac?\l"
	.string "Möchtest du meine Sammlung sehen?$"
#else
	.string "Wow, you came here again?\n"
	.string "Maybe you're a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"
#endif

Route10_Text_ClarkRematchIntro::
#if GERMAN
	.string "Ha-haha-hatschi!\n"
	.string "Ich kann nicht aufhören, zu niesen!$"
#else
	.string "Ha-hahah-ah-ha!\n"
	.string "I can't stop sneezing!$"
#endif

Route10_Text_HermanRematchIntro::
#if GERMAN
	.string "Hullo Kind!\n"
	.string "Habe ich dir schon meine Pokémon\l"
	.string "gezeigt?$"
#else
	.string "Hi, kid!\n"
	.string "Did I show you my POKéMON?$"
#endif

Route10_Text_HeidiRematchIntro::
#if GERMAN
	.string "Ich bin erneut zu einer Pokémon-\n"
	.string "Arena gegangen.$"
#else
	.string "I went out to a POKéMON GYM again.\p"
	.string "…But I lost as usual.$"
#endif

Route10_Text_TrentRematchIntro::
#if GERMAN
	.string "Ahh! Die Bergluft ist so wunderbar\n"
	.string "erfrischend! Ich muss einfach hier\l"
	.string "bleiben!$"
#else
	.string "Ah!\n"
	.string "This mountain air is delicious!\l"
	.string "It's so good, I can't leave!$"
#endif

Route10_Text_CarolRematchIntro::
#if GERMAN
	.string "In meinem Kopf dreht sich schon\n"
	.string "alles. Ich bin zu lange gewandert…$"
#else
	.string "My head is starting to spin.\n"
	.string "I've been hiking for too long…$"
#endif

Route11_Text_HugoRematchIntro::
#if GERMAN
	.string "Sieg, Niederlage oder Remis?\n"
	.string "Auf in den Rückkampf!$"
#else
	.string "Win, lose, or draw!\n"
	.string "Now for our rematch!$"
#endif

Route11_Text_JasperRematchIntro::
#if GERMAN
	.string "Wettkämpfe!\n"
	.string "Ich kann ihnen nicht widerstehen!$"
#else
	.string "Competing is the ultimate thrill.\n"
	.string "I still can't get enough!$"
#endif

Route11_Text_EddieRematchIntro::
#if GERMAN
	.string "Du weißt Bescheid, oder?\n"
	.string "Los, aber wehe du mogelst!$"
#else
	.string "You know, right?\n"
	.string "Let's go, but don't cheat!$"
#endif

Route11_Text_BraxtonRematchIntro::
#if GERMAN
	.string "Guten Tag!\p"
	.string "Vorsicht!\n"
	.string "Ich verlege hier immer noch Kabel!$"
#else
	.string "Hi, there!\p"
	.string "But be careful!\n"
	.string "I'm still laying down some cables!$"
#endif

Route11_Text_DillonRematchIntro::
#if GERMAN
	.string "Ich bin schon seit geraumer Zeit\n"
	.string "Pokémon Trainer, also kann ich dich\l"
	.string "besiegen!$"
#else
	.string "I became a TRAINER a while ago.\n"
	.string "But, I think I can win.$"
#endif

Route11_Text_DirkRematchIntro::
#if GERMAN
	.string "Haha!\n"
	.string "Bisher habe ich noch nie verloren!\p"
	.string "… und falls doch, hätte ich das\n"
	.string "längst vergessen!$"
#else
	.string "Fwahaha!\n"
	.string "I have never lost!\p"
	.string "…And if I did, I've forgotten all\n"
	.string "about it!$"
#endif

Route11_Text_DarianRematchIntro::
#if GERMAN
	.string "Ich habe noch nie gewonnen…\p"
	.string "Vielleicht ist dies auch meine\n"
	.string "Bestimmung…$"
#else
	.string "I have never won before…\p"
	.string "Perhaps I am destined to remain\n"
	.string "that way…$"
#endif

Route11_Text_YasuRematchIntro::
#if GERMAN
	.string "In meiner Klasse bin ich der Beste!\n"
	.string "Ich trainiere Tag und Nacht!$"
#else
	.string "I'm the best in my class.\n"
	.string "I train every morning and night!$"
#endif

Route11_Text_BernieRematchIntro::
#if GERMAN
	.string "Nimm dich vor Hochspannung in\n"
	.string "Acht!$"
#else
	.string "Keep your eyes out for live wires!$"
#endif

Route11_Text_DaveRematchIntro::
#if GERMAN
	.string "Meine Pokémon müssten bereit sein!\n"
	.string "Dieses Mal gewinne ich!$"
#else
	.string "I raised my POKéMON carefully.\n"
	.string "They should be ready by now.\l"
	.string "This time, they should win, too.$"
#endif

Route12_Text_NedRematchIntro::
#if GERMAN
	.string "Cool!\n"
	.string "Mir ist etwas ins Netz gegangen!\l"
	.string "Dieses Mal aber wirklich!$"
#else
	.string "Yeah!\n"
	.string "I got a bite, here!\l"
	.string "Th-this might be the real thing!$"
#endif

Route12_Text_ChipRematchIntro::
#if GERMAN
	.string "Endlich bist du da!\n"
	.string "Als Angler muss man geduldig sein!$"
#else
	.string "You're finally here.\n"
	.string "Fishing is a waiting game.$"
#endif

Route12_Text_JustinRematchIntro::
#if GERMAN
	.string "Ich habe immer noch keinen Mondstein\n"
	.string "finden können!\l"
	.string "Hast du einen?$"
#else
	.string "Still can't find a MOON STONE…\n"
	.string "Have you found one?$"
#endif

Route12_Text_LucaRematchIntro::
#if GERMAN
	.string "Elektrizität war schon immer meine\n"
	.string "Stärke!\p"
	.string "Ich habe allerdings von Wasser-Pokémon\n"
	.string "keine Ahnung!$"
#else
	.string "Electricity has always been my\n"
	.string "specialty.\p"
	.string "I don't know a thing about POKéMON\n"
	.string "of the sea, though.$"
#endif

Route12_Text_HankRematchIntro::
#if GERMAN
	.string "Der Angelkönig gegen das Pokémon-\n"
	.string "Kind! Runde 2!$"
#else
	.string "The FISHING FOOL vs. POKéMON KID!\n"
	.string "Another round, fight!$"
#endif

Route12_Text_ElliotRematchIntro::
#if GERMAN
	.string "Versteh mich nicht falsch…\n"
	.string "Ich liebe das Angeln, dennoch würde ich\l"
	.string "lieber arbeiten…\l"
	.string "… das Angeln aufzugeben ist schwer!$"
#else
	.string "I love fishing, don't get me wrong.\n"
	.string "But, I wish I had more work…\l"
	.string "…It's hard to give up fishing!$"
#endif

Route12_Text_AndrewRematchIntro::
#if GERMAN
	.string "Was ich fange?\p"
	.string "Das wirst du nie herausfinden, wenn\n"
	.string "du mich nicht schlägst.$"
#else
	.string "What's catching?\p"
	.string "You'll never know unless you beat\n"
	.string "me!$"
#endif

Route12_Text_JesRematchIntro::
#if GERMAN
	.string "Deniz: Gewinne ich heute, werde\n"
	.string "ich Sira einen Antrag machen!$"
#else
	.string "JES: I'll win here today and\n"
	.string "propose to my GIA.$"
#endif

Route12_Text_GiaRematchIntro::
#if GERMAN
	.string "Sira: Heh, Deniz…\n"
	.string "Ich habe jetzt schon so lange\l"
	.string "gewartet.\l"
	.string "Falls wir heute gewinnen, werden wir\l"
	.string "heiraten!$"
#else
	.string "GIA: Hey, JES…\n"
	.string "I've been waiting a long time now.\p"
	.string "If we win today, I'll marry you!$"
#endif

Route13_Text_SebastianRematchIntro::
#if GERMAN
	.string "Meine Vogel-Pokémon erinnern sich an\n"
	.string "dich!$"
#else
	.string "My bird POKéMON remember you!$"
#endif

Route13_Text_SusieRematchIntro::
#if GERMAN
	.string "Ich wollte als Kind der beste\n"
	.string "Trainer sein!$"
#else
	.string "I want to be the best TRAINER \n"
	.string "while I'm a kid!$"
#endif

Route13_Text_ValerieRematchIntro::
#if GERMAN
	.string "Wow!\n"
	.string "Du hast noch mehr coole Orden!$"
#else
	.string "Wow!\n"
	.string "You got more cool BADGES!$"
#endif

Route13_Text_GwenRematchIntro::
#if GERMAN
	.string "Meine niedlichen Pokémon möchten\n"
	.string "dich erneut gern kennen lernen.$"
#else
	.string "My cutely grown POKéMON wish to\n"
	.string "become reacquainted with you.$"
#endif

Route13_Text_AlmaRematchIntro::
#if GERMAN
	.string "Ich habe meine Ersparnisse\n"
	.string "zusammengekratzt und mehr Carbon\l"
	.string "gekauft.$"
#else
	.string "I cleaned out my savings and\n"
	.string "bought more CARBOS.$"
#endif

Route13_Text_PerryRematchIntro::
#if GERMAN
	.string "Dieses Mal werde ich nicht verlieren!\n"
	.string "Ich bin unterwegs und habe Rückenwind…$"
#else
	.string "I'm not going to lose this time.\n"
	.string "The wind's blowing my way!$"
#endif

Route13_Text_LolaRematchIntro::
#if GERMAN
	.string "Oh, du bist zurück!\p"
	.string "Natürlich trete ich erneut gegen\n"
	.string "dich an!$"
#else
	.string "Oh, you're back?\p"
	.string "Sure, I'll play again with you,\n"
	.string "sweetie.$"
#endif

Route13_Text_SheilaRematchIntro::
#if GERMAN
	.string "Kannst du nicht einfach vergessen,\n"
	.string "dass du gegen mich gekämpft hast?$"
#else
	.string "Can't you forget that you battled\n"
	.string "with me?$"
#endif

Route13_Text_JaredRematchIntro::
#if GERMAN
	.string "Was glotzt du so?$"
#else
	.string "What're you starin' at?$"
#endif

Route13_Text_RobertRematchIntro::
#if GERMAN
	.string "Meine Vogel-Pokémon begleiten\n"
	.string "mich immer!$"
#else
	.string "I always go with bird POKéMON.\n"
	.string "I've dedicated myself to them.$"
#endif

Route14_Text_CarterRematchIntro::
#if GERMAN
	.string "Ich habe meinen Pokémon mit TMs gute\n"
	.string "Attacken beigebracht.$"
#else
	.string "I used TMs to teach good moves\n"
	.string "to my POKéMON.$"
#endif

Route14_Text_MitchRematchIntro::
#if GERMAN
	.string "Meine Vogel-Pokémon sind dieses\n"
	.string "Mal noch besser vorbereitet!$"
#else
	.string "My bird POKéMON should be ready\n"
	.string "for battle this time.$"
#endif

Route14_Text_BeckRematchIntro::
#if GERMAN
	.string "Setzt du TMs bei Pokémon ein?\n"
	.string "Sie einfach nur zu besitzen, macht\l"
	.string "keinen Sinn!$"
#else
	.string "Are you using TMs on POKéMON?\n"
	.string "Just holding them is useless.$"
#endif

Route14_Text_MarlonRematchIntro::
#if GERMAN
	.string "Hast du einem Vogel-Pokémon schon das\n"
	.string "Fliegen beigebracht?$"
#else
	.string "Have you taught your bird POKéMON\n"
	.string "how to FLY?\p"
	.string "You'll be able to soar with it into\n"
	.string "the sky! Give it a try.$"
#endif

Route14_Text_DonaldRematchIntro::
#if GERMAN
	.string "Die Legende der Illusionen mit Flügeln…\n"
	.string "Du hast davon gehört, oder?$"
#else
	.string "The legend of the winged mirages…\n"
	.string "You've heard it, right?$"
#endif

Route14_Text_BennyRematchIntro::
#if GERMAN
	.string "Ich will nicht unbedingt, aber lass\n"
	.string "uns dennoch kämpfen!$"
#else
	.string "I'm really not into it, but okay.\n"
	.string "Let's go!$"
#endif

Route14_Text_LukasRematchIntro::
#if GERMAN
	.string "Heh, ich kenne dich!\p"
	.string "Los, los! Lass uns kämpfen. Auf in\n"
	.string "den Kampf! Los!$"
#else
	.string "Hey!\n"
	.string "I remember you!\p"
	.string "C'mon, c'mon.\n"
	.string "Let's go, let's go, let's go!$"
#endif

Route14_Text_IsaacRematchIntro::
#if GERMAN
	.string "Du schon wieder? Schnauze und los!$"
#else
	.string "You're here again, huh?\n"
	.string "Shut up and battle.$"
#endif

Route14_Text_GeraldRematchIntro::
#if GERMAN
	.string "Wir kommen öfter her, weil es hier\n"
	.string "so unglaublich viel Platz gibt!$"
#else
	.string "We've been riding here because of\n"
	.string "the wide-open spaces.$"
#endif

Route14_Text_MalikRematchIntro::
#if GERMAN
	.string "Ein Pokémon-Kampf?\n"
	.string "Cool! Leg los, Kiddie!$"
#else
	.string "POKéMON battle, right?\n"
	.string "Cool! Rumble!$"
#endif

Route14_Text_KiriRematchIntro::
#if GERMAN
	.string "Berta: Enke, ich hoffe, wir gewinnen!$"
#else
	.string "KIRI: JAN, I hope we win today.$"
#endif

Route14_Text_JanRematchIntro::
#if GERMAN
	.string "Enke: Berta, los!\n"
	.string "Dieses Mal gewinnen wir sicher!$"
#else
	.string "JAN: KIRI, here we go!\n"
	.string "Let's win for sure this time!$"
#endif

Route15_Text_KindraRematchIntro::
#if GERMAN
	.string "Wunderbar! Ich werde mit den\n"
	.string "getauschten Pokémon weiterhin mein\l"
	.string "Glück versuchen.$"
#else
	.string "I'm going to keep battling with the\n"
	.string "POKéMON I got in trades.$"
#endif

Route15_Text_BeckyRematchIntro::
#if GERMAN
	.string "Du siehst lammfromm aus!\n"
	.string "Dann habe ich eine Chance!\p"
	.string "Einen Versuch habe ich noch!$"
#else
	.string "You look gentle, so I think I can\n"
	.string "beat you.\p"
	.string "I'll give it one more go!$"
#endif

Route15_Text_EdwinRematchIntro::
#if GERMAN
	.string "Vogel-Pokémon versammeln sich, wenn\n"
	.string "ich pfeife!\l"
	.string "Sie sind bewundernswert süß!$"
#else
	.string "When I whistle, bird POKéMON\n"
	.string "gather around.\p"
	.string "They're amazingly cute!$"
#endif

Route15_Text_ChesterRematchIntro::
#if GERMAN
	.string "Hmm? Meine Vögel erschaudern?\n"
	.string "Moment, du bist doch dieser Trainer…$"
#else
	.string "Hmm? My birds are shivering!\n"
	.string "Wait, aren't you that TRAINER…$"
#endif

Route15_Text_GraceRematchIntro::
#if GERMAN
	.string "Du bist aber niedlich!\n"
	.string "Wie ein kleines, süßes Pokémon!\l"
	.string "Jetzt erinnere ich mich an dich!$"
#else
	.string "Oh, you're a little cutie!\n"
	.string "So like a darling POKéMON!\l"
	.string "I remember you now!$"
#endif

Route15_Text_OliviaRematchIntro::
#if GERMAN
	.string "Ich trainiere Pokémon, weil ich\n"
	.string "alleine lebe!\p"
	.string "Das hat sich nicht geändert!$"
#else
	.string "I raise POKéMON for protection\n"
	.string "because I live alone.\p"
	.string "That hasn't changed.$"
#endif

Route15_Text_ErnestRematchIntro::
#if GERMAN
	.string "Heh, Kind!\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, kid! C'mon!\n"
	.string "I got these off some loser!$"
#endif

Route15_Text_AlexRematchIntro::
#if GERMAN
	.string "Her mit deinen Moneten! Wenn du\n"
	.string "verlierst, gibst du mir dein Geld!$"
#else
	.string "Fork over all your cash when you\n"
	.string "lose to me, kid!$"
#endif

Route15_Text_CeliaRematchIntro::
#if GERMAN
	.string "Pokémon zu tauschen ist wirklich\n"
	.string "cool!$"
#else
	.string "What's cool and happening?\n"
	.string "Trading POKéMON, of course.$"
#endif

Route15_Text_YazminRematchIntro::
#if GERMAN
	.string "Möchtest du noch einmal mit meinen\n"
	.string "Pokémon spielen?$"
#else
	.string "Want to play with my POKéMON\n"
	.string "again?$"
#endif

Route15_Text_MyaRematchIntro::
#if GERMAN
	.string "Eva: Hallo, wir treffen uns öfter,\n"
	.string "nicht wahr?\p"
	.string "Hilfst du mir erneut, meinen kleinen\n"
	.string "Bruder zu trainieren?$"
#else
	.string "MYA: Hi, we keep meeting,\n"
	.string "don't we?\p"
	.string "Help me train my little brother\n"
	.string "again?$"
#endif

Route15_Text_RonRematchIntro::
#if GERMAN
	.string "Sergio: Meine Schwester ist noch\n"
	.string "stärker geworden…$"
#else
	.string "RON: My sister's gotten more\n"
	.string "powerful…$"
#endif

Route16_Text_LaoRematchIntro::
#if GERMAN
	.string "Was willst du?$"
#else
	.string "What do you want?$"
#endif

Route16_Text_KojiRematchIntro::
#if GERMAN
	.string "Du besitzt ein schönes Fahrrad!\n"
	.string "Her damit!$"
#else
	.string "Nice BIKE!\n"
	.string "Hand it over quick!$"
#endif

Route16_Text_LukeRematchIntro::
#if GERMAN
	.string "Komm lass uns spielen, Hasenfuß! Ich\n"
	.string "weiß jetzt mit dir umzugehen!$"
#else
	.string "Come out and play, little mouse.\n"
	.string "I'll treat you right!$"
#endif

Route16_Text_HideoRematchIntro::
#if GERMAN
	.string "Heh, warte doch! Erst rufst du\n"
	.string "mich und dann haust du ab.$"
#else
	.string "Hey, wait a second!\n"
	.string "Don't call me and then run away!$"
#endif

Route16_Text_CamronRematchIntro::
#if GERMAN
	.string "Ich habe Hunger und bin fies! Ich\n"
	.string "brauche jetzt wirklich einen Sandsack!$"
#else
	.string "I'm feeling hungry and mean!\n"
	.string "I really need a punching bag!$"
#endif

Route16_Text_RubenRematchIntro::
#if GERMAN
	.string "Heh, du!\n"
	.string "Wir werden uns jetzt amüsieren!$"
#else
	.string "Hey, there!\n"
	.string "We'll have ourselves a good time!$"
#endif

Route16_Text_JedRematchIntro::
#if GERMAN
	.string "Uwe: Bist du hier, um unsere grenzenlose\n"
	.string "Liebe zu sehen?$"
#else
	.string "JED: Are you here to see our\n"
	.string "love, which knows no bounds?$"
#endif

Route16_Text_LeaRematchIntro::
#if GERMAN
	.string "Lena: Manchmal macht mir die Intensität\n"
	.string "unserer Liebe Angst!$"
#else
	.string "LEA: Sometimes, the intensity of\n"
	.string "our love scares me.$"
#endif

Route17_Text_RaulRematchIntro::
#if GERMAN
	.string "Ich hab es dir doch schon gesagt!\n"
	.string "Es lohnt sich nicht, Kinder\l"
	.string "auszurauben!$"
#else
	.string "I told you, there's no getting rich\n"
	.string "quick in battling kids.$"
#endif

Route17_Text_IsaiahRematchIntro::
#if GERMAN
	.string "Ich bin mächtig stolz auf mein\n"
	.string "Team, Kiddie! Komm schon!$"
#else
	.string "I'm mighty proud of my bod, kiddo.\n"
	.string "Come on!$"
#endif

Route17_Text_VirgilRematchIntro::
#if GERMAN
	.string "Gehst du spazieren?$"
#else
	.string "You out for a stroll?$"
#endif

Route17_Text_BillyRematchIntro::
#if GERMAN
	.string "Wir sind Biker, Könige des Highways!$"
#else
	.string "We're BIKERS!\n"
	.string "We rule the roads, man!$"
#endif

Route17_Text_NikolasRematchIntro::
#if GERMAN
	.string "Voltobal wird dich heute ernsthaft\n"
	.string "frizzeln!$"
#else
	.string "VOLTORB's going to seriously\n"
	.string "electrify you today!$"
#endif

Route17_Text_ZeekRematchIntro::
#if GERMAN
	.string "Ich habe mein Pokémon trainiert, aber\n"
	.string "es entwickelt sich einfach nicht!\l"
	.string "Warum?$"
#else
	.string "I leveled up my POKéMON, but it\n"
	.string "absolutely won't evolve. Why?$"
#endif

Route17_Text_JamalRematchIntro::
#if GERMAN
	.string "Ich muss ein wenig abnehmen und\n"
	.string "wirklich mehr trainieren!$"
#else
	.string "Gaah! I really need to exercise\n"
	.string "and seriously trim some flab!$"
#endif

Route17_Text_CoreyRematchIntro::
#if GERMAN
	.string "Sei ein Rebell!$"
#else
	.string "Be a rebel!$"
#endif

Route17_Text_JaxonRematchIntro::
#if GERMAN
	.string "Du besitzt ein schickes Fahrrad!\n"
	.string "Fährt es sich gut?$"
#else
	.string "Yep, that's a nice BIKE!\n"
	.string "How's it handle?$"
#endif

Route17_Text_WilliamRematchIntro::
#if GERMAN
	.string "Zieh Leine!\n"
	.string "Ich bin erschöpft!$"
#else
	.string "Get lost, kid!\n"
	.string "I'm bushed!$"
#endif

Route18_Text_WiltonRematchIntro::
#if GERMAN
	.string "Ich suche in jeder neuen Wiese,\n"
	.string "die ich finde, nach neuen Pokémon!\p"
	.string "Das ist nicht immer leicht…$"
#else
	.string "I've been checking every grassy\n"
	.string "area for new POKéMON.\p"
	.string "But it's not always easy…$"
#endif

Route18_Text_RamiroRematchIntro::
#if GERMAN
	.string "Guruguu!\n"
	.string "Wird mein Vogellockruf besser?$"
#else
	.string "Koorukukukoo!\n"
	.string "Is my birdcall getting better?$"
#endif

Route18_Text_JacobRematchIntro::
#if GERMAN
	.string "Ich sagte dir bereits, das hier ist mein\n"
	.string "Gebiet! Sieh zu, dass du Land gewinnst!$"
#else
	.string "I warned you before, this is my\n"
	.string "turf!\p"
	.string "I don't want you coming around.$"
#endif

Route19_Text_RichardRematchIntro::
#if GERMAN
	.string "Ich bin fast genug aufgewärmt,\n"
	.string "um draußen zu schwimmen!$"
#else
	.string "I'm almost warmed up to go\n"
	.string "out for a swim.$"
#endif

Route19_Text_ReeceRematchIntro::
#if GERMAN
	.string "Warte! Sonst bekommst du einen\n"
	.string "Herzinfarkt!$"
#else
	.string "Wait! Slow down!\n"
	.string "What if you have a heart attack?$"
#endif

Route19_Text_MatthewRematchIntro::
#if GERMAN
	.string "Ich gehe gerne schwimmen!\n"
	.string "Du bist wohl eher für das Surfen zu\l"
	.string "begeistern, oder?$"
#else
	.string "I love swimming!\n"
	.string "I guess you're the surfing type.$"
#endif

Route19_Text_DouglasRematchIntro::
#if GERMAN
	.string "Was mag sich hinter dem Horizont\n"
	.string "verbergen? Hast du es bereits\l"
	.string "herausgefunden?$"
#else
	.string "What's beyond the horizon?\n"
	.string "Have you seen?$"
#endif

Route19_Text_DavidRematchIntro::
#if GERMAN
	.string "Ich wollte schon wieder nach Pokémon\n"
	.string "tauchen und wieder war es keine gute\l"
	.string "Idee!$"
#else
	.string "I tried diving for POKéMON again,\n"
	.string "but it was a no-go like before.$"
#endif

Route19_Text_TonyRematchIntro::
#if GERMAN
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!\p"
	.string "… wie meine Niederlage gegen dich!$"
#else
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.\p"
	.string "…Like losing to you the last time!$"
#endif

Route19_Text_AnyaRematchIntro::
#if GERMAN
	.string "Du reitest immer auf deinem Pokémon…\p"
	.string "Das sieht so entspannend aus! Kann\n"
	.string "ich es haben, wenn ich gewinne?$"
#else
	.string "You always get to ride your\n"
	.string "POKéMON…\p"
	.string "It looks so relaxing.\n"
	.string "Can I have it if I win?$"
#endif

Route19_Text_AliceRematchIntro::
#if GERMAN
	.string "Schwimmen ist herrlich!\n"
	.string "Sonnenbrand nicht!$"
#else
	.string "Swimming's great!\n"
	.string "Sunburns aren't!$"
#endif

Route19_Text_AxleRematchIntro::
#if GERMAN
	.string "Diese Gewässer sind trügerisch!\n"
	.string "Du hättest nicht wieder herkommen\l"
	.string "dürfen!$"
#else
	.string "These waters are treacherous!\n"
	.string "You shouldn't come back here!$"
#endif

Route19_Text_ConnieRematchIntro::
#if GERMAN
	.string "Ich bin mit meinen Freunden hierher\n"
	.string "geschwommen…\l"
	.string "Müssen wir wirklich erneut kämpfen?$"
#else
	.string "I swam here with my friends…\n"
	.string "I'm tired…\l"
	.string "Must we really battle again?$"
#endif

Route19_Text_LiaRematchIntro::
#if GERMAN
	.string "Nora: Du weißt, dass mein Bruder\n"
	.string "erst vor kurzem ein Trainer wurde!\p"
	.string "Ich will, dass er besser wird, also\n"
	.string "brauche ich deine Hilfe!$"
#else
	.string "LIA: You know my brother just\n"
	.string "became a TRAINER, right?\p"
	.string "I want to make him better, so I\n"
	.string "need your help again.$"
#endif

Route19_Text_LucRematchIntro::
#if GERMAN
	.string "Tom: Meine große Schwester hat mir\n"
	.string "alles über Pokémon beigebracht!\p"
	.string "Ich frage mich, ob ich besser bin?$"
#else
	.string "LUC: My big sis taught me all\n"
	.string "about POKéMON.\p"
	.string "I wonder if I'm better?$"
#endif

Route20_Text_BarryRematchIntro::
#if GERMAN
	.string "Das Wasser ist hier sehr flach.$"
#else
	.string "The water is shallow here.\n"
	.string "There are many people swimming.$"
#endif

Route20_Text_ShirleyRematchIntro::
#if GERMAN
	.string "Bist du neidisch, dass ich meinen Urlaub\n"
	.string "auf den Seeschaum-Inseln verbringe?$"
#else
	.string "Are you jealous that I'm\n"
	.string "vacationing on SEAFOAM?$"
#endif

Route20_Text_TiffanyRematchIntro::
#if GERMAN
	.string "Ich lasse mich gerne mit den Fischen\n"
	.string "treiben!$"
#else
	.string "I love floating with the fishes\n"
	.string "here among the waves.$"
#endif

Route20_Text_IreneRematchIntro::
#if GERMAN
	.string "Bist du auch auf Urlaub hier?$"
#else
	.string "Were you on vacation, too?$"
#endif

Route20_Text_DeanRematchIntro::
#if GERMAN
	.string "Schau dir meinen gestählten Körper\n"
	.string "ruhig an!\p"
	.string "Er ist noch durchtrainierter jetzt!$"
#else
	.string "Check out my physique!\p"
	.string "It's even more buff than ever\n"
	.string "before!$"
#endif

Route20_Text_DarrinRematchIntro::
#if GERMAN
	.string "Warum reitest du ein Pokémon?\n"
	.string "Kannst du noch nicht schwimmen?$"
#else
	.string "Why are you riding a POKéMON?\n"
	.string "Haven't you learned to swim yet?$"
#endif

Route20_Text_RogerRematchIntro::
#if GERMAN
	.string "Mein Vogel-Pokémon hat mich hierher\n"
	.string "getragen!$"
#else
	.string "I rode my bird POKéMON here.$"
#endif

Route20_Text_NoraRematchIntro::
#if GERMAN
	.string "Mein Freund hat mir große Perlen\n"
	.string "gegeben und sie sind immer größer\l"
	.string "geworden!$"
#else
	.string "My boyfriend gave me big pearls.\n"
	.string "And, they've grown bigger!$"
#endif

Route20_Text_MissyRematchIntro::
#if GERMAN
	.string "Ich bin von der Zinnoberinsel\n"
	.string "herübergeschwommen!$"
#else
	.string "I swam here from CINNABAR ISLAND.\n"
	.string "It wasn't easy, like I said.$"
#endif

Route20_Text_MelissaRematchIntro::
#if GERMAN
	.string "Auf der Zinnoberinsel befindet\n"
	.string "sich ein Pokémon-Labor.$"
#else
	.string "CINNABAR, in the west, has a LAB\n"
	.string "for POKéMON.\p"
	.string "My daddy works there.$"
#endif

Route21_North_Text_RonaldRematchIntro::
#if GERMAN
	.string "Möchtest du wissen, ob die Fische\n"
	.string "beißen?$"
#else
	.string "You want to know if the fish are\n"
	.string "biting?$"
#endif

Route21_North_Text_WadeRematchIntro::
#if GERMAN
	.string "Ich habe schon wieder einen Großen\n"
	.string "gefangen! Willst du noch ein Match?$"
#else
	.string "I got a big haul again!\n"
	.string "Wanna go for it once more?$"
#endif

Route21_North_Text_SpencerRematchIntro::
#if GERMAN
	.string "Die See reinigt Körper und Seele!$"
#else
	.string "The sea cleanses my body and soul!$"
#endif

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
#if GERMAN
	.string "Auch heute bin ich wieder\n"
	.string "zum Schwimmen hier!$"
#else
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"
#endif

Route21_South_Text_JackRematchIntro::
#if GERMAN
	.string "Ich habe meine Pokémon im Wasser\n"
	.string "gefangen und dort trainiere ich auch\l"
	.string "mit ihnen.$"
#else
	.string "I caught my POKéMON at sea.\n"
	.string "And that's where I train them.$"
#endif

Route21_South_Text_JeromeRematchIntro::
#if GERMAN
	.string "Ich nehme gerade an einem weiteren\n"
	.string "Triathlon teil!$"
#else
	.string "Right now, I'm in another triathlon\n"
	.string "meet!$"
#endif

Route21_South_Text_RolandRematchIntro::
#if GERMAN
	.string "Ahh!\n"
	.string "Genieße die Sonne und den Wind!$"
#else
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"
#endif

Route21_South_Text_ClaudeRematchIntro::
#if GERMAN
	.string "Heh, halte dich zurück!\n"
	.string "Du verscheuchst immer die Fische!$"
#else
	.string "Hey, cut it out already.\n"
	.string "You always scare away the fish!$"
#endif

Route21_South_Text_NolanRematchIntro::
#if GERMAN
	.string "Leiste mir Gesellschaft, bis etwas\n"
	.string "anbeißt!$"
#else
	.string "Keep me company till I get a hit.$"
#endif

Route21_North_Text_LilRematchIntro::
#if GERMAN
	.string "Ewe: Häh? Ein Kampf? Schon wieder?\n"
	.string "Tobi, schaffst du das nicht alleine?$"
#else
	.string "LIL: Huh? A battle again?\n"
	.string "IAN, can't you do it alone?$"
#endif

Route21_North_Text_IanRematchIntro::
#if GERMAN
	.string "Tobi: Meine Schwester ist faul!\n"
	.string "Hilf mir, sie in Form zu bringen!$"
#else
	.string "IAN: My sis is still a slob.\n"
	.string "Help me get her into shape!$"
#endif

Route25_Text_JoeyRematchIntro::
#if GERMAN
	.string "Ich werde nicht verlieren, während ich\n"
	.string "hier bin!$"
#else
	.string "I won't lose while I'm here!$"
#endif

Route25_Text_DanRematchIntro::
#if GERMAN
	.string "Ich habe in Orania City mit meinem Papa\n"
	.string "auf der M.S. Anne eine Party besucht!$"
#else
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"
#endif

Route25_Text_FlintRematchIntro::
#if GERMAN
	.string "Ich bin richtig cool!\n"
	.string "Ich habe eine Freundin!\p"
	.string "Ich beweise ihr dieses Mal, wie cool ich\n"
	.string "wirklich bin!$"
#else
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!\p"
	.string "I'll show her how cool I am for\n"
	.string "sure this time!$"
#endif

Route25_Text_KelseyRematchIntro::
#if GERMAN
	.string "Hallo!\n"
	.string "Mein Freund ist cool!\l"
	.string "Ich fühle mich heute gut!$"
#else
	.string "Hi!\n"
	.string "My boyfriend is cool!\l"
	.string "My conditioning's good today!$"
#endif

Route25_Text_ChadRematchIntro::
#if GERMAN
	.string "Ich hatte dieses Gefühl…\n"
	.string "Ich wusste, dass wir erneut miteinander\l"
	.string "kämpfen würden!$"
#else
	.string "I had this feeling…\n"
	.string "I knew I had to battle you again!$"
#endif

Route25_Text_HaleyRematchIntro::
#if GERMAN
	.string "Meine Freundin hat so ein süßes\n"
	.string "Pokémon! Ich bin furchtbar neidisch!$"
#else
	.string "My friend has many cute POKéMON.\n"
	.string "I'm so jealous!$"
#endif

Route25_Text_FranklinRematchIntro::
#if GERMAN
	.string "Ich habe auf dem Mondberg trainiert\n"
	.string "und immer noch Benzin im Tank!$"
#else
	.string "I just trained up on MT. MOON,\n"
	.string "but I've still got gas in the tank!$"
#endif

Route25_Text_NobRematchIntro::
#if GERMAN
	.string "Ich bin auf dem Weg zu einem Pokémaniac\n"
	.string "am Kap!\l"
	.string "Kennst du seine Sammlung?$"
#else
	.string "A POKéMANIAC lives on the cape.\n"
	.string "Have you seen his collection?$"
#endif

Route25_Text_WayneRematchIntro::
#if GERMAN
	.string "Du möchtest wieder zu Bill?\n"
	.string "Aber erst wird gekämpft!$"
#else
	.string "You're going to see BILL again?\n"
	.string "First, we battle!$"
#endif

Route24_Text_ShaneRematchIntro::
#if GERMAN
	.string "Ich habe deine Vorstellung aus dem\n"
	.string "Gras heraus beobachtet!$"
#else
	.string "I saw your feat from the grass!$"
#endif

Route24_Text_EthanRematchIntro::
#if GERMAN
	.string "O.k.!\n"
	.string "Dich mache ich platt!$"
#else
	.string "Okay!\n"
	.string "I'll stomp you!$"
#endif

Route24_Text_ReliRematchIntro::
#if GERMAN
	.string "Du siehst immer so beschäftigt aus!\n"
	.string "Wirst du nicht müde?$"
#else
	.string "You always look so busy…\n"
	.string "Aren't you getting tired?$"
#endif

Route24_Text_TimmyRematchIntro::
#if GERMAN
	.string "Du musst es wirklich lieben, zur\n"
	.string "Nugget-brücke zu kommen.$"
#else
	.string "You really must love coming to\n"
	.string "NUGGET BRIDGE.$"
#endif

Route24_Text_AliRematchIntro::
#if GERMAN
	.string "Als wir kämpften…\p"
	.string "Obwohl ich nur an zweiter Stelle\n"
	.string "stand, war ich die Beste, oder?$"
#else
	.string "The time we battled…\p"
	.string "Even though I was the second in\n"
	.string "line, I was the best, wasn't I?$"
#endif

Route24_Text_CaleRematchIntro::
#if GERMAN
	.string "Die Leute nennen das hier die\n"
	.string "Nugget-brücke!\p"
	.string "Du hast uns bereits besiegt, also\n"
	.string "darfst du an der Herausforderung nicht\l"
	.string "mehr teilnehmen…\l"
	.string "… aber du darfst gerne wieder mit uns\l"
	.string "kämpfen!$"
#else
	.string "People call this the NUGGET\n"
	.string "BRIDGE!\p"
	.string "You've already beaten us, so you're\n"
	.string "not allowed to take the challenge…\p"
	.string "…But, you're welcome to battle with\n"
	.string "us again.$"
#endif

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
#if GERMAN
	.string "Beim Entspannen habe ich mich von den\n"
	.string "Wellen treiben lassen und die Zeit\l"
	.string "vergessen…$"
#else
	.string "Lying back, rocked by the waves…\n"
	.string "I don't notice time slipping by…$"
#endif

OneIsland_KindleRoad_Text_MariaRematchIntro::
#if GERMAN
	.string "Das Wetter ist fantastisch! Ich\n"
	.string "versuche es nicht zu vermiesen!$"
#else
	.string "The weather's gorgeous!\n"
	.string "I'll try not to spoil it.$"
#endif

OneIsland_KindleRoad_Text_AbigailRematchIntro::
#if GERMAN
	.string "Mein Sonnenbrand fängt an zu\n"
	.string "schmerzen…$"
#else
	.string "My sunburn is starting to hurt…$"
#endif

OneIsland_KindleRoad_Text_FinnRematchIntro::
#if GERMAN
	.string "Der Berg des Feuervogels wirft\n"
	.string "einen riesigen Schatten…$"
#else
	.string "The fire bird's mountain casts\n"
	.string "a huge shadow…$"
#endif

OneIsland_KindleRoad_Text_GarrettRematchIntro::
#if GERMAN
	.string "Ich spüre genau, dass ich dieses Mal\n"
	.string "gewinnen kann!$"
#else
	.string "I have this strong feeling that\n"
	.string "I can win this time!$"
#endif

OneIsland_KindleRoad_Text_TommyRematchIntro::
#if GERMAN
	.string "Warte! Einen Moment noch!\n"
	.string "Ich bin sicher, dass ich einen Großen am\l"
	.string "Haken habe!$"
#else
	.string "Wait! Wait a second!\n"
	.string "I'm sure I've hooked a big one!$"
#endif

OneIsland_KindleRoad_Text_SharonRematchIntro::
#if GERMAN
	.string "Du hilfst mir erneut beim Training?$"
#else
	.string "You'll help me out with my\n"
	.string "training again?$"
#endif

OneIsland_KindleRoad_Text_TanyaRematchIntro::
#if GERMAN
	.string "Wir haben bis jetzt jeden Tag\n"
	.string "trainiert!$"
#else
	.string "We haven't missed a single day of\n"
	.string "training yet!$"
#endif

OneIsland_KindleRoad_Text_SheaRematchIntro::
#if GERMAN
	.string "Jeden Morgen vorm Frühstück schwimme\n"
	.string "ich um diese Insel…\l"
	.string "und das dreimal!$"
#else
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island…\l"
	.string "Three times!$"
#endif

OneIsland_KindleRoad_Text_HughRematchIntro::
#if GERMAN
	.string "Zieh dich kampfgemäß an!\n"
	.string "Zieh dich um, hab ich gesagt!$"
#else
	.string "Dress appropriately for battle!\n"
	.string "Lose that frivolous outfit, I said!$"
#endif

OneIsland_KindleRoad_Text_BryceRematchIntro::
#if GERMAN
	.string "Weißt du, dass in der Natur alles\n"
	.string "großartig schmeckt?$"
#else
	.string "You know, everything tastes great\n"
	.string "when you're out in the wild.$"
#endif

OneIsland_KindleRoad_Text_ClaireRematchIntro::
#if GERMAN
	.string "Ich habe erneut zu viel gegessen!\n"
	.string "Kämpfst du gegen uns, um ein wenig zu\l"
	.string "trainieren?$"
#else
	.string "I ate too much again, so will you\n"
	.string "battle us for some exercise?$"
#endif

OneIsland_KindleRoad_Text_KiaRematchIntro::
#if GERMAN
	.string "Heidi: Mein großer Bruder und ich\n"
	.string "sind eine grandiose Mischung!\p"
	.string "Dieses Mal verlieren wir nicht!$"
#else
	.string "KIA: My big brother and I make\n"
	.string "an awesome combination!\p"
	.string "We won't lose this time!$"
#endif

OneIsland_KindleRoad_Text_MikRematchIntro::
#if GERMAN
	.string "Dirk: An der Seite von Heidi habe ich vor\n"
	.string "nichts Angst!\p"
	.string "Dieses Mal beweisen wir es dir!$"
#else
	.string "MIK: Together with KIA, we're\n"
	.string "afraid of nothing!\p"
	.string "We'll prove it to you this time!$"
#endif

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
#if GERMAN
	.string "Sollen wir erneut kämpfen?$"
#else
	.string "Are we to battle again?$"
#endif

ThreeIsland_BondBridge_Text_VioletRematchIntro::
#if GERMAN
	.string "Wo kommst du her und wohin willst du?$"
#else
	.string "From where have you come, and\n"
	.string "where are you bound?$"
#endif

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
#if GERMAN
	.string "Ich möchte bald ohne Schwimmreifen\n"
	.string "schwimmen.$"
#else
	.string "I want to swim without my float\n"
	.string "ring soon.$"
#endif

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
#if GERMAN
	.string "Yay, yay!\n"
	.string "Pokémon!$"
#else
	.string "Yay, yay!\n"
	.string "POKéMON!$"
#endif

ThreeIsland_BondBridge_Text_TishaRematchIntro::
#if GERMAN
	.string "Oh, nein, habe ich es dir nicht\n"
	.string "bereits gesagt? Lass mich in Ruhe!$"
#else
	.string "Oh, no, didn't I tell you already?\n"
	.string "Please, stay away from me!$"
#endif

ThreeIsland_BondBridge_Text_JoyRematchIntro::
#if GERMAN
	.string "Ute: Wir sind jetzt stärker!\n"
	.string "Und zwar gewaltig stärker!$"
#else
	.string "JOY: We've gotten stronger!\n"
	.string "Lots and lots!$"
#endif

ThreeIsland_BondBridge_Text_MegRematchIntro::
#if GERMAN
	.string "Ida: Heute besiegst du uns nicht!$"
#else
	.string "MEG: You can't beat us today!$"
#endif

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
#if GERMAN
	.string "Oh, hallo!\p"
	.string "Trainierst du deine Pokémon in\n"
	.string "netter Umgebung?$"
#else
	.string "Oh, hello!\p"
	.string "Are you raising your POKéMON in a\n"
	.string "good environment?$"
#endif

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
#if GERMAN
	.string "Diese Hände werden heute den\n"
	.string "Sieg davontragen!$"
#else
	.string "With these hands, I will create\n"
	.string "my victory today.$"
#endif

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
#if GERMAN
	.string "Muss ich mich wiederholen?\n"
	.string "Ich male!\l"
	.string "Geh mir aus der Sicht!$"
#else
	.string "Must I repeat myself?\n"
	.string "I'm trying to paint.\l"
	.string "Please keep out of my sight!$"
#endif

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
#if GERMAN
	.string "Ich habe keinen Fortschritt gemacht…\n"
	.string "Ich kann immer noch nicht den richtigen\l"
	.string "Winkel finden…$"
#else
	.string "I haven't made any progress…\n"
	.string "I still can't get the right angle…$"
#endif

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
#if GERMAN
	.string "Du gibst mir erneut Gelegenheit,\n"
	.string "meine Kräfte mit dir zu messen?$"
#else
	.string "Oh, you will give me another\n"
	.string "opportunity to match wits with you?$"
#endif

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
#if GERMAN
	.string "Der Pool für meine Pokémon ist\n"
	.string "fast fertig.\p"
	.string "Du musst ihn dir anschauen!$"
#else
	.string "They're almost finished making the\n"
	.string "pool for my POKéMON.\p"
	.string "You must drop in for a visit.$"
#endif

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
#if GERMAN
	.string "Ich bin ein starker Läufer!\n"
	.string "Ich bin noch schneller jetzt!$"
#else
	.string "I'm a good runner.\n"
	.string "I've gotten even faster!$"
#endif

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
#if GERMAN
	.string "Heh, mein Kamerad! Lass uns die Zeit\n"
	.string "zusammen genießen!$"
#else
	.string "I say, friend!\n"
	.string "Let us enjoy our time together!$"
#endif

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
#if GERMAN
	.string "Ich bin der älteste der Vogel-brüder.\n"
	.string "Erinnerst du dich?\p"
	.string "Genau, ich bin derjenige, der Vögel\n"
	.string "wegen ihrer Schnäbel liebt!$"
#else
	.string "I'm the eldest of the BIRD\n"
	.string "BROTHERS. Remember me?\p"
	.string "That's right, I'm the one who loves\n"
	.string "birds for their beaks!$"
#endif

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
#if GERMAN
	.string "Ich bin der zweitälteste der\n"
	.string "Vogel-brüder.\p"
	.string "Ich bin derjenige, der Vögel wegen ihrer\n"
	.string "Flügel liebt!\l"
	.string "Lass uns erneut kämpfen!$"
#else
	.string "I'm the middle kid of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I'm the one that loves wings.\n"
	.string "Let's battle again!$"
#endif

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
#if GERMAN
	.string "Ich bin der jüngste der Vogel-brüder.\p"
	.string "Ich liebe Vögel ihres Gefieders wegen.\n"
	.string "Ich dachte nicht, dass wir uns wieder\l"
	.string "sehen würden.$"
#else
	.string "I'm the youngest of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I love birds for their down.\n"
	.string "I didn't think I'd see you again!$"
#endif

SixIsland_OutcastIsland_Text_TylorRematchIntro::
#if GERMAN
	.string "Ich habe immer noch kein Glück!\n"
	.string "Ein Kampf wäre ein Tempowechsel!$"
#else
	.string "I'm still having no luck at all.\n"
	.string "A battle'd be a change of pace!$"
#endif

SixIsland_OutcastIsland_Text_MymoRematchIntro::
#if GERMAN
	.string "Schnauf… schnauf…\p"
	.string "Ich bin erneut von Eiland Sechs\n"
	.string "ohne Pause hierher geschwommen.$"
#else
	.string "Gasp… Gasp…\p"
	.string "I swam here from SIX ISLAND's port\n"
	.string "in one go again.$"
#endif

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
#if GERMAN
	.string "Beim Schwimmen treffe ich immer\n"
	.string "auf dich!$"
#else
	.string "You always come along while I'm\n"
	.string "swimming.$"
#endif

SixIsland_OutcastIsland_Text_AvaRematchIntro::
#if GERMAN
	.string "Tina: Auf in einen erneuten\n"
	.string "Zwei-gegen-Zwei-Kampf im Wasser!$"
#else
	.string "AVA: Let's have another\n"
	.string "two-on-two marine battle today!$"
#endif

SixIsland_OutcastIsland_Text_GebRematchIntro::
#if GERMAN
	.string "Tino: Meine große Schwester und\n"
	.string "ich sind viel stärker als früher!$"
#else
	.string "GEB: My big sister and I are way\n"
	.string "tougher than before!$"
#endif

SixIsland_GreenPath_Text_JaclynRematchIntro::
#if GERMAN
	.string "… Häh?\p"
	.string "Ich sehe mein Haus vor meinem inneren\n"
	.string "Auge, aber Teleport bringt mich stets\l"
	.string "hierher!$"
#else
	.string "…Huh?\p"
	.string "I envision my house, but TELEPORT\n"
	.string "always brings me here!$"
#endif

SixIsland_WaterPath_Text_RoseRematchIntro::
#if GERMAN
	.string "Oh, hallo!\n"
	.string "Erneut weht ein angenehmes Lüftchen!$"
#else
	.string "Oh, hello.\n"
	.string "A pleasant breeze is blowing again.$"
#endif

SixIsland_WaterPath_Text_EdwardRematchIntro::
#if GERMAN
	.string "Hehe! Ich trainiere schon wieder\n"
	.string "heimlich!$"
#else
	.string "Hehehe, I'm practicing in secret\n"
	.string "again.$"
#endif

SixIsland_WaterPath_Text_SamirRematchIntro::
#if GERMAN
	.string "Wie? Du kannst keine Schwimmer\n"
	.string "wie mich mehr sehen?\p"
	.string "Ah! Sei doch nicht so!\n"
	.string "Lass uns lieber erneut kämpfen!$"
#else
	.string "What, you're sick of seeing\n"
	.string "SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!\n"
	.string "Battle with me again.$"
#endif

SixIsland_WaterPath_Text_DeniseRematchIntro::
#if GERMAN
	.string "Seufz…\n"
	.string "Mein Freund ist schon wieder\l"
	.string "beschäftigt…$"
#else
	.string "Sigh…\n"
	.string "My boyfriend's busy again…$"
#endif

SixIsland_WaterPath_Text_EarlRematchIntro::
#if GERMAN
	.string "Sag mir, wo in dieser Gegend die\n"
	.string "Berge liegen!$"
#else
	.string "Come on, tell me, where are the\n"
	.string "mountains around these parts?$"
#endif

SixIsland_WaterPath_Text_MiuRematchIntro::
#if GERMAN
	.string "Lea: Hallo Pokémon!\n"
	.string "Lass uns erneut spielen!$"
#else
	.string "MIU: Hello, POKéMON!\n"
	.string "It's time to play again!$"
#endif

SixIsland_WaterPath_Text_MiaRematchIntro::
#if GERMAN
	.string "Mia: Hallo Pokémon!\n"
	.string "Lass uns erneut kämpfen!$"
#else
	.string "MIA: Hello, POKéMON!\n"
	.string "It's time to battle again!$"
#endif

SixIsland_RuinValley_Text_StanlyRematchIntro::
#if GERMAN
	.string "Es gibt noch sehr viele ungelöste\n"
	.string "Rätsel in dieser Welt!$"
#else
	.string "There appear to be many secrets\n"
	.string "still unsolved in this world.$"
#endif

SixIsland_RuinValley_Text_FosterRematchIntro::
#if GERMAN
	.string "Hallo! Kennen wir uns nicht?\n"
	.string "Warum bist du zurückgekommen?$"
#else
	.string "Hi, didn't we meet before?\n"
	.string "What compelled you to come back?$"
#endif

SixIsland_RuinValley_Text_LarryRematchIntro::
#if GERMAN
	.string "Man sagt, dass es auf dieser Insel\n"
	.string "geheimnisvolle Steine geben soll.\p"
	.string "Hast du seit unserem letzten\n"
	.string "Treffen etwas herausgefunden?$"
#else
	.string "It's been said that there are\n"
	.string "mysterious stones on this island.\p"
	.string "Have you discovered anything since\n"
	.string "we last met?$"
#endif

SixIsland_RuinValley_Text_DarylRematchIntro::
#if GERMAN
	.string "Ein Rückkampf mit dir, hier oben?$"
#else
	.string "A rematch with you, so high up!$"
#endif

SixIsland_RuinValley_Text_HectorRematchIntro::
#if GERMAN
	.string "Ich kenne mich in dieser Gegend\n"
	.string "recht gut aus!$"
#else
	.string "I'm pretty familiar with the land\n"
	.string "around these parts.$"
#endif

SevenIsland_TrainerTower_Text_DarioRematchIntro::
#if GERMAN
	.string "Ich spürte, dass du kommst!$"
#else
	.string "I sensed your approach.$"
#endif

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
#if GERMAN
	.string "Irgendwo auf dieser Insel schlafen\n"
	.string "gewisse Pokémon!$"
#else
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
#if GERMAN
	.string "Hyah!\p"
	.string "Deine Rückkehr ändert nichts, ich\n"
	.string "werde dich mühelos pulverisieren!$"
#else
	.string "Kyahaha!\p"
	.string "Coming back won't change a thing.\n"
	.string "I'll flick you away effortlessly!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
#if GERMAN
	.string "Alles fit? Du bist in meinem Fanclub,\n"
	.string "oder?$"
#else
	.string "Howdy! You're a member of my\n"
	.string "fan club, isn't that right?$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
#if GERMAN
	.string "Diese Insel ist zu weitläufig…\n"
	.string "Hier Wache zu halten ist mühsam…$"
#else
	.string "This island is too spread out…\n"
	.string "Patrolling the place is a drag…$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
#if GERMAN
	.string "Menschen, die Pokémon missbrauchen,\n"
	.string "kann ich nicht vergeben!$"
#else
	.string "I don't forgive people who abuse\n"
	.string "POKéMON!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
#if GERMAN
	.string "Tizia: Ich kämpfe wieder mit Till\n"
	.string "zusammen!$"
#else
	.string "EVE: I'll team up with JON and\n"
	.string "battle together again.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
#if GERMAN
	.string "Till: An der Seite von Tizia habe ich\n"
	.string "stets das Gefühl, nicht verlieren zu\l"
	.string "können.$"
#else
	.string "JON: When I'm with EVE, it feels\n"
	.string "like we could never lose, not ever.$"
#endif

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
#if GERMAN
	.string "Lass uns erneut kämpfen!\n"
	.string "Ich bin heute in Topform!$"
#else
	.string "Let's have another battle.\n"
	.string "My conditioning's in top form!$"
#endif

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
#if GERMAN
	.string "Es macht nichts, wenn du die stärksten\n"
	.string "Pokémon hast…\p"
	.string "Wenn du mit ihnen nicht umzugehen\n"
	.string "weißt, bringt es dir nichts!$"
#else
	.string "It doesn't matter if you happen to\n"
	.string "have the strongest POKéMON…\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "know how to use them properly!$"
#endif

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
#if GERMAN
	.string "Ich arbeite im Naturschutz!\n"
	.string "Die Natur beschützt mich dafür!$"
#else
	.string "I work to protect the environment.\n"
	.string "In turn, nature protects me!$"
#endif

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
#if GERMAN
	.string "Bei jedem Treffen trägst du diese\n"
	.string "coolen Schuhe!$"
#else
	.string "Every time we meet, you have those\n"
	.string "snazzy shoes on.$"
#endif

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
#if GERMAN
	.string "Du musst stärker geworden sein!\n"
	.string "Darf ich gegen dich kämpfen?$"
#else
	.string "You must have gotten tougher.\n"
	.string "Let me battle you, please!$"
#endif

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
#if GERMAN
	.string "Mir wurde die beste Ausbildung\n"
	.string "zuteil, um so stark zu werden!\p"
	.string "Dieses Mal verliere ich nicht.\n"
	.string "Bestimmt nicht!$"
#else
	.string "I was given the best possible\n"
	.string "education to become this strong.\p"
	.string "I won't lose this time.\n"
	.string "Absolutely not!$"
#endif

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
#if GERMAN
	.string "Ole: Geliebte Grit, zusammen werden wir\n"
	.string "gewinnen!$"
#else
	.string "LEX: My darling NYA, together\n"
	.string "we will win for certain!$"
#endif

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
#if GERMAN
	.string "Grit: Ich enttäusche meinen Mentor\n"
	.string "Ole nicht! Wir werden gewinnen!$"
#else
	.string "NYA: I won't drag down my mentor\n"
	.string "LEX! We're going to win!$"
#endif

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
#if GERMAN
	.string "Hast du irgendetwas über diese\n"
	.string "Steinkammer herausgefunden?$"
#else
	.string "Have you discovered anything about\n"
	.string "this stone chamber?$"
#endif

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
#if GERMAN
	.string "Man sagt, ein geheimnisvolles\n"
	.string "Pokémon würde hier schlafen!$"
#else
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here.$"
#endif

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
#if GERMAN
	.string "Mein Lehrer zeigt mir, wie ich noch\n"
	.string "mehr malen kann.$"
#else
	.string "My teacher is showing me how to\n"
	.string "paint some more.$"
#endif

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
#if GERMAN
	.string "Heute sind wir nach dem Unterricht\n"
	.string "erneut in die Kammer gegangen!$"
#else
	.string "Today, in addition to our lesson,\n"
	.string "we came to see the chamber again.$"
#endif
